In [1]:
%run data_gather-Copy1.ipynb

{'_type': 'album',
 'api_path': '/albums/102298',
 'cover_art_thumbnail_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
 'cover_art_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
 'full_title': 'Euphoria Mourning by Chris Cornell',
 'id': 102298,
 'name': 'Euphoria Mourning',
 'name_with_artist': 'Euphoria Mourning (artist: Chris Cornell)',
 'primary_artist_names': 'Chris Cornell',
 'pusher_channel': 'album-102298',
 'release_date_components': {'year': 1999, 'month': 9, 'day': 21},
 'release_date_for_display': 'September 21, 1999',
 'updated_at': 1739842718,
 'url': 'https://genius.com/albums/Chris-cornell/Euphoria-mourning',
 'current_user_metadata': {'permissions': ['create_comment'],
                           'excluded_permissions': ['set_album_color_gradient',
                                                    'edit',
                                                    'destroy',
                                                    'pyong',
                                                    'lock',
                                                    'super_lock',
                                                    'unlock',
                                                    'sort_songs',
                                                    'hide',
                                                    'unhide',
                                                    'see_short_id',
                                                    'create_additional_role',
                                                    'create_question'],
                           'interactions': {'pyong': False, 'following': False},
                           'iq_by_action': {}},
 'artist': 'Chris Cornell',
 'primary_artists': [{'_type': 'artist',
                      'api_path': '/artists/18435',
                      'header_image_url': 'https://images.genius.com/b6a79ad3d1aa69a9dfb83168a82022f7.473x281x1.png',
                      'id': 18435,
                      'image_url': 'https://images.genius.com/13f0e2fe12d710928b62ec5a98778cc3.1000x1000x1.jpg',
                      'index_character': 'c',
                      'is_meme_verified': False,
                      'is_verified': False,
                      'links_config': None,
                      'name': 'Chris Cornell',
                      'slug': 'Chris-cornell',
                      'url': 'https://genius.com/artists/Chris-cornell'}],
 'album_type': 'album',
 'comment_count': 0,
 'custom_header_image_url': 'https://images.genius.com/588bfe15d081baa0ae31ed59960244c0.461x251x1.png',
 'description_preview': '',
 'header_image_url': 'https://images.genius.com/588bfe15d081baa0ae31ed59960244c0.461x251x1.png',
 'hidden': False,
 'language': None,
 'lock_state': 'editable',
 'pyongs_count': 0,
 'release_date': '1999-09-21',
 'tracking_paths': {'aggregate': '/albums/Chris-cornell/Euphoria-mourning',
                    'concurrent': '/albums/Chris-cornell/Euphoria-mourning'},
 'viewable_by_roles': [],
 'album_art_primary_color': '#b7bc57',
 'album_art_secondary_color': '#a0cbd6',
 'album_art_text_color': '#000',
 'song_pageviews': 138643,
 'album_relationships': [{'_type': 'album_relationship',
                          'relationship_type': 'deluxe_edition_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_deluxe_edition',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'alternate_version_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_alternate_version',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'reissue_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_reissue',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'remix_version_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_remix_version',
                          'albums': []}],
 'cover_arts': [{'_type': 'cover_art',
                 'annotated': False,
                 'api_path': '/albums/102298',
                 'id': 21402,
                 'image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
                 'thumbnail_image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
                 'url': 'https://genius.com/album_cover_arts/21402',
                 'current_user_metadata': {'permissions': [],
                                           'excluded_permissions': ['destroy']},
                 'description_annotation': {'_type': 'referent',
                                            'annotator_id': 2937273,
                                            'annotator_login': 'geniusbot',
                                            'api_path': '/referents/12001602',
                                            'classification': 'needs_exegesis',
                                            'fragment': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
                                            'id': 12001602,
                                            'ios_app_url': 'genius://referents/12001602',
                                            'is_description': True,
                                            'is_image': True,
                                            'path': '/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                            'range': {'content': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg'},
                                            'song_id': None,
                                            'url': 'https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                            'verified_annotator_ids': [],
                                            'current_user_metadata': {'permissions': [],
                                                                      'excluded_permissions': ['add_pinned_annotation_to',
                                                                                               'add_community_annotation_to'],
                                                                      'relationships': {}},
                                            'tracking_paths': {'aggregate': '/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                                               'concurrent': '/albums/Chris-cornell/Euphoria-mourning'},
                                            'twitter_share_message': '“?” '
                                                                     '—@Genius',
                                            'annotatable': {'_type': 'cover_art',
                                                            'api_path': '/albums/102298',
                                                            'context': 'Chris '
                                                                       'Cornell',
                                                            'id': 21402,
                                                            'image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
                                                            'link_title': 'Euphoria '
                                                                          'Mourning',
                                                            'title': 'Euphoria '
                                                                     'Mourning',
                                                            'type': 'CoverArt',
                                                            'url': 'https://genius.com/album_cover_arts/21402'},
                                            'annotations': [{'_type': 'annotation',
                                                             'api_path': '/annotations/12001602',
                                                             'being_created': False,
                                                             'body': {'plain': ''},
                                                             'comment_count': 0,
                                                             'community': True,
                                                             'created_at': 1496876077,
                                                             'custom_preview': None,
                                                             'deleted': False,
                                                             'embed_content': '<blockquote '
                                                                              "class='rg_standalone_container' "
                                                                              "data-src='//genius.com/annotations/12001602/standalone_embed'><a "
                                                                              "href='https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg'>https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg</a><br><a "
                                                                              "href='https://genius.com/album_cover_arts/21402'>&#8213; "
                                                                              'Euphoria '
                                                                              'Mourning</a></blockquote><script '
                                                                              'async '
                                                                              'crossorigin '
                                                                              "src='//genius.com/annotations/load_standalone_embeds.js'></script>",
                                                             'has_voters': False,
                                                             'id': 12001602,
                                                             'needs_exegesis': True,
                                                             'pinned': False,
                                                             'proposed_edit_count': 0,
                                                             'pyongs_count': None,
                                                             'referent_id': 12001602,
                                                             'share_url': 'https://genius.com/12001602',
                                                             'source': None,
                                                             'state': 'needs_exegesis',
                                                             'twitter_share_message': '“?” '
                                                                                      '—@Genius',
                                                             'url': 'https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                                             'verified': False,
                                                             'votes_total': 0,
                                                             'current_user_metadata': {'permissions': [],
                                                                                       'excluded_permissions': ['vote',
                                                                                                                'edit',
                                                                                                                'cosign',
                                                                                                                'uncosign',
                                                                                                                'destroy',
                                                                                                                'accept',
                                                                                                                'reject',
                                                                                                                'see_unreviewed',
                                                                                                                'clear_votes',
                                                                                                                'propose_edit_to',
                                                                                                                'pin_to_profile',
                                                                                                                'unpin_from_profile',
                                                                                                                'update_source',
                                                                                                                'edit_custom_preview',
                                                                                                                'report_as_abusive',
                                                                                                                'create_comment'],
                                                                                       'interactions': {'cosign': False,
                                                                                                        'pyong': False,
                                                                                                        'vote': None},
                                                                                       'iq_by_action': {}},
                                                             'accepted_by': None,
                                                             'authors': [{'_type': 'user_attribution',
                                                                          'attribution': 1.0,
                                                                          'pinned_role': None,
                                                                          'user': {'_type': 'user',
                                                                                   'about_me_summary': 'Hi! '
                                                                                                       'I’m '
                                                                                                       'the '
                                                                                                       'Genius '
                                                                                                       'Bot, '
                                                                                                       'a '
                                                                                                       'robotic '
                                                                                                       'user '
                                                                                                       'who '
                                                                                                       'performs '
                                                                                                       'automated '
                                                                                                       'tasks '
                                                                                                       'on '
                                                                                                       'the '
                                                                                                       'site. '
                                                                                                       'My '
                                                                                                       'behavior '
                                                                                                       'was '
                                                                                                       'programmed '
                                                                                                       'by '
                                                                                                       'the '
                                                                                                       'tech '
                                                                                                       'team, '
                                                                                                       'and '
                                                                                                       'my '
                                                                                                       'job '
                                                                                                       'is '
                                                                                                       'to '
                                                                                                       'help '
                                                                                                       'keep '
                                                                                                       'the '
                                                                                                       'site’s '
                                                                                                       'data '
                                                                                                       'crisp '
                                                                                                       'and '
                                                                                                       'clean.\n'
                                                                                                       '\n'
                                                                                                       'If '
                                                                                                       'I’ve '
                                                                                                       'rejected '
                                                                                                       'or '
                                                                                                       'deleted '
                                                                                                       'your '
                                                                                                       'annotation, '

In [2]:
%run data_cleaning-no-labels.ipynb

{'_type': 'album',
 'api_path': '/albums/102298',
 'cover_art_thumbnail_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
 'cover_art_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
 'full_title': 'Euphoria Mourning by Chris Cornell',
 'id': 102298,
 'name': 'Euphoria Mourning',
 'name_with_artist': 'Euphoria Mourning (artist: Chris Cornell)',
 'primary_artist_names': 'Chris Cornell',
 'pusher_channel': 'album-102298',
 'release_date_components': {'year': 1999, 'month': 9, 'day': 21},
 'release_date_for_display': 'September 21, 1999',
 'updated_at': 1739842718,
 'url': 'https://genius.com/albums/Chris-cornell/Euphoria-mourning',
 'current_user_metadata': {'permissions': ['create_comment'],
                           'excluded_permissions': ['set_album_color_gradient',
                                                    'edit',
                                                    'destroy',
                                                    'pyong',
                                                    'lock',
                                                    'super_lock',
                                                    'unlock',
                                                    'sort_songs',
                                                    'hide',
                                                    'unhide',
                                                    'see_short_id',
                                                    'create_additional_role',
                                                    'create_question'],
                           'interactions': {'pyong': False, 'following': False},
                           'iq_by_action': {}},
 'artist': 'Chris Cornell',
 'primary_artists': [{'_type': 'artist',
                      'api_path': '/artists/18435',
                      'header_image_url': 'https://images.genius.com/b6a79ad3d1aa69a9dfb83168a82022f7.473x281x1.png',
                      'id': 18435,
                      'image_url': 'https://images.genius.com/13f0e2fe12d710928b62ec5a98778cc3.1000x1000x1.jpg',
                      'index_character': 'c',
                      'is_meme_verified': False,
                      'is_verified': False,
                      'links_config': None,
                      'name': 'Chris Cornell',
                      'slug': 'Chris-cornell',
                      'url': 'https://genius.com/artists/Chris-cornell'}],
 'album_type': 'album',
 'comment_count': 0,
 'custom_header_image_url': 'https://images.genius.com/588bfe15d081baa0ae31ed59960244c0.461x251x1.png',
 'description_preview': '',
 'header_image_url': 'https://images.genius.com/588bfe15d081baa0ae31ed59960244c0.461x251x1.png',
 'hidden': False,
 'language': None,
 'lock_state': 'editable',
 'pyongs_count': 0,
 'release_date': '1999-09-21',
 'tracking_paths': {'aggregate': '/albums/Chris-cornell/Euphoria-mourning',
                    'concurrent': '/albums/Chris-cornell/Euphoria-mourning'},
 'viewable_by_roles': [],
 'album_art_primary_color': '#b7bc57',
 'album_art_secondary_color': '#a0cbd6',
 'album_art_text_color': '#000',
 'song_pageviews': 138643,
 'album_relationships': [{'_type': 'album_relationship',
                          'relationship_type': 'deluxe_edition_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_deluxe_edition',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'alternate_version_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_alternate_version',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'reissue_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_reissue',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'remix_version_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_remix_version',
                          'albums': []}],
 'cover_arts': [{'_type': 'cover_art',
                 'annotated': False,
                 'api_path': '/albums/102298',
                 'id': 21402,
                 'image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
                 'thumbnail_image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
                 'url': 'https://genius.com/album_cover_arts/21402',
                 'current_user_metadata': {'permissions': [],
                                           'excluded_permissions': ['destroy']},
                 'description_annotation': {'_type': 'referent',
                                            'annotator_id': 2937273,
                                            'annotator_login': 'geniusbot',
                                            'api_path': '/referents/12001602',
                                            'classification': 'needs_exegesis',
                                            'fragment': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
                                            'id': 12001602,
                                            'ios_app_url': 'genius://referents/12001602',
                                            'is_description': True,
                                            'is_image': True,
                                            'path': '/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                            'range': {'content': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg'},
                                            'song_id': None,
                                            'url': 'https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                            'verified_annotator_ids': [],
                                            'current_user_metadata': {'permissions': [],
                                                                      'excluded_permissions': ['add_pinned_annotation_to',
                                                                                               'add_community_annotation_to'],
                                                                      'relationships': {}},
                                            'tracking_paths': {'aggregate': '/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                                               'concurrent': '/albums/Chris-cornell/Euphoria-mourning'},
                                            'twitter_share_message': '“?” '
                                                                     '—@Genius',
                                            'annotatable': {'_type': 'cover_art',
                                                            'api_path': '/albums/102298',
                                                            'context': 'Chris '
                                                                       'Cornell',
                                                            'id': 21402,
                                                            'image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
                                                            'link_title': 'Euphoria '
                                                                          'Mourning',
                                                            'title': 'Euphoria '
                                                                     'Mourning',
                                                            'type': 'CoverArt',
                                                            'url': 'https://genius.com/album_cover_arts/21402'},
                                            'annotations': [{'_type': 'annotation',
                                                             'api_path': '/annotations/12001602',
                                                             'being_created': False,
                                                             'body': {'plain': ''},
                                                             'comment_count': 0,
                                                             'community': True,
                                                             'created_at': 1496876077,
                                                             'custom_preview': None,
                                                             'deleted': False,
                                                             'embed_content': '<blockquote '
                                                                              "class='rg_standalone_container' "
                                                                              "data-src='//genius.com/annotations/12001602/standalone_embed'><a "
                                                                              "href='https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg'>https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg</a><br><a "
                                                                              "href='https://genius.com/album_cover_arts/21402'>&#8213; "
                                                                              'Euphoria '
                                                                              'Mourning</a></blockquote><script '
                                                                              'async '
                                                                              'crossorigin '
                                                                              "src='//genius.com/annotations/load_standalone_embeds.js'></script>",
                                                             'has_voters': False,
                                                             'id': 12001602,
                                                             'needs_exegesis': True,
                                                             'pinned': False,
                                                             'proposed_edit_count': 0,
                                                             'pyongs_count': None,
                                                             'referent_id': 12001602,
                                                             'share_url': 'https://genius.com/12001602',
                                                             'source': None,
                                                             'state': 'needs_exegesis',
                                                             'twitter_share_message': '“?” '
                                                                                      '—@Genius',
                                                             'url': 'https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                                             'verified': False,
                                                             'votes_total': 0,
                                                             'current_user_metadata': {'permissions': [],
                                                                                       'excluded_permissions': ['vote',
                                                                                                                'edit',
                                                                                                                'cosign',
                                                                                                                'uncosign',
                                                                                                                'destroy',
                                                                                                                'accept',
                                                                                                                'reject',
                                                                                                                'see_unreviewed',
                                                                                                                'clear_votes',
                                                                                                                'propose_edit_to',
                                                                                                                'pin_to_profile',
                                                                                                                'unpin_from_profile',
                                                                                                                'update_source',
                                                                                                                'edit_custom_preview',
                                                                                                                'report_as_abusive',
                                                                                                                'create_comment'],
                                                                                       'interactions': {'cosign': False,
                                                                                                        'pyong': False,
                                                                                                        'vote': None},
                                                                                       'iq_by_action': {}},
                                                             'accepted_by': None,
                                                             'authors': [{'_type': 'user_attribution',
                                                                          'attribution': 1.0,
                                                                          'pinned_role': None,
                                                                          'user': {'_type': 'user',
                                                                                   'about_me_summary': 'Hi! '
                                                                                                       'I’m '
                                                                                                       'the '
                                                                                                       'Genius '
                                                                                                       'Bot, '
                                                                                                       'a '
                                                                                                       'robotic '
                                                                                                       'user '
                                                                                                       'who '
                                                                                                       'performs '
                                                                                                       'automated '
                                                                                                       'tasks '
                                                                                                       'on '
                                                                                                       'the '
                                                                                                       'site. '
                                                                                                       'My '
                                                                                                       'behavior '
                                                                                                       'was '
                                                                                                       'programmed '
                                                                                                       'by '
                                                                                                       'the '
                                                                                                       'tech '
                                                                                                       'team, '
                                                                                                       'and '
                                                                                                       'my '
                                                                                                       'job '
                                                                                                       'is '
                                                                                                       'to '
                                                                                                       'help '
                                                                                                       'keep '
                                                                                                       'the '
                                                                                                       'site’s '
                                                                                                       'data '
                                                                                                       'crisp '
                                                                                                       'and '
                                                                                                       'clean.\n'
                                                                                                       '\n'
                                                                                                       'If '
                                                                                                       'I’ve '
                                                                                                       'rejected '
                                                                                                       'or '
                                                                                                       'deleted '
                                                                                                       'your '
                                                                                                       'annotation, '

In [3]:
chris_cornell_df_without_labels.reset_index(drop=True)

,track_title,track_lyrics,album_name,project_name,release_year,label,processed_track_lyrics
0,Can’t Change Me,"[Verse 1] She can do anything at all Have anything she pleases The power to change what she thinks is wrong But what could she want with me? Yeah [Pre-Chorus] But wait just one minute here I can see that she's trying to read me (Suddenly I know) [Chorus] She's going to change the world She's going to change the world She's going to change the world But she can't change me No, she can't change me [Verse 2] She has the daylight at her command She gives the night its dreams, yeah She can uncover your darkest fear And make you forget you feel it [Pre-Chorus] But wait just one minute more I can see that she's trying to free me (Suddenly I know) [Chorus] She's going to change the world (Going to change the world) She's going to change the world (Going to change the world) She's going to change the world (Going to change) But she can't change me No, she can't change me [Bridge] And suddenly I can see everything that's wrong with me, yeah But what can I do? I'm the only thing I really have at all [Instrumental Break] [Pre-Chorus] But wait, just, one minute here I can see that she's trying to need me (Suddenly I know) [Chorus] She's going to change the world (Going to change the world) She's going to change the world (Going to change the world) She's going to change the world (Going to change) But she can't change me No, she can't change me",Euphoria Mourning,Chris Cornell,1999,A&M Records,she do she pleases power change she thinks wrong she want me ? wait minute i that she's trying read me suddenly i know she's going change world she's going change world she's going change world she can't change me no she can't change me she daylight her command she gives night dreams she uncover darkest fear you forget you feel it wait minute i that she's trying free me suddenly i know she's going change world going change world she's going change world going change world she's going change world going change she can't change me no she can't change me suddenly i that's wrong me i do ? i'm thing i break wait minute i that she's trying need me suddenly i know she's going change world going change world she's going change world going change world she's going change world going change she can't change me no she can't change me
1,Flutter Girl,"[Verse 1] I'm drinking dust with eyes of rust Tonight my tears might stain your wings So flutter home because you're better off alone than with me [Verse 2] So hide your face and tie your lace And butterflies across your cheek Forget how soon you become a fool for words when I speak [Chorus] Flutter girl You don't want to know what I live You don't want to take what I give Because I give nothing for free You don't want to know what I live You don't want to take what I give Because I give nothing for free [Verse 3] My hands are rough, my fingers cold And your heart's so young and so naive To ever feel for a moment that I might dare to believe [Chorus] Flutter girl You don't want to know what I live You don't want to take what I give Because I give nothing for free You don't want to know what I live You don't want to take what I give Because I give nothing for free [Bridge] I'll tear your wings As I melt in your smile As I run all your colors away [Chorus] Flutter girl You don't want to know what I live You don't want to take what I give Because I give nothing for free You don't want to know what I live You don't want to take what I give Because I give nothing for free [Outro] Flutter girl",Euphoria Mourning,Chris Cornell,1999,A&M Records,i'm drinking dust eyes rust tonight tears stain wings flutter home you're better me hide face tie lace butterflies cheek forget soon you fool words i speak flutter girl you don't want know i live you don't want i i free you don't want know i live you don't want i i free hands rough fingers cold heart's young naive feel moment that i dare believe flutter girl you don't want know i live you don't want i i free you don't want know i live you don't want i i free i tear wings i melt smile i run colors away flutter girl you don't want know i live you don't want i i free you don't want know i live you don't want i i free flutter girl
2,Preaching the End of the World,"[Verse 1] Hello, I know there's someone out there Who can understand and who's feeling the same way as me I'm 24 and I've got everything to live for But I know now that it wasn't meant to be [Verse] 'Cause all has been lost and all has been won And there's nothing left for us to save But now I know that I don't wanna be alone today So if you're finding you've been feeling just the same [Chorus] Call me now, it's alright It's just the end of the world You'll need a friend in the world 'Cause you can't hide So call and I'll get right back If your intentions are pure I'm seeking a friend for the end of the world [Verse] I've got a photograph, I'll send it off today You will see that I am perfectly sane Not for a lifetime or ""forever and a day"" 'Cause we know now that just won't be the case [Chorus] So call me now, it's alright It's just the end of the world You'll need a friend in the world 'Cause you can't hide So call and I'll get right back If your intentions are pure I'm seeking a friend for the end of the world [Bridge] With no commitment and no confessions And no little secrets to keep No little children or houses with roses Just the end of the world and me [Verse] 'Cause all has been gone and all has been done And there's nothing left for us to save But we could be together as they blow it all away And we could share in every moment as it breaks [Chorus] So call me now, it's alright It's just the end of the world You'll need a friend in the world 'Cause you can't hide So call and I'll get right back If your intentions are pure I'm seeking a friend for the end of the world [Chorus] So call me now, it's alright It's just the end of the world You'll need a friend in the world 'Cause you can't hide So call and I'll get right back If your intentions are pure I'm seeking a friend for the end of the world",Euphoria Mourning,Chris Cornell,1999,A&M Records,hello i know's understand's feeling way me i'm 24 i got live i know that it was n't meant'cause lost won's left us save i know that i don't wanna today you're finding you feeling me it's alright it's end world you need friend world'cause you can't hide i right intentions pure i'm seeking friend end world i got photograph i send it today you that i perfectly sane not lifetime forever day'cause we know that won't case me it's alright it's end world you need friend world'cause you can't hide i right intentions pure i'm seeking friend end world no commitment no confessions no little secrets no little children houses roses end world me'cause gone's left us save we they blow it away we share moment it breaks me it's alright it's end world you need friend world'cause you can't hide i right intentions pure i'm seeking friend end world me it's alright it's end world you need friend world'cause you can't hide i right intentions pure i'm seeking friend end world
3,Follow My Way,"[Verse 1] Little one, don't be a fool I'm a wreck when I look mighty In euphoria, I'm bruised In confusion, next I'm lightning In complacence, I am small Through oblivion I'm charged [Chorus] Follow my way when I'm not leading anyone Open and frayed when you can see that I'm unsure Out on my way, I'm only pure when I get lost And you're only needing when you're finding that I'm not [Verse 2] You're just looking for a boy Bathed in infrared and sunlight I'm all polish and reward When I'm confident, I'm hopeless Just like everybody else Right before they fall apart [Chorus] So follow my way when I am falling from your heart When I'm the pain, fever, and sweet relief in one Out on my way, though I'm not worthy of your trust Follow me down into a swan dive, all eyes closed tight [Bridge] Lowly, slowly, now I know I love where you go when you're gone Warm your hands inside my veins I might be contagious Through oblivion, I charge [Chorus] So follow my way when I am useless to your cause When I derail, calm in the patience of remorse Out on my way, out on my empty open nerves When all you know is that I don't know where we are When all you know is that I don't know Follow my way",Euphoria Mourning,Chris Cornell,1999,A&M Records,little don't fool i'm wreck i look mighty euphoria i'm bruised confusion i'm lightning complacence i small oblivion i'm charged follow way i'm not leading open frayed you that i'm unsure way i'm pure i lost you're needing you're finding that i'm not you're looking boy bathed infrared sunlight i'm polish reward i'm confident i'm hopeless like everybody right they fall apart follow way i falling heart i'm pain fever sweet relief way i'm not worthy trust follow me swan dive eyes closed tight lowly slowly i know i love you you're gone warm hands inside veins i contagious oblivion i charge follow way i useless cause i derail calm patience remorse way open nerves you know that i don't know we you know that i don't know follow way
4,When I’m Down,"[Verse 1] What say you now The door is opening on your vigil Now I'm in my usual way I save my breath, knowing what you're You're wanting me to say I only love you when I'm down [Verse 2] You say that midnight opens its arms to me Leaving you alone, then I fly so far away Until the light blurs my vision and I have nowhere to roam I only love you when I'm down Ooo [Chorus] And I only love you when I'm down And I'm only near you when I'm gone But one thing for you to keep in mind, you know That I'm down all the time, all the time [Verse 3] Well, I know you're reaching out and you You need to feel my hand You want to be understood Yeah, well, I understand I know you hold precious little hope for me And in your happiness, I'm always drowning in my grief [Chorus] And I only love you when I'm down, oh-oh And I'm only near you when I'm gone But one thing for you to keep in mind, you know That I'm down all the time, all the time [Outro] All the time All the time",Euphoria Mourning,Chris Cornell,1999,A&M Records,you door opening vigil i'm usual way i save breath knowing you're you're wanting me i love you i'm you that midnight opens arms me leaving you i fly far away light blurs vision i roam i love you i'm i love you i'm i'm near you i'm gone thing you mind you know that i'm time time i know you're reaching you you need feel hand you want understood i understand i know you hold precious little hope me happiness i'm drowning grief i love you i'm i'm near you i'm gone thing you mind you know that i'm time time time time
...,...,...,...,...,...,...,...
86,Times of Trouble,"[Verse 1] When the spoon is hot and the needle's sharp And you drift away, ooh, I can hear you say That the world in black is upon your back And your body shakes, so you ditch away Yeah, and you close the shades [Chorus 1] Don't try to do it, don't try to kill your time, oh Yeah, you might do it, then you can't change your mind, oh-oh, oh-oh-oh You gotta hold onto your time 'til you break through these times of Trouble [Verse 2] When you try to talk and the words get hard And they put you down, don't you stay Mm-mmm, don't ditch away [Chorus 2] I saw you swingin', yeah, swingin' your mother's sword, oh-oh-oh-oh-oh And yeah, yeah, yeah, I know you're playin', oh, sometimes the rules get hard, oh-oh, oh-oh-oh But if somebody left you out on a ledge If somebody pushed you over the edge You gotta hold on to your time and break through these times of Trouble [Harmonica Solo] [Chorus 2] I saw you swingin', yeah, swingin' your mother's sword, ooh And yeah, yeah, yeah, I know you're playin', but oh, sometimes the rules get hard, oh-oh-oh-oh-oh But if somebody left you on out on the ledge If somebody pushed you, you're over the edge If somebody loved you and left you for dead You gotta hold on to your time and break through these times of Trouble",Temple of the Dog,Temple of the Dog,1991,A&M Records,spoon hot needle's sharp you drift away i hear you that world black body shakes you ditch away you close shades don't try do it don't try kill time you do it you can't change mind you gotta hold time' til you break times trouble you try talk words hard they you don't you stay don't ditch away i saw you swingin' swingin' mother's sword i know you're playin' rules hard somebody left you ledge somebody pushed you edge you gotta hold time break times trouble harmonica i saw you swingin' swingin' mother's sword i know you're playin' rules hard somebody left you ledge somebody pushed you you're edge somebody loved you left you dead you gotta hold time break times trouble
87,Wooden Jesus,"[Verse 1] Wooden Jesus, where are you from? Korea or Canada or maybe Taiwan? But I didn't know it was the Holy Land But I believed from the minute the check left my hand, I pray [Chorus] Can I be saved? I spent all my money on a future grave Wooden Jesus, I'll cut you in On twenty percent of my future sin [Post-Chorus] I'll cut you in [Verse 2] Yeah, Porcelain Mary, her majesties pure Looking for virgin territory Coat-hanger halos that don't come cheap From television shepherds with livin' room sheep, and I pray [Chorus] Can I be saved? I spent all my money on a future grave Wooden Jesus, I'll cut you in On twenty percent of my future sin [Post-Chorus] I'll cut you in I'll cut you in [Guitar Solo] [Bridge] Hey, Wooden Jesus, where are you from? Korea or Canada or maybe Taiwan? But I didn't know it was the Holy Land! But I believed from the minute the check left my hand! [Chorus] Oh, can I be saved? I spent all my money on a future grave Wooden Jesus, I'll cut you in On twenty percent of my future sin [Outro] Hey! I'll cut you in, I'll cut you in I'll cut you in, I'll cut you in I'll cut you in, I'll cut you in Yeah Ooh-ooh-ooh-ooh, ooh",Temple of the Dog,Temple of the Dog,1991,A&M Records,wooden jesus you ? korea canada maybe taiwan ? i didn't know it was holy land i believed minute check left hand i pray i saved ? i spent money future grave wooden jesus i cut you percent future sin i cut you porcelain mary her majesties pure looking virgin territory coathanger halos that don't come cheap television shepherds livin' room sheep i pray i saved ? i spent money future grave wooden jesus i cut you percent future sin i cut you i cut you wooden jesus you ? korea canada maybe taiwan ? i didn't know it was holy land i believed minute check left hand i saved ? i spent money future grave wooden jesus i cut you percent future sin i cut you i cut you i cut you i cut you i cut you i cut you
88,Your Saviour,"[Verse 1] Yeah, people like you, I know myself Walk in the shoes of somebody else Whisper to me my tragic fate Whisper to me my tragic end [Chorus] But don't give me your savior Don't give me your savior I said, hey, yeah [Verse 2] Yeah, people, I choose life on my own Burn me your fuse, throw me your stone Give me your brand, burn on my hand Whisper to me my tragic end [Chorus] But don't give me your savior No, don't give me your savior I said, hey, yeah [Instrumental Break] [Verse 3] Oh, people I choose, I know myself Lay my need out, give you my help But you give me your blues and you whisper my fate But don't give me, don't give me, oh, your savior [Guitar Solo] [Outro] Don't give me, don't give me Whisper, hide your face Cry, hide your faith Whisper, hide your face Cry, hide your faith Whisper, hide your face Cry, hide your faith Whisper",Temple of the Dog,Temple of the Dog,1991,A&M Records,people like you i know myself walk shoes somebody whisper me tragic fate whisper me tragic end don't me savior don't me savior i said people i choose life burn me fuse throw me stone me brand burn hand whisper me tragic end don't me savior no don't me savior i said break people i choose i know myself lay need you help you me blues you whisper fate don't me don't me savior don't me don't me whisper hide face cry hide faith whisper hide face cry hide faith whisper hide face cry hide faith whisper
89,Four Walled World,"[Verse 1] Well, she cries, and she cries All night to the sound of the freeway hum And she swears she'll be gone when the sun hits the ground And she ain't comin' back to my cell To my cell, ooh [Verse 2] Well she's tired, and she's tired Of this life she's been leadin' too long And the time turns around through these walls that surround To the chimes of a jailer's song [Chorus] Oh, but in my four, yeah, in my four In my four, my four-walled world In my four, yeah, in my four In my four, my four-walled world [Verse 3] Yeah, she tries, and she tries But my feet, they just won't leave the ground And I'm tired, and I'm tired of this prisoner's life And these chains that drag me down [Chorus] Oh, but in my four, in my four Yeah, in my four, in my four-walled world Yeah, in my four, oh, in my four Yeah, in my four, my four-walled world [Verse 1] Well she cries, and she cries All night to the sound of the freeway hum And she swears she'll be gone when the sun hits the ground And she ain't, no she ain't comin' back to my cell! [Bridge] Now the sun is low And these walls try to break my soul Now the moon is full And I won't see nothin' tonight but the tear in her eyes [Outro] In my four Yeah, in my four world Yeah, in my four-walled world Yeah, in my four, my four, yeah, my four, oh, my four-walled world Yeah, in my four-walled world, yeah In my four, in my four-walled world, yeah In my four, in my four, in my four-walled world, yeah, yeah In my four-walled world, yeah, yeah, yeah Oh, in my four, in my four-walled world, yeah Four! In my four! In my four-walled world, yeah In my four-walled world, yeah",Temple of the Dog,Temple of the Dog,1991,A&M Records,she cries she cries night sound freeway hum she swears she gone sun hits ground she ain't comin' cell cell she's tired she's tired life she's leadin' long time turns walls that surround chimes jailer's song fourwalled world fourwalled world she tries she tries feet they won't leave ground i'm tired i'm tired prisoner's life chains that drag me fourwalled world fourwalled world she cries she cries night sound freeway hum she swears she gone sun hits ground she ain't no she ain't comin' cell sun low walls try break soul moon i won't nothin' tonight tear her eyes world fourwalled world fourwalled world fourwalled world fourwalled world fourwalled world fourwalled world fourwalled world fourwalled world fourwalled world

In [4]:
import re
from collections import Counter

text = chris_cornell_df_without_labels.loc[chris_cornell_df_without_labels["album_name"] == "Euphoria Mourning", "processed_track_lyrics"]

words = text.str.split(" ").sum()

Counter(words).most_common(30)

[('you', 110),
 ('i', 95),
 ("i'm", 55),
 ("it's", 30),
 ('me', 25),
 ('know', 25),
 ('world', 24),
 ('change', 22),
 ('that', 19),
 ('want', 17),
 ("you're", 17),
 ('rain', 17),
 ('going', 16),
 ("don't", 16),
 ('sweet', 15),
 ('steel', 15),
 ('she', 13),
 ('like', 13),
 ('taking', 13),
 ("she's", 12),
 ('way', 12),
 ('come', 12),
 ("can't", 11),
 ('it', 11),
 ('away', 11),
 ('love', 11),
 ('no', 10),
 ('today', 10),
 ('alright', 10),
 ('falling', 10)]

QUESTION 1a: How did Chris Cornell’s use of pronouns change when looking at the first solo album versus last solo album?

First solo album: Euphoria Mourning
[('you', 110),
 ('i', 95),
 ("i'm", 55),
 ("it's", 30),
 ('me', 25),
 ("you're", 17),
 ('she', 13),
 ("she's", 12),
 ('it', 11),
 ("we're", 7),
 ('we', 5),
 ('us', 3)

Question 2a: What are the top 10 nouns Chris Cornell uses in each album. How many of them are concrete and how many are abstract? 

First solo album: Euphoria Morning 

NOTE: combined i, i'm, and me even though one's in the subjective and one's in the objective since they're referring to the same noun 


('you', 110), ("you're", 17),
 ('i', 95), ("i'm", 55), ('me', 21),
 ('world', 24),
 ('change', 22),
 ('steel', 15),
 ('she', 13),("she's", 12),
 ('way', 12),
 ('rain', 12),
 ('love', 11),
('mission', 10),]

In [5]:
# text = chris_cornell_df_without_labels.loc[chris_cornell_df_without_labels["album_name"] == "Higher Truth", "processed_track_lyrics"]

# words = text.str.split(" ").sum()

# counts=Counter(words)

# counts_df = pd.DataFrame(
#     counts.items(),
#     columns=["word", "count"]
# )

# counts_df = counts_df.sort_values("count", ascending = False)

In [6]:
first = ["i", "i'm", "me", "my", "mine", "myself",
         "we", "us", "our", "ours", "ourselves"]

second = ["you", "your", "yours", "yourself", "yourselves"]

third = ["he", "he's", "him", "his", "himself",
         "she", "she's", "her", "hers", "herself",
         "it", "it's", "its", "itself",
         "they", "them", "their", "theirs", "themselves"]

In [16]:
#Create new dataframe for pronoun counts per album and by each pronoun person (first, second, third)

album_data = chris_cornell_df_without_labels[
    chris_cornell_df_without_labels["album_name"].isin(
        ["Euphoria Mourning",
         "Higher Truth",
         "Ultramega OK",
         "King Animal",
         "Audioslave",
         "Revelations",
        "Temple of the Dog"])]

counts = []

for album, group in album_data.groupby("album_name"):
    album_words = " ".join(group["processed_track_lyrics"]).split()
    counter = Counter(album_words)
    
    counts.append({
        "album": album,
        "pronoun": "First",
        "pronoun_count": sum(counter[first_person] for first_person in first)
    })
    
    counts.append({
        "album": album,
        "pronoun": "Second",
        "pronoun_count": sum(counter[second_person] for second_person in second)
    })
    
    counts.append({
        "album": album,
        "pronoun": "Third",
        "pronoun_count": sum(counter[third_person] for third_person in third)
    })


pronoun_count_df = pd.DataFrame(counts)

pronoun_count_df

                album pronoun  pronoun_count
0          Audioslave   First            224
1          Audioslave  Second            169
2          Audioslave   Third             86
3   Euphoria Mourning   First            183
4   Euphoria Mourning  Second            113
5   Euphoria Mourning   Third             69
6        Higher Truth   First            270
7        Higher Truth  Second            122
8        Higher Truth   Third            115
9         King Animal   First            195
10        King Animal  Second             69
11        King Animal   Third             38
12        Revelations   First            174
13        Revelations  Second             53
14        Revelations   Third             51
15  Temple of the Dog   First            178
16  Temple of the Dog  Second             79
17  Temple of the Dog   Third             80
18       Ultramega OK   First             54
19       Ultramega OK  Second             22
20       Ultramega OK   Third             79

In [17]:
euphoria_higher = pronoun_count_df[
    pronoun_count_df["album"].isin(["Euphoria Mourning", "Higher Truth"])
]

ultramega_king = pronoun_count_df[
    pronoun_count_df["album"].isin(["Ultramega OK", "King Animal"])
]

audioslave_revelations = pronoun_count_df[
    pronoun_count_df["album"].isin(["Audioslave", "Revelations"])
]

In [18]:
#Create new lists to add as new columns to new dataframe 

word_count_processed_lyrics = []

text = chris_cornell_df_without_labels['processed_track_lyrics']

for text in chris_cornell_df_without_labels["processed_track_lyrics"]:
    tokens = text.split()
    word_count_processed_lyrics.append(len(tokens))

chris_cornell_df_without_labels["word_count_processed_lyrics"] = word_count_processed_lyrics

In [19]:
total_word_count_euphoriamourning = chris_cornell_df_without_labels.loc[chris_cornell_df_without_labels['album_name'] == 'Euphoria Mourning', 'word_count_processed_lyrics'].sum()

total_word_count_highertruth = chris_cornell_df_without_labels.loc[chris_cornell_df_without_labels['album_name'] == 'Higher Truth', 'word_count_processed_lyrics'].sum()

total_word_count_ultramegaok = chris_cornell_df_without_labels.loc[chris_cornell_df_without_labels['album_name'] == 'Ultramega OK', 'word_count_processed_lyrics'].sum()

total_word_count_kinganimal = chris_cornell_df_without_labels.loc[chris_cornell_df_without_labels['album_name'] == 'King Animal', 'word_count_processed_lyrics'].sum()

total_word_count_audioslave = chris_cornell_df_without_labels.loc[chris_cornell_df_without_labels['album_name'] == 'Audioslave', 'word_count_processed_lyrics'].sum()

total_word_count_revelations = chris_cornell_df_without_labels.loc[chris_cornell_df_without_labels['album_name'] == 'Revelations', 'word_count_processed_lyrics'].sum()

total_word_count_temple = chris_cornell_df_without_labels.loc[chris_cornell_df_without_labels['album_name'] == 'Temple of the Dog', 'word_count_processed_lyrics'].sum()

1535 euphoria morrning
2280 higher truth
908 ultramegaok
1483 kinganimal
1569 audioslave
1545 revelations 
1375 temple

In [20]:
word_count_totals = {
    'Euphoria Mourning': 1535,
    'Higher Truth': 2280,
    'Ultramega OK': 908,
    'King Animal': 1483,
    'Audioslave': 1569,
    'Revelations': 1545,
    'Temple of the Dog': 1375}

pronoun_count_df['total_word_count'] =  pronoun_count_df['album'].map(word_count_totals)

In [21]:
pronoun_count_df

                album pronoun  pronoun_count  total_word_count
0          Audioslave   First            224              1569
1          Audioslave  Second            169              1569
2          Audioslave   Third             86              1569
3   Euphoria Mourning   First            183              1535
4   Euphoria Mourning  Second            113              1535
5   Euphoria Mourning   Third             69              1535
6        Higher Truth   First            270              2280
7        Higher Truth  Second            122              2280
8        Higher Truth   Third            115              2280
9         King Animal   First            195              1483
10        King Animal  Second             69              1483
11        King Animal   Third             38              1483
12        Revelations   First            174              1545
13        Revelations  Second             53              1545
14        Revelations   Third             51              1545
15  Temple of the Dog   First            178              1375
16  Temple of the Dog  Second             79              1375
17  Temple of the Dog   Third             80              1375
18       Ultramega OK   First             54               908
19       Ultramega OK  Second             22               908
20       Ultramega OK   Third             79               908

In [22]:
pronoun_count_df['pronoun_percentage'] = (pronoun_count_df['pronoun_count'] / pronoun_count_df['total_word_count'])*100

In [23]:
pronoun_count_df=pronoun_count_df.round(2)

In [24]:
pronoun_bar_chart_df = pronoun_count_df.pivot(
    index="album",
    columns="pronoun",
    values="pronoun_percentage").reset_index()

In [25]:
pronoun_bar_chart_df

pronoun              album  First  Second  Third
0               Audioslave  14.28   10.77   5.48
1        Euphoria Mourning  11.92    7.36   4.50
2             Higher Truth  11.84    5.35   5.04
3              King Animal  13.15    4.65   2.56
4              Revelations  11.26    3.43   3.30
5        Temple of the Dog  12.95    5.75   5.82
6             Ultramega OK   5.95    2.42   8.70

In [26]:
pronoun_bar_chart_df.to_csv("pronoun_count_df.csv")