In [ ]:
#!pip install lyricsgenius
#https://pypi.org/project/lyricsgenius/

In [1]:
import lyricsgenius

In [2]:
genius = lyricsgenius.Genius("NA_X8Wlr63RHWwTJikhX3F5rfy86E5gT5RSjiU-ty04P3znjGVg6c_GZG-9csR42")

In [3]:
lyricsgenius.enable_logging()

In [77]:
album = genius.search_album("Euphoria Morning", "Chris Cornell")
album.save_lyrics()

INFO lyricsgenius.genius: Searching for "Euphoria Morning" by Chris Cornell...
DEBUG urllib3.connectionpool: Starting new HTTPS connection (2): genius.com:443
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/search/multi?q=Euphoria+Morning+Chris+Cornell HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/albums/102298?text_format=plain HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/albums/102298/tracks?per_page=50&page=1&text_format=plain HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-cant-change-me-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-flutter-girl-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-preaching-the-end-of-the-world-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-follow-my-way-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-when-im-down-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-mission-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-wave-goodbye-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-moonchild-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-sweet-euphoria-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-disappearing-one-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-pillow-of-your-bones-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-steel-rain-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-sunshower-lyrics HTTP/2.0" 200 None

saved_album_lyrics_chris_cornell_euphoria_mourning.json already exists. Overwrite?
(y/n):  n

DEBUG lyricsgenius.types.base: Skipping file save.

In [78]:
import json

with open('saved_album_lyrics_chris_cornell_euphoria_mourning.json') as euphoria_mourning:
    euphoria_mourning = json.load(euphoria_mourning)
    euphoria_mourning

In [6]:
import pprint

In [79]:
pprint.pp(euphoria_mourning)

{'_type': 'album',
 'api_path': '/albums/102298',
 'cover_art_thumbnail_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
 'cover_art_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
 'full_title': 'Euphoria Mourning by Chris Cornell',
 'id': 102298,
 'name': 'Euphoria Mourning',
 'name_with_artist': 'Euphoria Mourning (artist: Chris Cornell)',
 'primary_artist_names': 'Chris Cornell',
 'pusher_channel': 'album-102298',
 'release_date_components': {'year': 1999, 'month': 9, 'day': 21},
 'release_date_for_display': 'September 21, 1999',
 'updated_at': 1739842718,
 'url': 'https://genius.com/albums/Chris-cornell/Euphoria-mourning',
 'current_user_metadata': {'permissions': ['create_comment'],
                           'excluded_permissions': ['set_album_color_gradient',
                                                    'edit',
                                                    'destroy',
                                                    'pyong',
                                                    'lock',
                                                    'super_lock',
                                                    'unlock',
                                                    'sort_songs',
                                                    'hide',
                                                    'unhide',
                                                    'see_short_id',
                                                    'create_additional_role',
                                                    'create_question'],
                           'interactions': {'pyong': False, 'following': False},
                           'iq_by_action': {}},
 'artist': 'Chris Cornell',
 'primary_artists': [{'_type': 'artist',
                      'api_path': '/artists/18435',
                      'header_image_url': 'https://images.genius.com/b6a79ad3d1aa69a9dfb83168a82022f7.473x281x1.png',
                      'id': 18435,
                      'image_url': 'https://images.genius.com/13f0e2fe12d710928b62ec5a98778cc3.1000x1000x1.jpg',
                      'index_character': 'c',
                      'is_meme_verified': False,
                      'is_verified': False,
                      'links_config': None,
                      'name': 'Chris Cornell',
                      'slug': 'Chris-cornell',
                      'url': 'https://genius.com/artists/Chris-cornell'}],
 'album_type': 'album',
 'comment_count': 0,
 'custom_header_image_url': 'https://images.genius.com/588bfe15d081baa0ae31ed59960244c0.461x251x1.png',
 'description_preview': '',
 'header_image_url': 'https://images.genius.com/588bfe15d081baa0ae31ed59960244c0.461x251x1.png',
 'hidden': False,
 'language': None,
 'lock_state': 'editable',
 'pyongs_count': 0,
 'release_date': '1999-09-21',
 'tracking_paths': {'aggregate': '/albums/Chris-cornell/Euphoria-mourning',
                    'concurrent': '/albums/Chris-cornell/Euphoria-mourning'},
 'viewable_by_roles': [],
 'album_art_primary_color': '#b7bc57',
 'album_art_secondary_color': '#a0cbd6',
 'album_art_text_color': '#000',
 'song_pageviews': 138643,
 'album_relationships': [{'_type': 'album_relationship',
                          'relationship_type': 'deluxe_edition_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_deluxe_edition',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'alternate_version_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_alternate_version',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'reissue_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_reissue',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'remix_version_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_remix_version',
                          'albums': []}],
 'cover_arts': [{'_type': 'cover_art',
                 'annotated': False,
                 'api_path': '/albums/102298',
                 'id': 21402,
                 'image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
                 'thumbnail_image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
                 'url': 'https://genius.com/album_cover_arts/21402',
                 'current_user_metadata': {'permissions': [],
                                           'excluded_permissions': ['destroy']},
                 'description_annotation': {'_type': 'referent',
                                            'annotator_id': 2937273,
                                            'annotator_login': 'geniusbot',
                                            'api_path': '/referents/12001602',
                                            'classification': 'needs_exegesis',
                                            'fragment': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
                                            'id': 12001602,
                                            'ios_app_url': 'genius://referents/12001602',
                                            'is_description': True,
                                            'is_image': True,
                                            'path': '/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                            'range': {'content': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg'},
                                            'song_id': None,
                                            'url': 'https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                            'verified_annotator_ids': [],
                                            'current_user_metadata': {'permissions': [],
                                                                      'excluded_permissions': ['add_pinned_annotation_to',
                                                                                               'add_community_annotation_to'],
                                                                      'relationships': {}},
                                            'tracking_paths': {'aggregate': '/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                                               'concurrent': '/albums/Chris-cornell/Euphoria-mourning'},
                                            'twitter_share_message': '“?” '
                                                                     '—@Genius',
                                            'annotatable': {'_type': 'cover_art',
                                                            'api_path': '/albums/102298',
                                                            'context': 'Chris '
                                                                       'Cornell',
                                                            'id': 21402,
                                                            'image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
                                                            'link_title': 'Euphoria '
                                                                          'Mourning',
                                                            'title': 'Euphoria '
                                                                     'Mourning',
                                                            'type': 'CoverArt',
                                                            'url': 'https://genius.com/album_cover_arts/21402'},
                                            'annotations': [{'_type': 'annotation',
                                                             'api_path': '/annotations/12001602',
                                                             'being_created': False,
                                                             'body': {'plain': ''},
                                                             'comment_count': 0,
                                                             'community': True,
                                                             'created_at': 1496876077,
                                                             'custom_preview': None,
                                                             'deleted': False,
                                                             'embed_content': '<blockquote '
                                                                              "class='rg_standalone_container' "
                                                                              "data-src='//genius.com/annotations/12001602/standalone_embed'><a "
                                                                              "href='https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg'>https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg</a><br><a "
                                                                              "href='https://genius.com/album_cover_arts/21402'>&#8213; "
                                                                              'Euphoria '
                                                                              'Mourning</a></blockquote><script '
                                                                              'async '
                                                                              'crossorigin '
                                                                              "src='//genius.com/annotations/load_standalone_embeds.js'></script>",
                                                             'has_voters': False,
                                                             'id': 12001602,
                                                             'needs_exegesis': True,
                                                             'pinned': False,
                                                             'proposed_edit_count': 0,
                                                             'pyongs_count': None,
                                                             'referent_id': 12001602,
                                                             'share_url': 'https://genius.com/12001602',
                                                             'source': None,
                                                             'state': 'needs_exegesis',
                                                             'twitter_share_message': '“?” '
                                                                                      '—@Genius',
                                                             'url': 'https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                                             'verified': False,
                                                             'votes_total': 0,
                                                             'current_user_metadata': {'permissions': [],
                                                                                       'excluded_permissions': ['vote',
                                                                                                                'edit',
                                                                                                                'cosign',
                                                                                                                'uncosign',
                                                                                                                'destroy',
                                                                                                                'accept',
                                                                                                                'reject',
                                                                                                                'see_unreviewed',
                                                                                                                'clear_votes',
                                                                                                                'propose_edit_to',
                                                                                                                'pin_to_profile',
                                                                                                                'unpin_from_profile',
                                                                                                                'update_source',
                                                                                                                'edit_custom_preview',
                                                                                                                'report_as_abusive',
                                                                                                                'create_comment'],
                                                                                       'interactions': {'cosign': False,
                                                                                                        'pyong': False,
                                                                                                        'vote': None},
                                                                                       'iq_by_action': {}},
                                                             'accepted_by': None,
                                                             'authors': [{'_type': 'user_attribution',
                                                                          'attribution': 1.0,
                                                                          'pinned_role': None,
                                                                          'user': {'_type': 'user',
                                                                                   'about_me_summary': 'Hi! '
                                                                                                       'I’m '
                                                                                                       'the '
                                                                                                       'Genius '
                                                                                                       'Bot, '
                                                                                                       'a '
                                                                                                       'robotic '
                                                                                                       'user '
                                                                                                       'who '
                                                                                                       'performs '
                                                                                                       'automated '
                                                                                                       'tasks '
                                                                                                       'on '
                                                                                                       'the '
                                                                                                       'site. '
                                                                                                       'My '
                                                                                                       'behavior '
                                                                                                       'was '
                                                                                                       'programmed '
                                                                                                       'by '
                                                                                                       'the '
                                                                                                       'tech '
                                                                                                       'team, '
                                                                                                       'and '
                                                                                                       'my '
                                                                                                       'job '
                                                                                                       'is '
                                                                                                       'to '
                                                                                                       'help '
                                                                                                       'keep '
                                                                                                       'the '
                                                                                                       'site’s '
                                                                                                       'data '
                                                                                                       'crisp '
                                                                                                       'and '
                                                                                                       'clean.\n'
                                                                                                       '\n'
                                                                                                       'If '
                                                                                                       'I’ve '
                                                                                                       'rejected '
                                                                                                       'or '
                                                                                                       'deleted '
                                                                                                       'your '
                                                                                                       'annotation, '

In [80]:
euphoria_mourning['tracks'][0]['song']['lyrics']

"[Verse 1]\nShe can do anything at all\nHave anything she pleases\nThe power to change what she thinks is wrong\nBut what could she want with me? Yeah\n\n[Pre-Chorus]\nBut wait just one minute here\nI can see that she's trying to read me\n(Suddenly I know)\n\n[Chorus]\nShe's going to change the world\nShe's going to change the world\nShe's going to change the world\nBut she can't change me\nNo, she can't change me\n\n[Verse 2]\nShe has the daylight at her command\nShe gives the night its dreams, yeah\nShe can uncover your darkest fear\nAnd make you forget you feel it\n\n[Pre-Chorus]\nBut wait just one minute more\nI can see that she's trying to free me\n(Suddenly I know)\n\n[Chorus]\nShe's going to change the world (Going to change the world)\nShe's going to change the world (Going to change the world)\nShe's going to change the world (Going to change)\nBut she can't change me\nNo, she can't change me\n\n[Bridge]\nAnd suddenly I can see everything that's wrong with me, yeah\nBut what can I do? I'm the only thing I really have at all\n\n[Instrumental Break]\n\n[Pre-Chorus]\nBut wait, just, one minute here\nI can see that she's trying to need me\n(Suddenly I know)\n\n[Chorus]\nShe's going to change the world (Going to change the world)\nShe's going to change the world (Going to change the world)\nShe's going to change the world (Going to change)\nBut she can't change me\nNo, she can't change me"

In [81]:
for track_lyric in euphoria_mourning['tracks']:
    print(track_lyric['song']['lyrics'])

[Verse 1]
She can do anything at all
Have anything she pleases
The power to change what she thinks is wrong
But what could she want with me? Yeah

[Pre-Chorus]
But wait just one minute here
I can see that she's trying to read me
(Suddenly I know)

[Chorus]
She's going to change the world
She's going to change the world
She's going to change the world
But she can't change me
No, she can't change me

[Verse 2]
She has the daylight at her command
She gives the night its dreams, yeah
She can uncover your darkest fear
And make you forget you feel it

[Pre-Chorus]
But wait just one minute more
I can see that she's trying to free me
(Suddenly I know)

[Chorus]
She's going to change the world (Going to change the world)
She's going to change the world (Going to change the world)
She's going to change the world (Going to change)
But she can't change me
No, she can't change me

[Bridge]
And suddenly I can see everything that's wrong with me, yeah
But what can I do? I'm the only thing I really have at all

[Instrumental Break]

[Pre-Chorus]
But wait, just, one minute here
I can see that she's trying to need me
(Suddenly I know)

[Chorus]
She's going to change the world (Going to change the world)
She's going to change the world (Going to change the world)
She's going to change the world (Going to change)
But she can't change me
No, she can't change me
[Verse 1]
I'm drinking dust with eyes of rust
Tonight my tears might stain your wings
So flutter home because you're better off alone than with me

[Verse 2]
So hide your face and tie your lace
And butterflies across your cheek
Forget how soon you become a fool for words when I speak

[Chorus]
Flutter girl
You don't want to know what I live
You don't want to take what I give
Because I give nothing for free
You don't want to know what I live
You don't want to take what I give
Because I give nothing for free

[Verse 3]
My hands are rough, my fingers cold
And your heart's so young and so naive
To ever feel for a moment that I might dare to believe

[Chorus]
Flutter girl
You don't want to know what I live
You don't want to take what I give
Because I give nothing for free
You don't want to know what I live
You don't want to take what I give
Because I give nothing for free

[Bridge]
I'll tear your wings
As I melt in your smile
As I run all your colors away

[Chorus]
Flutter girl
You don't want to know what I live
You don't want to take what I give
Because I give nothing for free
You don't want to know what I live
You don't want to take what I give
Because I give nothing for free

[Outro]
Flutter girl
[Verse 1]
Hello, I know there's someone out there
Who can understand and who's feeling the same way as me
I'm 24 and I've got everything to live for
But I know now that it wasn't meant to be

[Verse]
'Cause all has been lost and all has been won
And there's nothing left for us to save
But now I know that I don't wanna be alone today
So if you're finding you've been feeling just the same

[Chorus]
Call me now, it's alright
It's just the end of the world
You'll need a friend in the world
'Cause you can't hide
So call and I'll get right back
If your intentions are pure
I'm seeking a friend for the end of the world

[Verse]
I've got a photograph, I'll send it off today
You will see that I am perfectly sane
Not for a lifetime or "forever and a day"
'Cause we know now that just won't be the case

[Chorus]
So call me now, it's alright
It's just the end of the world
You'll need a friend in the world
'Cause you can't hide
So call and I'll get right back
If your intentions are pure
I'm seeking a friend for the end of the world

[Bridge]
With no commitment and no confessions
And no little secrets to keep
No little children or houses with roses
Just the end of the world and me

[Verse]
'Cause all has been gone and all has been done
And there's nothing left for us to save
But we could be together as they blow it all away
And we could share in every moment as it breaks

[Chorus]
So call me now, it's alright
It's just the end of the world
You'll need a friend in the world
'Cause you can't hide
So call and I'll get right back
If your intentions are pure
I'm seeking a friend for the end of the world

[Chorus]
So call me now, it's alright
It's just the end of the world
You'll need a friend in the world
'Cause you can't hide
So call and I'll get right back
If your intentions are pure
I'm seeking a friend for the end of the world
[Verse 1]
Little one, don't be a fool
I'm a wreck when I look mighty
In euphoria, I'm bruised
In confusion, next I'm lightning
In complacence, I am small
Through oblivion I'm charged

[Chorus]
Follow my way when I'm not leading anyone
Open and frayed when you can see that I'm unsure
Out on my way, I'm only pure when I get lost
And you're only needing when you're finding that I'm not

[Verse 2]
You're just looking for a boy
Bathed in infrared and sunlight
I'm all polish and reward
When I'm confident, I'm hopeless
Just like everybody else
Right before they fall apart

[Chorus]
So follow my way when I am falling from your heart
When I'm the pain, fever, and sweet relief in one
Out on my way, though I'm not worthy of your trust
Follow me down into a swan dive, all eyes closed tight

[Bridge]
Lowly, slowly, now I know
I love where you go when you're gone
Warm your hands inside my veins
I might be contagious
Through oblivion, I charge

[Chorus]
So follow my way when I am useless to your cause
When I derail, calm in the patience of remorse
Out on my way, out on my empty open nerves
When all you know is that I don't know where we are
When all you know is that I don't know
Follow my way
[Verse 1]
What say you now
The door is opening on your vigil
Now I'm in my usual way
I save my breath, knowing what you're
You're wanting me to say
I only love you when I'm down

[Verse 2]
You say that midnight opens its arms to me
Leaving you alone, then I fly so far away
Until the light blurs my vision and I have nowhere to roam
I only love you when I'm down
Ooo

[Chorus]
And I only love you when I'm down
And I'm only near you when I'm gone
But one thing for you to keep in mind, you know
That I'm down all the time, all the time

[Verse 3]
Well, I know you're reaching out and you
You need to feel my hand
You want to be understood
Yeah, well, I understand
I know you hold precious little hope for me
And in your happiness, I'm always drowning in my grief

[Chorus]
And I only love you when I'm down, oh-oh
And I'm only near you when I'm gone
But one thing for you to keep in mind, you know
That I'm down all the time, all the time

[Outro]
All the time
All the time
[Verse 1]
Pulled through you and drowning in your swirl
Circling, unfolding in your will
I'm gonna glide on the winds of your breathing
And alight on your guarded heart
I'm going to tear all your temples down

[Chorus]
I'm on a mission now
I'm on a mission now

[Verse 2]
Smoldering down inside your mood
Slithering and fanning in your eyes
I'm gonna dive through your crying and sleep in your hair
Rise from your ashes and kneel in your prayers
Tear all your temples down

[Chorus]
I'm on a mission now
I'm on a mission now
I'm on a mission now
I'm on a mission now

[Bridge]
I have nothing but then, the have is not as good as the want

[Verse 3]
I'm gonna glide on the winds of your breathing
Writhe in your calm and provide your release
Wade into your warning you're needing
And reside in the heart of your strongest beliefs
Tear all your temples down

[Chorus]
I'm on a mission now
I'm on a mission now
I'm on a mission now
I'm on a mission now

[Outro]
And I have nothing, but then the have is not as good as the want
[Verse]
Words get tangled on your tongue
And you stumble on your feet
When you miss somebody

And everywhere you think you see them
Walking down the street
When you miss somebody

[Chorus]
When you miss somebody
You tell yourself a hundred thousand times
"Nobody ever lives forever"
So you give it one more try
To wave goodbye
Wave goodbye

[Verse]
Every hurtful thing you ever said
Is ringing in your ears
When you miss somebody

And every thing of beauty that you see
It only brings a tear
When you miss somebody

[Chorus]
Oh, when you miss somebody
You tell yourself that everything will be alright
You try to stand up strong and brave
But all you want to do is lay down and die

[Bridge]
How long I've waited for an answer or a sign
Lonely and weary from this troubled task of trying
To wave goodbye

[Verse]
So now you start to recognize that every single path you see
Leads to a tear in your eye
So wave goodbye
Wave goodbye
Wave goodbye
Wave goodbye
[Verse 1]
Open your arms to the lonely shine
Lonesome as gold in the poor man's smile
See how the moon is full
Follow the push and pull
Follow the ebb and flow in the breathing tide

[Chorus]
Come on, Moonchild
You're so far away tonight
The door is falling open and we're flying wild

[Verse 2]
Cat on the road down in the living night
See how the black dog grins in the diamond light
We're dreaming and we're real
We're broken and we're healed
Give in to what you feel over what you see

[Chorus]
Come on, Moonchild
You're so far away tonight
The door is falling open and we're flying wild
Come on, moonflower
You're so far away from now
You could bloom forever in the hour

[Bridge]
And when "if" is only "yes" and "no"
It now becomes too soon
I know you'll be alright if you'd only
Come away in the moon, yeah
Come away in the moon
In the blue shine

[Chorus]
Come on, Moonchild
You're so far away tonight
The door is falling open and we're flying wild
Come on, moonflower
You're so far away from now
You could bloom forever in the hour
You could bloom forever in the hour
[Verse]
Sweet euphoria
Mine is the heart you own
You lost the grace of the hands that harmed you
In the daze of a thousand yawns
Lost my love, as it is I'm truly gone

In your morning I will sleep
Fire on an open palm
Death for Jesus and plastic armies
Wouldn't bring me back again
Sweet as ether eyes I'm blind to them

[Chorus]
And in your aching hour
Time wilts like flowers
Sleeping on land-mine pillows
Tired angels
Save my love for the lasting one

[Verse 2]
Sweet euphoria
Mine is heart you stole
Touched and broken are the things you love
Using stars to light your candles
Warms my face but I can't remember yours

[Chorus]
Gone are your dandelions
Falling like mine
Falling like daydream mangos
Diving swallows
Save my love, save my love
Save my love for the lasting one
Sweet Euphoria
[Verse 1]
What have you done, my little spark?
Cursing my name 'cause again I put you out
Falling apart, you tell yourself you are
Dreaming only of the ones who never dream of you
Never dream of you

[Chorus]
But I'm your disappearing one
I vanish when the curtain's drawn
But I will come again and you will let me in
And you'll see I never disappear for long

[Verse 2]
Into your room I stumble now
Too tired to cower and it's too late to draw you out
And there you lie like a painting of Christ
Bleeding on the heads of the ones who nailed you down
The ones who nailed you down

[Chorus]
But I'm your disappearing one
I vanish when the curtain's drawn
But I will come again and you will let me in
And you'll see I never disappear for long

[Chorus]
Yeah, I'm your disappearing one
I vanish when the curtain's drawn
But I will come again and you will let me in
And you'll see I never disappear for long
And you'll see I never disappear for long, no
[Verse 1]
The embers of the saint inside of you
Are growing as I'm bathing in your glow
I'm swallowing the poison of your flower
And hanging on the rising of my low

[Pre-Chorus]
Colorful and falling from your mouth
Like a painted fever in recoil
Like a lie without the pain

[Chorus]
On a pillow of your bones
I will lay across the stones
Of your shore until the tide comes crawling
Throw my pillow on the fire
Make my bed under the eye
Of your moon until the tide comes crawling back

[Verse 2]
A waning hand on silver granite ways
Will mend my broken limbs and bend my haze
I'm sleeping in the silence of your voice
I'm cradling the peril of my only choice

[Pre-Chorus]
Colorful and falling from your mouth
Like a painted fever in recoil
Like a lie without the pain

[Chorus]
On a pillow of your bones
I will lay across the stones
Of your shore until the tide comes crawling
Throw my pillow on the fire
Make my bed under the eye
Of your moon until the tide comes crawling back

[Bridge]
Even though the truth can burn inside or fall behind
I will wander through your open mind
And you will find no lie can hide
Until the tide comes crawling

[Outro]
On a pillow of your bones
I will lay across the stones
Of your shore until the tide comes crawling
Throw my pillow on the fire
Make my bed under the eye
Of your moon until the tide comes crawling
On a pillow of your bones
I will lay across the stones
Of your shore until the tide comes crawling back
[Verse 1]
And so we start another day together
You and I and the million miles between us
I train my moods to bloom like flowers unfolding
Instead of fluttering around and slowly drowning

[Chorus]
In the steel rain
Steel rain, steel rain
It's taking over
It's taking over

[Verse 2]
The sky is open and the drones are pouring out
The day inhales in a contagious yawn
And there you smile as though the sun were bouncing

[Chorus]
In the steel rain
Steel rain, steel rain
It's taking over
Steel rain
Steel rain, steel rain
It's taking over
It's taking over

[Guitar Solo]

[Bridge]
Here in the little world
The tiny world spins for me
All's well in the tilted world
But there's something falling down

[Chorus]
In the steel rain
Steel rain, steel rain
It's taking over
Steel rain
Steel rain, steel rain
It's taking over
It's taking over

[Outro]
It's taking over
It's taking over
It's taking over
It's taking over
It's taking over
[Verse]
Dark as roses and fine as sand
Feel your healing and your sting again
I hear you laughing and my soul is saved
On forgotten graves you cry

[Verse]
Crawl like ivy up my spine
Through my nerves and into my eyes
Cuts like anguish or recollections
Of better days gone by

[Chorus]
But it's all right when you're all in pain
And you feel the rain come down
It's alright when you find your way
Then you see it disappear
It's alright, though your garden's grey
I know all your graces someday will flower
In the sweet sunshower
In the sweet sunshower

[Verse]
Eyes like oceans so far away
A feather trail to a better way
Worried mornings turn into days
Then into worried nights

[Chorus]
But it's all right when you're all in pain
And you feel the rain come down
It's alright when you find your way
Then you see it disappear
It's alright, though your garden's grey
I know all your graces someday will flower
In the sweet sunshower
In the sweet sunshower

[Outro]
Oh in the sweet sunshower
In the sweet sweet sweet sunshower
I know all your graces someday will flower
In the sweet sweet sunshower
It's all right
All you'll be you are today, are today
It's all right
All you'll be you are today, are today
Are today
Are today
Are today
Are today

In [ ]:
# d['_type']
# d['release_date_components']
#^just needs to be once per album

# d['tracks'][0]['song']['title']
# d['tracks'][0]['song']['artist']
# d['tracks'[0]['song']['lyrics']

In [168]:
# Source - https://stackoverflow.com/a/24888331
# Posted by fred, modified by community. See post 'Timeline' for change history
# Retrieved 2026-07-05, License - CC BY-SA 4.0

import pandas as pd

euphoria_mourning_df = pd.DataFrame(columns=['track_title', 'track_lyrics', 'album_name', 'project_name', 'release_year', 'label'])

In [169]:
track_title = []

for track in euphoria_mourning["tracks"]:
    track_title.append(track['song']['title'])

#https://www.askpython.com/python-modules/pandas/appending-dataframes-with-for-loops

In [170]:
track_title

['Can’t Change Me',
 'Flutter Girl',
 'Preaching the End of the World',
 'Follow My Way',
 'When I’m Down',
 'Mission',
 'Wave Goodbye',
 'Moonchild',
 'Sweet Euphoria',
 'Disappearing One',
 'Pillow of Your Bones',
 'Steel Rain',
 'Sunshower']

In [171]:
euphoria_mourning_df['track_title'] = track_title

In [172]:
euphoria_mourning_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Can’t Change Me,NaN,NaN,NaN,NaN,NaN
1,Flutter Girl,NaN,NaN,NaN,NaN,NaN
2,Preaching the End of the World,NaN,NaN,NaN,NaN,NaN
3,Follow My Way,NaN,NaN,NaN,NaN,NaN
4,When I’m Down,NaN,NaN,NaN,NaN,NaN
5,Mission,NaN,NaN,NaN,NaN,NaN
6,Wave Goodbye,NaN,NaN,NaN,NaN,NaN
7,Moonchild,NaN,NaN,NaN,NaN,NaN
8,Sweet Euphoria,NaN,NaN,NaN,NaN,NaN
9,Disappearing One,NaN,NaN,NaN,NaN,NaN
10,Pillow of Your Bones,NaN,NaN,NaN,NaN,NaN
11,Steel Rain,NaN,NaN,NaN,NaN,NaN
12,Sunshower,NaN,NaN,NaN,NaN,NaN

In [173]:
track_lyrics = []

for lyric in euphoria_mourning["tracks"]:
    track_lyrics.append(lyric['song']['lyrics'])

In [174]:
track_lyrics

["[Verse 1]\nShe can do anything at all\nHave anything she pleases\nThe power to change what she thinks is wrong\nBut what could she want with me? Yeah\n\n[Pre-Chorus]\nBut wait just one minute here\nI can see that she's trying to read me\n(Suddenly I know)\n\n[Chorus]\nShe's going to change the world\nShe's going to change the world\nShe's going to change the world\nBut she can't change me\nNo, she can't change me\n\n[Verse 2]\nShe has the daylight at her command\nShe gives the night its dreams, yeah\nShe can uncover your darkest fear\nAnd make you forget you feel it\n\n[Pre-Chorus]\nBut wait just one minute more\nI can see that she's trying to free me\n(Suddenly I know)\n\n[Chorus]\nShe's going to change the world (Going to change the world)\nShe's going to change the world (Going to change the world)\nShe's going to change the world (Going to change)\nBut she can't change me\nNo, she can't change me\n\n[Bridge]\nAnd suddenly I can see everything that's wrong with me, yeah\nBut what can I do? I'm the only thing I really have at all\n\n[Instrumental Break]\n\n[Pre-Chorus]\nBut wait, just, one minute here\nI can see that she's trying to need me\n(Suddenly I know)\n\n[Chorus]\nShe's going to change the world (Going to change the world)\nShe's going to change the world (Going to change the world)\nShe's going to change the world (Going to change)\nBut she can't change me\nNo, she can't change me",
 "[Verse 1]\nI'm drinking dust with eyes of rust\nTonight my tears might stain your wings\nSo flutter home because you're better off alone than with me\n\n[Verse 2]\nSo hide your face and tie your lace\nAnd butterflies across your cheek\nForget how soon you become a fool for words when I speak\n\n[Chorus]\nFlutter girl\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\n\n[Verse 3]\nMy hands are rough, my fingers cold\nAnd your heart's so young and so naive\nTo ever feel for a moment that I might dare to believe\n\n[Chorus]\nFlutter girl\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\n\n[Bridge]\nI'll tear your wings\nAs I melt in your smile\nAs I run all your colors away\n\n[Chorus]\nFlutter girl\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\n\n[Outro]\nFlutter girl",
 '[Verse 1]\nHello, I know there\'s someone out there\nWho can understand and who\'s feeling the same way as me\nI\'m 24 and I\'ve got everything to live for\nBut I know now that it wasn\'t meant to be\n\n[Verse]\n\'Cause all has been lost and all has been won\nAnd there\'s nothing left for us to save\nBut now I know that I don\'t wanna be alone today\nSo if you\'re finding you\'ve been feeling just the same\n\n[Chorus]\nCall me now, it\'s alright\nIt\'s just the end of the world\nYou\'ll need a friend in the world\n\'Cause you can\'t hide\nSo call and I\'ll get right back\nIf your intentions are pure\nI\'m seeking a friend for the end of the world\n\n[Verse]\nI\'ve got a photograph, I\'ll send it off today\nYou will see that I am perfectly sane\nNot for a lifetime or "forever and a day"\n\'Cause we know now that just won\'t be the case\n\n[Chorus]\nSo call me now, it\'s alright\nIt\'s just the end of the world\nYou\'ll need a friend in the world\n\'Cause you can\'t hide\nSo call and I\'ll get right back\nIf your intentions are pure\nI\'m seeking a friend for the end of the world\n\n[Bridge]\nWith no commitment and no confessions\nAnd no little secrets to keep\nNo little children or houses with roses\nJust the end of the world and me\n\n[Verse]\n\'Cause all has been gone and all has been done\nAnd there\'s nothing left for us to save\nBut we could be together as they blow it all away\nAnd we could share in every moment as it breaks\n\n[Chorus]\nSo call me now, it\'s alright\nIt\'s just the end of the world\nYou\'ll need a friend in the world\n\'Cause you can\'t hide\nSo call and I\'ll get right back\nIf your intentions are pure\nI\'m seeking a friend for the end of the world\n\n[Chorus]\nSo call me now, it\'s alright\nIt\'s just the end of the world\nYou\'ll need a friend in the world\n\'Cause you can\'t hide\nSo call and I\'ll get right back\nIf your intentions are pure\nI\'m seeking a friend for the end of the world',
 "[Verse 1]\nLittle one, don't be a fool\nI'm a wreck when I look mighty\nIn euphoria, I'm bruised\nIn confusion, next I'm lightning\nIn complacence, I am small\nThrough oblivion I'm charged\n\n[Chorus]\nFollow my way when I'm not leading anyone\nOpen and frayed when you can see that I'm unsure\nOut on my way, I'm only pure when I get lost\nAnd you're only needing when you're finding that I'm not\n\n[Verse 2]\nYou're just looking for a boy\nBathed in infrared and sunlight\nI'm all polish and reward\nWhen I'm confident, I'm hopeless\nJust like everybody else\nRight before they fall apart\n\n[Chorus]\nSo follow my way when I am falling from your heart\nWhen I'm the pain, fever, and sweet relief in one\nOut on my way, though I'm not worthy of your trust\nFollow me down into a swan dive, all eyes closed tight\n\n[Bridge]\nLowly, slowly, now I know\nI love where you go when you're gone\nWarm your hands inside my veins\nI might be contagious\nThrough oblivion, I charge\n\n[Chorus]\nSo follow my way when I am useless to your cause\nWhen I derail, calm in the patience of remorse\nOut on my way, out on my empty open nerves\nWhen all you know is that I don't know where we are\nWhen all you know is that I don't know\nFollow my way",
 "[Verse 1]\nWhat say you now\nThe door is opening on your vigil\nNow I'm in my usual way\nI save my breath, knowing what you're\nYou're wanting me to say\nI only love you when I'm down\n\n[Verse 2]\nYou say that midnight opens its arms to me\nLeaving you alone, then I fly so far away\nUntil the light blurs my vision and I have nowhere to roam\nI only love you when I'm down\nOoo\n\n[Chorus]\nAnd I only love you when I'm down\nAnd I'm only near you when I'm gone\nBut one thing for you to keep in mind, you know\nThat I'm down all the time, all the time\n\n[Verse 3]\nWell, I know you're reaching out and you\nYou need to feel my hand\nYou want to be understood\nYeah, well, I understand\nI know you hold precious little hope for me\nAnd in your happiness, I'm always drowning in my grief\n\n[Chorus]\nAnd I only love you when I'm down, oh-oh\nAnd I'm only near you when I'm gone\nBut one thing for you to keep in mind, you know\nThat I'm down all the time, all the time\n\n[Outro]\nAll the time\nAll the time",
 "[Verse 1]\nPulled through you and drowning in your swirl\nCircling, unfolding in your will\nI'm gonna glide on the winds of your breathing\nAnd alight on your guarded heart\nI'm going to tear all your temples down\n\n[Chorus]\nI'm on a mission now\nI'm on a mission now\n\n[Verse 2]\nSmoldering down inside your mood\nSlithering and fanning in your eyes\nI'm gonna dive through your crying and sleep in your hair\nRise from your ashes and kneel in your prayers\nTear all your temples down\n\n[Chorus]\nI'm on a mission now\nI'm on a mission now\nI'm on a mission now\nI'm on a mission now\n\n[Bridge]\nI have nothing but then, the have is not as good as the want\n\n[Verse 3]\nI'm gonna glide on the winds of your breathing\nWrithe in your calm and provide your release\nWade into your warning you're needing\nAnd reside in the heart of your strongest beliefs\nTear all your temples down\n\n[Chorus]\nI'm on a mission now\nI'm on a mission now\nI'm on a mission now\nI'm on a mission now\n\n[Outro]\nAnd I have nothing, but then the have is not as good as the want",
 '[Verse]\nWords get tangled on your tongue\nAnd you stumble on your feet\nWhen you miss somebody\n\nAnd everywhere you think you see them\nWalking down the street\nWhen you miss somebody\n\n[Chorus]\nWhen you miss somebody\nYou tell yourself a hundred thousand times\n"Nobody ever lives forever"\nSo you give it one more try\nTo wave goodbye\nWave goodbye\n\n[Verse]\nEvery hurtful thing you ever said\nIs ringing in your ears\nWhen you miss somebody\n\nAnd every thing of beauty that you see\nIt only brings a tear\nWhen you miss somebody\n\n[Chorus]\nOh, when you miss somebody\nYou tell yourself that everything will be alright\nYou try to stand up strong and brave\nBut all you want to do is lay down and die\n\n[Bridge]\nHow long I\'ve waited for an answer or a sign\nLonely and weary from this troubled task of trying\nTo wave goodbye\n\n[Verse]\nSo now you start to recognize that every single path you see\nLeads to a tear in your eye\nSo wave goodbye\nWave goodbye\nWave goodbye\nWave goodbye',
 '[Verse 1]\nOpen your arms to the lonely shine\nLonesome as gold in the poor man\'s smile\nSee how the moon is full\nFollow the push and pull\nFollow the ebb and flow in the breathing tide\n\n[Chorus]\nCome on, Moonchild\nYou\'re so far away tonight\nThe door is falling open and we\'re flying wild\n\n[Verse 2]\nCat on the road down in the living night\nSee how the black dog grins in the diamond light\nWe\'re dreaming and we\'re real\nWe\'re broken and we\'re healed\nGive in to what you feel over what you see\n\n[Chorus]\nCome on, Moonchild\nYou\'re so far away tonight\nThe door is falling open and we\'re flying wild\nCome on, moonflower\nYou\'re so far away from now\nYou could bloom forever in the hour\n\n[Bridge]\nAnd when "if" is only "yes" and "no"\nIt now becomes too soon\nI know you\'ll be alright if you\'d only\nCome away in the moon, yeah\nCome away in the moon\nIn the blue shine\n\n[Chorus]\nCome on, Moonchild\nYou\'re so far away tonight\nThe door is falling open and we\'re flying wild\nCome on, moonflower\nYou\'re so far away from now\nYou could bloom forever in the hour\nYou could bloom forever in the hour',
 "[Verse]\nSweet euphoria\nMine is the heart you own\nYou lost the grace of the hands that harmed you\nIn the daze of a thousand yawns\nLost my love, as it is I'm truly gone\n\nIn your morning I will sleep\nFire on an open palm\nDeath for Jesus and plastic armies\nWouldn't bring me back again\nSweet as ether eyes I'm blind to them\n\n[Chorus]\nAnd in your aching hour\nTime wilts like flowers\nSleeping on land-mine pillows\nTired angels\nSave my love for the lasting one\n\n[Verse 2]\nSweet euphoria\nMine is heart you stole\nTouched and broken are the things you love\nUsing stars to light your candles\nWarms my face but I can't remember yours\n\n[Chorus]\nGone are your dandelions\nFalling like mine\nFalling like daydream mangos\nDiving swallows\nSave my love, save my love\nSave my love for the lasting one\nSweet Euphoria",
 "[Verse 1]\nWhat have you done, my little spark?\nCursing my name 'cause again I put you out\nFalling apart, you tell yourself you are\nDreaming only of the ones who never dream of you\nNever dream of you\n\n[Chorus]\nBut I'm your disappearing one\nI vanish when the curtain's drawn\nBut I will come again and you will let me in\nAnd you'll see I never disappear for long\n\n[Verse 2]\nInto your room I stumble now\nToo tired to cower and it's too late to draw you out\nAnd there you lie like a painting of Christ\nBleeding on the heads of the ones who nailed you down\nThe ones who nailed you down\n\n[Chorus]\nBut I'm your disappearing one\nI vanish when the curtain's drawn\nBut I will come again and you will let me in\nAnd you'll see I never disappear for long\n\n[Chorus]\nYeah, I'm your disappearing one\nI vanish when the curtain's drawn\nBut I will come again and you will let me in\nAnd you'll see I never disappear for long\nAnd you'll see I never disappear for long, no",
 "[Verse 1]\nThe embers of the saint inside of you\nAre growing as I'm bathing in your glow\nI'm swallowing the poison of your flower\nAnd hanging on the rising of my low\n\n[Pre-Chorus]\nColorful and falling from your mouth\nLike a painted fever in recoil\nLike a lie without the pain\n\n[Chorus]\nOn a pillow of your bones\nI will lay across the stones\nOf your shore until the tide comes crawling\nThrow my pillow on the fire\nMake my bed under the eye\nOf your moon until the tide comes crawling back\n\n[Verse 2]\nA waning hand on silver granite ways\nWill mend my broken limbs and bend my haze\nI'm sleeping in the silence of your voice\nI'm cradling the peril of my only choice\n\n[Pre-Chorus]\nColorful and falling from your mouth\nLike a painted fever in recoil\nLike a lie without the pain\n\n[Chorus]\nOn a pillow of your bones\nI will lay across the stones\nOf your shore until the tide comes crawling\nThrow my pillow on the fire\nMake my bed under the eye\nOf your moon until the tide comes crawling back\n\n[Bridge]\nEven though the truth can burn inside or fall behind\nI will wander through your open mind\nAnd you will find no lie can hide\nUntil the tide comes crawling\n\n[Outro]\nOn a pillow of your bones\nI will lay across the stones\nOf your shore until the tide comes crawling\nThrow my pillow on the fire\nMake my bed under the eye\nOf your moon until the tide comes crawling\nOn a pillow of your bones\nI will lay across the stones\nOf your shore until the tide comes crawling back",
 "[Verse 1]\nAnd so we start another day together\nYou and I and the million miles between us\nI train my moods to bloom like flowers unfolding\nInstead of fluttering around and slowly drowning\n\n[Chorus]\nIn the steel rain\nSteel rain, steel rain\nIt's taking over\nIt's taking over\n\n[Verse 2]\nThe sky is open and the drones are pouring out\nThe day inhales in a contagious yawn\nAnd there you smile as though the sun were bouncing\n\n[Chorus]\nIn the steel rain\nSteel rain, steel rain\nIt's taking over\nSteel rain\nSteel rain, steel rain\nIt's taking over\nIt's taking over\n\n[Guitar Solo]\n\n[Bridge]\nHere in the little world\nThe tiny world spins for me\nAll's well in the tilted world\nBut there's something falling down\n\n[Chorus]\nIn the steel rain\nSteel rain, steel rain\nIt's taking over\nSteel rain\nSteel rain, steel rain\nIt's taking over\nIt's taking over\n\n[Outro]\nIt's taking over\nIt's taking over\nIt's taking over\nIt's taking over\nIt's taking over",
 "[Verse]\nDark as roses and fine as sand\nFeel your healing and your sting again\nI hear you laughing and my soul is saved\nOn forgotten graves you cry\n\n[Verse]\nCrawl like ivy up my spine\nThrough my nerves and into my eyes\nCuts like anguish or recollections\nOf better days gone by\n\n[Chorus]\nBut it's all right when you're all in pain\nAnd you feel the rain come down\nIt's alright when you find your way\nThen you see it disappear\nIt's alright, though your garden's grey\nI know all your graces someday will flower\nIn the sweet sunshower\nIn the sweet sunshower\n\n[Verse]\nEyes like oceans so far away\nA feather trail to a better way\nWorried mornings turn into days\nThen into worried nights\n\n[Chorus]\nBut it's all right when you're all in pain\nAnd you feel the rain come down\nIt's alright when you find your way\nThen you see it disappear\nIt's alright, though your garden's grey\nI know all your graces someday will flower\nIn the sweet sunshower\nIn the sweet sunshower\n\n[Outro]\nOh in the sweet sunshower\nIn the sweet sweet sweet sunshower\nI know all your graces someday will flower\nIn the sweet sweet sunshower\nIt's all right\nAll you'll be you are today, are today\nIt's all right\nAll you'll be you are today, are today\nAre today\nAre today\nAre today\nAre today"]

In [175]:
euphoria_mourning_df['track_lyrics'] = track_lyrics

In [176]:
euphoria_mourning_df['album_name']= euphoria_mourning['name']

In [177]:
euphoria_mourning_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Can’t Change Me,[Verse 1]\nShe can do anything at all\nHave an...,Euphoria Mourning,NaN,NaN,NaN
1,Flutter Girl,[Verse 1]\nI'm drinking dust with eyes of rust...,Euphoria Mourning,NaN,NaN,NaN
2,Preaching the End of the World,"[Verse 1]\nHello, I know there's someone out t...",Euphoria Mourning,NaN,NaN,NaN
3,Follow My Way,"[Verse 1]\nLittle one, don't be a fool\nI'm a ...",Euphoria Mourning,NaN,NaN,NaN
4,When I’m Down,[Verse 1]\nWhat say you now\nThe door is openi...,Euphoria Mourning,NaN,NaN,NaN
5,Mission,[Verse 1]\nPulled through you and drowning in ...,Euphoria Mourning,NaN,NaN,NaN
6,Wave Goodbye,[Verse]\nWords get tangled on your tongue\nAnd...,Euphoria Mourning,NaN,NaN,NaN
7,Moonchild,[Verse 1]\nOpen your arms to the lonely shine\...,Euphoria Mourning,NaN,NaN,NaN
8,Sweet Euphoria,[Verse]\nSweet euphoria\nMine is the heart you...,Euphoria Mourning,NaN,NaN,NaN
9,Disappearing One,"[Verse 1]\nWhat have you done, my little spark...",Euphoria Mourning,NaN,NaN,NaN
10,Pillow of Your Bones,[Verse 1]\nThe embers of the saint inside of y...,Euphoria Mourning,NaN,NaN,NaN
11,Steel Rain,[Verse 1]\nAnd so we start another day togethe...,Euphoria Mourning,NaN,NaN,NaN
12,Sunshower,[Verse]\nDark as roses and fine as sand\nFeel ...,Euphoria Mourning,NaN,NaN,NaN

In [349]:
euphoria_mourning_df['release_year']= euphoria_mourning['release_date_components']['year']

In [352]:
#Record label 

euphoria_mourning_df['label']=euphoria_mourning['song_performances'][14]['artists'][0]['name']

In [353]:
euphoria_mourning_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Can’t Change Me,[Verse 1]\nShe can do anything at all\nHave an...,Euphoria Mourning,Chris Cornell,1999,A&M Records
1,Flutter Girl,[Verse 1]\nI'm drinking dust with eyes of rust...,Euphoria Mourning,Chris Cornell,1999,A&M Records
2,Preaching the End of the World,"[Verse 1]\nHello, I know there's someone out t...",Euphoria Mourning,Chris Cornell,1999,A&M Records
3,Follow My Way,"[Verse 1]\nLittle one, don't be a fool\nI'm a ...",Euphoria Mourning,Chris Cornell,1999,A&M Records
4,When I’m Down,[Verse 1]\nWhat say you now\nThe door is openi...,Euphoria Mourning,Chris Cornell,1999,A&M Records
5,Mission,[Verse 1]\nPulled through you and drowning in ...,Euphoria Mourning,Chris Cornell,1999,A&M Records
6,Wave Goodbye,[Verse]\nWords get tangled on your tongue\nAnd...,Euphoria Mourning,Chris Cornell,1999,A&M Records
7,Moonchild,[Verse 1]\nOpen your arms to the lonely shine\...,Euphoria Mourning,Chris Cornell,1999,A&M Records
8,Sweet Euphoria,[Verse]\nSweet euphoria\nMine is the heart you...,Euphoria Mourning,Chris Cornell,1999,A&M Records
9,Disappearing One,"[Verse 1]\nWhat have you done, my little spark...",Euphoria Mourning,Chris Cornell,1999,A&M Records
10,Pillow of Your Bones,[Verse 1]\nThe embers of the saint inside of y...,Euphoria Mourning,Chris Cornell,1999,A&M Records
11,Steel Rain,[Verse 1]\nAnd so we start another day togethe...,Euphoria Mourning,Chris Cornell,1999,A&M Records
12,Sunshower,[Verse]\nDark as roses and fine as sand\nFeel ...,Euphoria Mourning,Chris Cornell,1999,A&M Records

In [354]:
euphoria_mourning_df['project_name']=euphoria_mourning['primary_artist_names']

In [355]:
euphoria_mourning_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Can’t Change Me,[Verse 1]\nShe can do anything at all\nHave an...,Euphoria Mourning,Chris Cornell,1999,A&M Records
1,Flutter Girl,[Verse 1]\nI'm drinking dust with eyes of rust...,Euphoria Mourning,Chris Cornell,1999,A&M Records
2,Preaching the End of the World,"[Verse 1]\nHello, I know there's someone out t...",Euphoria Mourning,Chris Cornell,1999,A&M Records
3,Follow My Way,"[Verse 1]\nLittle one, don't be a fool\nI'm a ...",Euphoria Mourning,Chris Cornell,1999,A&M Records
4,When I’m Down,[Verse 1]\nWhat say you now\nThe door is openi...,Euphoria Mourning,Chris Cornell,1999,A&M Records
5,Mission,[Verse 1]\nPulled through you and drowning in ...,Euphoria Mourning,Chris Cornell,1999,A&M Records
6,Wave Goodbye,[Verse]\nWords get tangled on your tongue\nAnd...,Euphoria Mourning,Chris Cornell,1999,A&M Records
7,Moonchild,[Verse 1]\nOpen your arms to the lonely shine\...,Euphoria Mourning,Chris Cornell,1999,A&M Records
8,Sweet Euphoria,[Verse]\nSweet euphoria\nMine is the heart you...,Euphoria Mourning,Chris Cornell,1999,A&M Records
9,Disappearing One,"[Verse 1]\nWhat have you done, my little spark...",Euphoria Mourning,Chris Cornell,1999,A&M Records
10,Pillow of Your Bones,[Verse 1]\nThe embers of the saint inside of y...,Euphoria Mourning,Chris Cornell,1999,A&M Records
11,Steel Rain,[Verse 1]\nAnd so we start another day togethe...,Euphoria Mourning,Chris Cornell,1999,A&M Records
12,Sunshower,[Verse]\nDark as roses and fine as sand\nFeel ...,Euphoria Mourning,Chris Cornell,1999,A&M Records

In [ ]:
#too much work right now for all albums across entire solo and band career 
#so do earliest and latest solo album from when he was alive 
#earliest and latest soundgarden
#earliest and latest audioslave

In [182]:
album = genius.search_album("Higher Truth", "Chris Cornell")
album.save_lyrics()

INFO lyricsgenius.genius: Searching for "Higher Truth" by Chris Cornell...
DEBUG urllib3.connectionpool: Starting new HTTPS connection (4): genius.com:443
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/search/multi?q=Higher+Truth+Chris+Cornell HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/albums/129290?text_format=plain HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/albums/129290/tracks?per_page=50&page=1&text_format=plain HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-nearly-forgot-my-broken-heart-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-dead-wishes-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-worried-moon-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-before-we-disappear-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-through-the-window-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-josephine-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-murderer-of-blue-skies-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-higher-truth-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-let-your-eyes-wander-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-only-these-words-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-circling-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-our-time-in-the-universe-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-bend-in-the-road-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-wrong-side-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-misery-chain-bonus-track-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Chris-cornell-our-time-in-the-universe-remix-lyrics HTTP/2.0" 200 None

saved_album_lyrics_chris_cornell_higher_truth.json already exists. Overwrite?
(y/n):  n

DEBUG lyricsgenius.types.base: Skipping file save.

In [190]:
import json

with open('saved_album_lyrics_chris_cornell_higher_truth.json') as higher_truth:
    higher_truth = json.load(higher_truth)

higher_truth

{'_type': 'album',
 'api_path': '/albums/129290',
 'cover_art_thumbnail_url': 'https://images.genius.com/414e1b9c9ffd0b8bbd5eebd801535477.300x300x1.jpg',
 'cover_art_url': 'https://images.genius.com/414e1b9c9ffd0b8bbd5eebd801535477.1000x1000x1.jpg',
 'full_title': 'Higher Truth by Chris Cornell',
 'id': 129290,
 'name': 'Higher Truth',
 'name_with_artist': 'Higher Truth (artist: Chris Cornell)',
 'primary_artist_names': 'Chris Cornell',
 'pusher_channel': 'album-129290',
 'release_date_components': {'year': 2015, 'month': None, 'day': None},
 'release_date_for_display': '2015',
 'updated_at': 1739842464,
 'url': 'https://genius.com/albums/Chris-cornell/Higher-truth',
 'current_user_metadata': {'permissions': ['create_comment'],
  'excluded_permissions': ['set_album_color_gradient',
   'edit',
   'destroy',
   'pyong',
   'lock',
   'super_lock',
   'unlock',
   'sort_songs',
   'hide',
   'unhide',
   'see_short_id',
   'create_additional_role',
   'create_question'],
  'interactions': {'pyong': False, 'following': False},
  'iq_by_action': {}},
 'artist': 'Chris Cornell',
 'primary_artists': [{'_type': 'artist',
   'api_path': '/artists/18435',
   'header_image_url': 'https://images.genius.com/b6a79ad3d1aa69a9dfb83168a82022f7.473x281x1.png',
   'id': 18435,
   'image_url': 'https://images.genius.com/13f0e2fe12d710928b62ec5a98778cc3.1000x1000x1.jpg',
   'index_character': 'c',
   'is_meme_verified': False,
   'is_verified': False,
   'links_config': None,
   'name': 'Chris Cornell',
   'slug': 'Chris-cornell',
   'url': 'https://genius.com/artists/Chris-cornell'}],
 'album_type': 'album',
 'comment_count': 1,
 'custom_header_image_url': 'https://images.genius.com/1189d8eece624910237402db0b8e7a12.470x294x1.png',
 'description_preview': '',
 'header_image_url': 'https://images.genius.com/1189d8eece624910237402db0b8e7a12.470x294x1.png',
 'hidden': False,
 'language': None,
 'lock_state': 'editable',
 'pyongs_count': 0,
 'release_date': '2015-01-01',
 'tracking_paths': {'aggregate': '/albums/Chris-cornell/Higher-truth',
  'concurrent': '/albums/Chris-cornell/Higher-truth'},
 'viewable_by_roles': [],
 'album_art_primary_color': '#cc1b1e',
 'album_art_secondary_color': '#841c24',
 'album_art_text_color': '#fff',
 'song_pageviews': 193616,
 'album_relationships': [{'_type': 'album_relationship',
   'relationship_type': 'deluxe_edition_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_deluxe_edition',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'alternate_version_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_alternate_version',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'reissue_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_reissue',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'remix_version_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_remix_version',
   'albums': []}],
 'cover_arts': [{'_type': 'cover_art',
   'annotated': False,
   'api_path': '/albums/129290',
   'id': 33722,
   'image_url': 'https://images.genius.com/414e1b9c9ffd0b8bbd5eebd801535477.1000x1000x1.jpg',
   'thumbnail_image_url': 'https://images.genius.com/414e1b9c9ffd0b8bbd5eebd801535477.300x300x1.jpg',
   'url': 'https://genius.com/album_cover_arts/33722',
   'current_user_metadata': {'permissions': [],
    'excluded_permissions': ['destroy']},
   'description_annotation': {'_type': 'referent',
    'annotator_id': 2937273,
    'annotator_login': 'geniusbot',
    'api_path': '/referents/12014068',
    'classification': 'needs_exegesis',
    'fragment': 'https://images.genius.com/414e1b9c9ffd0b8bbd5eebd801535477.1000x1000x1.jpg',
    'id': 12014068,
    'ios_app_url': 'genius://referents/12014068',
    'is_description': True,
    'is_image': True,
    'path': '/12014068/Higher-truth/Https-imagesgeniuscom-414e1b9c9ffd0b8bbd5eebd8015354771000x1000x1jpg',
    'range': {'content': 'https://images.genius.com/414e1b9c9ffd0b8bbd5eebd801535477.1000x1000x1.jpg'},
    'song_id': None,
    'url': 'https://genius.com/12014068/Higher-truth/Https-imagesgeniuscom-414e1b9c9ffd0b8bbd5eebd8015354771000x1000x1jpg',
    'verified_annotator_ids': [],
    'current_user_metadata': {'permissions': [],
     'excluded_permissions': ['add_pinned_annotation_to',
      'add_community_annotation_to'],
     'relationships': {}},
    'tracking_paths': {'aggregate': '/12014068/Higher-truth/Https-imagesgeniuscom-414e1b9c9ffd0b8bbd5eebd8015354771000x1000x1jpg',
     'concurrent': '/albums/Chris-cornell/Higher-truth'},
    'twitter_share_message': '“?” —@Genius',
    'annotatable': {'_type': 'cover_art',
     'api_path': '/albums/129290',
     'context': 'Chris Cornell',
     'id': 33722,
     'image_url': 'https://images.genius.com/414e1b9c9ffd0b8bbd5eebd801535477.300x300x1.jpg',
     'link_title': 'Higher Truth',
     'title': 'Higher Truth',
     'type': 'CoverArt',
     'url': 'https://genius.com/album_cover_arts/33722'},
    'annotations': [{'_type': 'annotation',
      'api_path': '/annotations/12014068',
      'being_created': False,
      'body': {'plain': ''},
      'comment_count': 0,
      'community': True,
      'created_at': 1496877978,
      'custom_preview': None,
      'deleted': False,
      'embed_content': "<blockquote class='rg_standalone_container' data-src='//genius.com/annotations/12014068/standalone_embed'><a href='https://genius.com/12014068/Higher-truth/Https-imagesgeniuscom-414e1b9c9ffd0b8bbd5eebd8015354771000x1000x1jpg'>https://images.genius.com/414e1b9c9ffd0b8bbd5eebd801535477.1000x1000x1.jpg</a><br><a href='https://genius.com/album_cover_arts/33722'>&#8213; Higher Truth</a></blockquote><script async crossorigin src='//genius.com/annotations/load_standalone_embeds.js'></script>",
      'has_voters': False,
      'id': 12014068,
      'needs_exegesis': True,
      'pinned': False,
      'proposed_edit_count': 0,
      'pyongs_count': None,
      'referent_id': 12014068,
      'share_url': 'https://genius.com/12014068',
      'source': None,
      'state': 'needs_exegesis',
      'twitter_share_message': '“?” —@Genius',
      'url': 'https://genius.com/12014068/Higher-truth/Https-imagesgeniuscom-414e1b9c9ffd0b8bbd5eebd8015354771000x1000x1jpg',
      'verified': False,
      'votes_total': 0,
      'current_user_metadata': {'permissions': [],
       'excluded_permissions': ['vote',
        'edit',
        'cosign',
        'uncosign',
        'destroy',
        'accept',
        'reject',
        'see_unreviewed',
        'clear_votes',
        'propose_edit_to',
        'pin_to_profile',
        'unpin_from_profile',
        'update_source',
        'edit_custom_preview',
        'report_as_abusive',
        'create_comment'],
       'interactions': {'cosign': False, 'pyong': False, 'vote': None},
       'iq_by_action': {}},
      'accepted_by': None,
      'authors': [{'_type': 'user_attribution',
        'attribution': 1.0,
        'pinned_role': None,
        'user': {'_type': 'user',
         'about_me_summary': 'Hi! I’m the Genius Bot, a robotic user who performs automated tasks on the site. My behavior was programmed by the tech team, and my job is to help keep the site’s data crisp and clean.\n\nIf I’ve rejected or deleted your annotation, check out this thread to learn more.\n\nIf you notice me doing anything else that seems wrong, please hit up the bugs forum!',
         'api_path': '/users/2937273',
         'avatar': {'tiny': {'url': 'https://images.genius.com/avatars/tiny/d8178e34dd5f45daf6e9cb62f8e3b996',
           'bounding_box': {'width': 16, 'height': 16}},
          'thumb': {'url': 'https://images.genius.com/avatars/thumb/d8178e34dd5f45daf6e9cb62f8e3b996',
           'bounding_box': {'width': 32, 'height': 32}},
          'small': {'url': 'https://images.genius.com/avatars/small/d8178e34dd5f45daf6e9cb62f8e3b996',
           'bounding_box': {'width': 100, 'height': 100}},
          'medium': {'url': 'https://images.genius.com/avatars/medium/d8178e34dd5f45daf6e9cb62f8e3b996',
           'bounding_box': {'width': 300, 'height': 400}}},
         'header_image_url': 'https://assets.genius.com/images/default_banner.png?1783019845',
         'human_readable_role_for_display': 'Staff',
         'id': 2937273,
         'iq': 0,
         'is_meme_verified': False,
         'is_verified': False,
         'login': 'geniusbot',
         'name': 'geniusbot',
         'role_for_display': 'staff',
         'url': 'https://genius.com/geniusbot',
         'current_user_metadata': {'permissions': [],
          'excluded_permissions': ['follow'],
          'interactions': {'following': False}}}}],
      'cosigned_by': [],
      'created_by': {'_type': 'user',
       'about_me_summary': 'Hi! I’m the Genius Bot, a robotic user who performs automated tasks on the site. My behavior was programmed by the tech team, and my job is to help keep the site’s data crisp and clean.\n\nIf I’ve rejected or deleted your annotation, check out this thread to learn more.\n\nIf you notice me doing anything else that seems wrong, please hit up the bugs forum!',
       'api_path': '/users/2937273',
       'avatar': {'tiny': {'url': 'https://images.genius.com/avatars/tiny/d8178e34dd5f45daf6e9cb62f8e3b996',
         'bounding_box': {'width': 16, 'height': 16}},
        'thumb': {'url': 'https://images.genius.com/avatars/thumb/d8178e34dd5f45daf6e9cb62f8e3b996',
         'bounding_box': {'width': 32, 'height': 32}},
        'small': {'url': 'https://images.genius.com/avatars/small/d8178e34dd5f45daf6e9cb62f8e3b996',
         'bounding_box': {'width': 100, 'height': 100}},
        'medium': {'url': 'https://images.genius.com/avatars/medium/d8178e34dd5f45daf6e9cb62f8e3b996',
         'bounding_box': {'width': 300, 'height': 400}}},
       'header_image_url': 'https://assets.genius.com/images/default_banner.png?1783019845',
       'human_readable_role_for_display': 'Staff',
       'id': 2937273,
       'iq': 0,
       'is_meme_verified': False,
       'is_verified': False,
       'login': 'geniusbot',
       'name': 'geniusbot',
       'role_for_display': 'staff',
       'url': 'https://genius.com/geniusbot',
       'current_user_metadata': {'permissions': [],
        'excluded_permissions': ['follow'],
        'interactions': {'following': False}}},
      'rejection_comment': None,
      'top_comment': None,
      'verified_by': None}]}},
  {'_type': 'cover_art',
   'annotated': False,
   'api_path': '/albums/129290',
   'id': 1135119,
   'image_url': 'https://images.genius.com/44914970814d7091f10c47191505d60a.875x875x1.jpg',
   'thumbnail_image_url': 'https://images.genius.com/44914970814d7091f10c47191505d60a.300x300x1.jpg',
   'url': 'https://genius.com/album_cover_arts/1135119',
   'current_user_metadata': {'permissions': [],
    'excluded_permissions': ['destroy']},
   'description_annotation': {'_type': 'referent',
    'annotator_id': 15914956,
    'annotator_login': 'seriousmoonage',
    'api_path': '/referents/31464787',
    'classification': 'needs_exegesis',
    'fragment': 'https://images.genius.com/44914970814d7091f10c47191505d60a.875x875x1.jpg',
    'id': 31464787,
    'ios_app_url': 'genius://referents/31464787',
    'is_description': True,
    'is_image': True,
    'path': '/31464787/Higher-truth/Https-imagesgeniuscom-44914970814d7091f10c47191505d60a875x875x1jpg',
    'range': {'content': 'https://images.genius.com/44914970814d7091f10c47191505d60a.875x875x1.jpg'},
    'song_id': None,
    'url': 'https://genius.com/31464787/Higher-truth/Https-imagesgeniuscom-44914970814d7091f10c47191505d60a875x875x1jpg',
    'verified_annotator_ids': [],
    'current_user_metadata': {'permissions': [],
     'excluded_permissions': ['add_pinned_annotation_to',
      'add_community_annotation_to'],
     'relationships': {}},
    'tracking_paths': {'aggregate': '/31464787/Higher-truth/Https-imagesgeniuscom-44914970814d7091f10c47191505d60a875x875x1jpg',
     'concurrent': '/albums/Chris-cornell/Higher-truth'},
    'twitter_share_message': '“?” —@Genius',
    'annotatable': {'_type': 'cover_art',
     'api_path': '/albums/129290',
     'context': 'Chris Cornell',
     'id': 1135119,
     'image_url': 'https://images.genius.com/44914970814d7091f10c47191505d60a.300x300x1.jpg',
     'link_title': 'Higher Truth',
     'title': 'Higher Truth',
     'type': 'CoverArt',
     'url': 'https://genius.com/album_cover_arts/1135119'},
    'annotations': [{'_type': 'annotation',
      'api_path': '/annotations/31464787',
      'being_created': False,
      'body': {'plain': ''},
      'comment_count': 0,
      'community': True,
      'created_at': 1713385996,
      'custom_preview': None,
      'deleted': False,
      'embed_content': "<blockquote class='rg_standalone_container' data-src='//genius.com/annotations/31464787/standalone_embed'><a href='https://genius.com/31464787/Higher-truth/Https-imagesgeniuscom-44914970814d7091f10c47191505d60a875x875x1jpg'>https://images.genius.com/44914970814d7091f10c47191505d60a.875x875x1.jpg</a><br><a href='https://genius.com/album_cover_arts/1135119'>&#8213; Higher Truth</a></blockquote><script async crossorigin src='//genius.com/annotations/load_standalone_embeds.js'></script>",
      'has_voters': False,
      'id': 31464787,
      'needs_exegesis': True,
      'pinned': False,
      'proposed_edit_count': 0,
      'pyongs_count': None,
      'referent_id': 31464787,
      'share_url': 'https://genius.com/31464787',
      'source': None,
      'state': 'needs_exegesis',
      'twitter_share_message': '“?” —@Genius',
      'url': 'https://genius.com/31464787/Higher-truth/Https-imagesgeniuscom-44914970814d7091f10c47191505d60a875x875x1jpg',
      'verified': False,
      'votes_total': 0,
      'current_user_metadata': {'permissions': [],
       'excluded_permissions': ['vote',
        'edit',
        'cosign',
        'uncosign',
        'destroy',
        'accept',
        'reject',
        'see_unreviewed',
        'clear_votes',
        'propose_edit_to',
        'pin_to_profile',
        'unpin_from_profile',
        'update_source',
        'edit_custom_preview',
        'report_as_abusive',
        'create_comment'],
       'interactions': {'cosign': False, 'pyong': False, 'vote': None},
       'iq_by_action': {}},
      'accepted_by': None,
      'authors': [{'_type': 'user_attribution',
        'attribution': 1.0,
        'pinned_role': None,
        'user': {'_type': 'user',
         'about_me_summary': '✧˖°. ᓚᘏᗢ ˚₊‧⁺⋆ ♱',
         'api_path': '/users/15914956',
         'avatar': {'tiny': {'url': 'https://filepicker-images.genius.com/150d13272428cd26a4dde1c18e5bd50d200d44ec0c9deed636b5785489792e4f%2F6jd39cggo5',
           'bounding_box': {'width': 16, 'height': 16}},
          'thumb': {'url': 'https://filepicker-images.genius.com/150d13272428cd26a4dde1c18e5bd50d200d44ec0c9deed636b5785489792e4f%2F6jd39cggo5',
           'bounding_box': {'width': 32, 'height': 32}},
          'small': {'url': 'https://filepicker-images.genius.com/150d13272428cd26a4dde1c18e5bd50d200d44ec0c9deed636b5785489792e4f%2F6jd39cggo5',
           'bounding_box': {'width': 100, 'height': 100}},
          'medium': {'url': 'https://filepicker-images.genius.com/150d13272428cd26a4dde1c18e5bd50d200d44ec0c9deed636b5785489792e4f%2F6jd39cggo5',
           'bounding_box': {'width': 300, 'height': 400}}},
         'header_image_url': 'https://filepicker-images.genius.com/150d13272428cd26a4dde1c18e5bd50d200d44ec0c9deed636b5785489792e4f%2Fpzfhiigflb',
         'human_readable_role_for_display': 'Contributor',
         'id': 15914956,
         'iq': 2215,
         'is_meme_verified': False,
         'is_verified': False,
         'login': 'seriousmoonage',
         'name': 'seriousmoonage',
         'role_for_display': 'contributor',
         'url': 'https://genius.com/seriousmoonage',
         'current_user_metadata': {'permissions': [],
          'excluded_permissions': ['follow'],
          'interactions': {'following': False}}}}],
      'cosigned_by': [],
      'created_by': {'_type': 'user',
       'about_me_summary': '✧˖°. ᓚᘏᗢ ˚₊‧⁺⋆ ♱',
       'api_path': '/users/15914956',
       'avatar': {'tiny': {'url': 'https://filepicker-images.genius.com/150d13272428cd26a4dde1c18e5bd50d200d44ec0c9deed636b5785489792e4f%2F6jd39cggo5',
         'bounding_box': {'width': 16, 'height': 16}},
        'thumb': {'url': 'https://filepicker-images.genius.com/150d13272428cd26a4dde1c18e5bd50d200d44ec0c9deed636b5785489792e4f%2F6jd39cggo5',
         'bounding_box': {'width': 32, 'height': 32}},
        'small': {'url': 'https://filepicker-images.genius.com/150d13272428cd26a4dde1c18e5bd50d200d44ec0c9deed636b5785489792e4f%2F6jd39cggo5',
         'bounding_box': {'width': 100, 'height': 100}},
        'medium': {'url': 'https://filepicker-images.genius.com/150d13272428cd26a4dde1c18e5bd50d200d44ec0c9deed636b5785489792e4f%2F6jd39cggo5',
         'bounding_box': {'width': 300, 'height': 400}}},
       'header_image_url': 'https://filepicker-images.genius.com/150d13272428cd26a4dde1c18e5bd50d200d44ec0c9deed636b5785489792e4f%2Fpzfhiigflb',
       'human_readable_role_for_display': 'Contributor',
       'id': 15914956,
       'iq': 2215,
       'is_meme_verified': False,
       'is_verified': False,
       'login': 'seriousmoonage',
       'name': 'seriousmoonage',
       'role_for_display': 'contributor',
       'url': 'https://genius.com/seriousmoonage',
       'current_user_metadata': {'permissions': [],
        'excluded_permissions': ['follow'],
        'interactions': {'following': False}}},
      'rejection_comment': None,
      'top_comment': None,
      'verified_by': None}]}}],
 'description_annotation': {'_type': 'referent',
  'annotator_id': 554585,
  'annotator_login': 'IThinkImAndrea',
  'api_path': '/referents/7655036',
  'classification': 'needs_exegesis',
  'fragment': 'Higher Truth',
  'id': 7655036,
  'ios_app_url': 'genius://referents/7655036',
  'is_description': True,
  'is_image': False,
  'path': '/7655036/Higher-truth/Higher-truth',
  'range': {'content': 'Higher Truth'},
  'song_id': None,
  'url': 'https://genius.com/7655036/Higher-truth/Higher-truth',
  'verified_annotator_ids': [],
  'current_user_metadata': {'permissions': [],
   'excluded_permissions': ['add_pinned_annotation_to',
    'add_community_annotation_to'],
   'relationships': {}},
  'tracking_paths': {'aggregate': '/7655036/Higher-truth/Higher-truth',
   'concurrent': '/albums/Chris-cornell/Higher-truth'},
  'twitter_share_message': '“?” —@Genius',
  'annotatable': {'_type': 'album',
   'api_path': '/albums/129290',
   'context': 'Chris Cornell',
   'id': 129290,
   'image_url': 'https://images.genius.com/414e1b9c9ffd0b8bbd5eebd801535477.300x300x1.jpg',
   'link_title': 'Higher Truth',
   'title': 'Higher Truth',
   'type': 'Album',
   'url': 'https://genius.com/albums/Chris-cornell/Higher-truth'},
  'annotations': [{'_type': 'annotation',
    'api_path': '/annotations/7655036',
    'being_created': False,
    'body': {'plain': ''},
    'comment_count': 0,
    'community': True,
    'created_at': 1439917747,
    'custom_preview': None,
    'deleted': False,
    'embed_content': "<blockquote class='rg_standalone_container' data-src='//genius.com/annotations/7655036/standalone_embed'><a href='https://genius.com/7655036/Higher-truth/Higher-truth'>Higher Truth</a><br><a href='https://genius.com/albums/Chris-cornell/Higher-truth'>&#8213; Higher Truth</a></blockquote><script async crossorigin src='//genius.com/annotations/load_standalone_embeds.js'></script>",
    'has_voters': False,
    'id': 7655036,
    'needs_exegesis': True,
    'pinned': False,
    'proposed_edit_count': 0,
    'pyongs_count': None,
    'referent_id': 7655036,
    'share_url': 'https://genius.com/7655036',
    'source': None,
    'state': 'needs_exegesis',
    'twitter_share_message': '“?” —@Genius',

In [192]:
higher_truth_df = pd.DataFrame(columns=['track_title', 'track_lyrics', 'album_name', 'project_name', 'release_year', 'label'])

In [193]:
track_title = []

for track in higher_truth["tracks"]:
    track_title.append(track['song']['title'])

In [194]:
higher_truth_df['track_title'] = track_title

In [195]:
higher_truth_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Nearly Forgot My Broken Heart,NaN,NaN,NaN,NaN,NaN
1,Dead Wishes,NaN,NaN,NaN,NaN,NaN
2,Worried Moon,NaN,NaN,NaN,NaN,NaN
3,Before We Disappear,NaN,NaN,NaN,NaN,NaN
4,Through the Window,NaN,NaN,NaN,NaN,NaN
5,Josephine,NaN,NaN,NaN,NaN,NaN
6,Murderer of Blue Skies,NaN,NaN,NaN,NaN,NaN
7,Higher Truth,NaN,NaN,NaN,NaN,NaN
8,Let Your Eyes Wander,NaN,NaN,NaN,NaN,NaN
9,Only These Words,NaN,NaN,NaN,NaN,NaN
10,Circling,NaN,NaN,NaN,NaN,NaN
11,Our Time In the Universe,NaN,NaN,NaN,NaN,NaN
12,Bend In the Road,NaN,NaN,NaN,NaN,NaN
13,Wrong Side,NaN,NaN,NaN,NaN,NaN
14,Misery Chain (Bonus Track),NaN,NaN,NaN,NaN,NaN
15,Our Time In the Universe (Remix),NaN,NaN,NaN,NaN,NaN

In [196]:
track_lyrics = []

for lyric in higher_truth["tracks"]:
    track_lyrics.append(lyric['song']['lyrics'])

In [197]:
higher_truth_df['track_lyrics'] = track_lyrics

In [198]:
higher_truth_df['album_name']= higher_truth['name']

In [199]:
higher_truth_df['release_year']= higher_truth['release_date_components']['year']

In [200]:
higher_truth_df['label']=higher_truth['song_performances'][13]['artists'][1]['name']

In [201]:
higher_truth_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Nearly Forgot My Broken Heart,[Verse 1]\nEvery time I stare into the sun\nTr...,Higher Truth,NaN,2015,Universal Music Group
1,Dead Wishes,[Verse]\nStaring in the mirror with two borrow...,Higher Truth,NaN,2015,Universal Music Group
2,Worried Moon,"Worried moon, shining bright\nCan I sleep here...",Higher Truth,NaN,2015,Universal Music Group
3,Before We Disappear,[Verse 1]\nTime ain’t nothing if it ain’t fast...,Higher Truth,NaN,2015,Universal Music Group
4,Through the Window,Clouds have gathered turned to rain\nCandle on...,Higher Truth,NaN,2015,Universal Music Group
5,Josephine,"Josephine, where can you be now?\nAgain the su...",Higher Truth,NaN,2015,Universal Music Group
6,Murderer of Blue Skies,[Verse]\nYou flew in on the wind\nWas a day th...,Higher Truth,NaN,2015,Universal Music Group
7,Higher Truth,"[Verse 1]\nYou can make somebody cry\nGo on, d...",Higher Truth,NaN,2015,Universal Music Group
8,Let Your Eyes Wander,When you find love\nAnd it gets away\nIf it co...,Higher Truth,NaN,2015,Universal Music Group
9,Only These Words,In a castle down a long road\nA little girl wa...,Higher Truth,NaN,2015,Universal Music Group
10,Circling,[Verse 1]\nNight falls while drunken angels\nS...,Higher Truth,NaN,2015,Universal Music Group
11,Our Time In the Universe,Waiting upon the dunes of earth and sand\nIn t...,Higher Truth,NaN,2015,Universal Music Group
12,Bend In the Road,[Verse 1]\nPut a bend in the road\nI’m too los...,Higher Truth,NaN,2015,Universal Music Group
13,Wrong Side,[Verse]\nWhen I was just a boy of ten\nMy fath...,Higher Truth,NaN,2015,Universal Music Group
14,Misery Chain (Bonus Track),[Verse 1]\nWon't you take one link from this m...,Higher Truth,NaN,2015,Universal Music Group
15,Our Time In the Universe (Remix),[Verse 1]\nWaiting upon the dunes of earth and...,Higher Truth,NaN,2015,Universal Music Group

In [202]:
higher_truth_df['project_name']=higher_truth['primary_artist_names']

In [203]:
higher_truth_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Nearly Forgot My Broken Heart,[Verse 1]\nEvery time I stare into the sun\nTr...,Higher Truth,Chris Cornell,2015,Universal Music Group
1,Dead Wishes,[Verse]\nStaring in the mirror with two borrow...,Higher Truth,Chris Cornell,2015,Universal Music Group
2,Worried Moon,"Worried moon, shining bright\nCan I sleep here...",Higher Truth,Chris Cornell,2015,Universal Music Group
3,Before We Disappear,[Verse 1]\nTime ain’t nothing if it ain’t fast...,Higher Truth,Chris Cornell,2015,Universal Music Group
4,Through the Window,Clouds have gathered turned to rain\nCandle on...,Higher Truth,Chris Cornell,2015,Universal Music Group
5,Josephine,"Josephine, where can you be now?\nAgain the su...",Higher Truth,Chris Cornell,2015,Universal Music Group
6,Murderer of Blue Skies,[Verse]\nYou flew in on the wind\nWas a day th...,Higher Truth,Chris Cornell,2015,Universal Music Group
7,Higher Truth,"[Verse 1]\nYou can make somebody cry\nGo on, d...",Higher Truth,Chris Cornell,2015,Universal Music Group
8,Let Your Eyes Wander,When you find love\nAnd it gets away\nIf it co...,Higher Truth,Chris Cornell,2015,Universal Music Group
9,Only These Words,In a castle down a long road\nA little girl wa...,Higher Truth,Chris Cornell,2015,Universal Music Group
10,Circling,[Verse 1]\nNight falls while drunken angels\nS...,Higher Truth,Chris Cornell,2015,Universal Music Group
11,Our Time In the Universe,Waiting upon the dunes of earth and sand\nIn t...,Higher Truth,Chris Cornell,2015,Universal Music Group
12,Bend In the Road,[Verse 1]\nPut a bend in the road\nI’m too los...,Higher Truth,Chris Cornell,2015,Universal Music Group
13,Wrong Side,[Verse]\nWhen I was just a boy of ten\nMy fath...,Higher Truth,Chris Cornell,2015,Universal Music Group
14,Misery Chain (Bonus Track),[Verse 1]\nWon't you take one link from this m...,Higher Truth,Chris Cornell,2015,Universal Music Group
15,Our Time In the Universe (Remix),[Verse 1]\nWaiting upon the dunes of earth and...,Higher Truth,Chris Cornell,2015,Universal Music Group

In [118]:
album = genius.search_album("Ultramega OK", "Soundgarden")

INFO lyricsgenius.genius: Searching for "Ultramega OK" by Soundgarden...
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/search/multi?q=Ultramega+OK+Soundgarden HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/albums/105320?text_format=plain HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/albums/105320/tracks?per_page=50&page=1&text_format=plain HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-flower-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-all-your-lies-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-665-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-beyond-the-wheel-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-667-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-mood-for-trouble-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-circle-of-power-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-he-didnt-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-smokestack-lightning-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-nazi-driver-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-head-injury-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-incessant-mace-lyrics HTTP/2.0" 200 None

In [119]:
album.save_lyrics()

DEBUG lyricsgenius.types.base: Wrote saved_album_lyrics_soundgarden_ultramega_ok.json.

In [204]:
with open('saved_album_lyrics_soundgarden_ultramega_ok.json') as ultramegaok:
    ultramegaok = json.load(ultramegaok)
ultramegaok

{'_type': 'album',
 'api_path': '/albums/105320',
 'cover_art_thumbnail_url': 'https://images.genius.com/745416d896c2bb3356cf7b00111f244d.300x300x1.png',
 'cover_art_url': 'https://images.genius.com/745416d896c2bb3356cf7b00111f244d.490x490x1.png',
 'full_title': 'Ultramega OK by Soundgarden',
 'id': 105320,
 'name': 'Ultramega OK',
 'name_with_artist': 'Ultramega OK (artist: Soundgarden)',
 'primary_artist_names': 'Soundgarden',
 'pusher_channel': 'album-105320',
 'release_date_components': {'year': 1988, 'month': 10, 'day': 31},
 'release_date_for_display': 'October 31, 1988',
 'updated_at': 1734551183,
 'url': 'https://genius.com/albums/Soundgarden/Ultramega-ok',
 'current_user_metadata': {'permissions': ['create_comment'],
  'excluded_permissions': ['set_album_color_gradient',
   'edit',
   'destroy',
   'pyong',
   'lock',
   'super_lock',
   'unlock',
   'sort_songs',
   'hide',
   'unhide',
   'see_short_id',
   'create_additional_role',
   'create_question'],
  'interactions': {'pyong': False, 'following': False},
  'iq_by_action': {}},
 'artist': 'Soundgarden',
 'primary_artists': [{'_type': 'artist',
   'api_path': '/artists/19976',
   'header_image_url': 'https://images.genius.com/6bbfe726dc5523b85c557274a3a67d51.1000x696x1.jpg',
   'id': 19976,
   'image_url': 'https://images.genius.com/f96fac2a51d57a7c0c80611c201f10c1.570x570x1.jpg',
   'index_character': 's',
   'is_meme_verified': False,
   'is_verified': False,
   'links_config': None,
   'name': 'Soundgarden',
   'slug': 'Soundgarden',
   'url': 'https://genius.com/artists/Soundgarden'}],
 'album_type': 'album',
 'comment_count': 0,
 'custom_header_image_url': None,
 'description_preview': 'Soundgarden’s debut album',
 'header_image_url': 'https://images.genius.com/745416d896c2bb3356cf7b00111f244d.490x490x1.png',
 'hidden': False,
 'language': None,
 'lock_state': 'editable',
 'pyongs_count': 0,
 'release_date': '1988-10-31',
 'tracking_paths': {'aggregate': '/albums/Soundgarden/Ultramega-ok',
  'concurrent': '/albums/Soundgarden/Ultramega-ok'},
 'viewable_by_roles': [],
 'album_art_primary_color': '#bc0808',
 'album_art_secondary_color': '#700a0b',
 'album_art_text_color': '#fff',
 'song_pageviews': 66816,
 'album_relationships': [{'_type': 'album_relationship',
   'relationship_type': 'deluxe_edition_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_deluxe_edition',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'alternate_version_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_alternate_version',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'reissue_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_reissue',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'remix_version_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_remix_version',
   'albums': []}],
 'cover_arts': [{'_type': 'cover_art',
   'annotated': False,
   'api_path': '/albums/105320',
   'id': 468029,
   'image_url': 'https://images.genius.com/745416d896c2bb3356cf7b00111f244d.490x490x1.png',
   'thumbnail_image_url': 'https://images.genius.com/745416d896c2bb3356cf7b00111f244d.300x300x1.png',
   'url': 'https://genius.com/album_cover_arts/468029',
   'current_user_metadata': {'permissions': [],
    'excluded_permissions': ['destroy']},
   'description_annotation': {'_type': 'referent',
    'annotator_id': 8491130,
    'annotator_login': 'Metalhead_Corgi',
    'api_path': '/referents/19582099',
    'classification': 'needs_exegesis',
    'fragment': 'https://images.genius.com/745416d896c2bb3356cf7b00111f244d.490x490x1.png',
    'id': 19582099,
    'ios_app_url': 'genius://referents/19582099',
    'is_description': True,
    'is_image': True,
    'path': '/19582099/Ultramega-ok/Https-imagesgeniuscom-745416d896c2bb3356cf7b00111f244d490x490x1png',
    'range': {'content': 'https://images.genius.com/745416d896c2bb3356cf7b00111f244d.490x490x1.png'},
    'song_id': None,
    'url': 'https://genius.com/19582099/Ultramega-ok/Https-imagesgeniuscom-745416d896c2bb3356cf7b00111f244d490x490x1png',
    'verified_annotator_ids': [],
    'current_user_metadata': {'permissions': [],
     'excluded_permissions': ['add_pinned_annotation_to',
      'add_community_annotation_to'],
     'relationships': {}},
    'tracking_paths': {'aggregate': '/19582099/Ultramega-ok/Https-imagesgeniuscom-745416d896c2bb3356cf7b00111f244d490x490x1png',
     'concurrent': '/albums/Soundgarden/Ultramega-ok'},
    'twitter_share_message': '“?” —@Genius',
    'annotatable': {'_type': 'cover_art',
     'api_path': '/albums/105320',
     'context': 'Soundgarden',
     'id': 468029,
     'image_url': 'https://images.genius.com/745416d896c2bb3356cf7b00111f244d.300x300x1.png',
     'link_title': 'Ultramega OK',
     'title': 'Ultramega OK',
     'type': 'CoverArt',
     'url': 'https://genius.com/album_cover_arts/468029'},
    'annotations': [{'_type': 'annotation',
      'api_path': '/annotations/19582099',
      'being_created': False,
      'body': {'plain': ''},
      'comment_count': 0,
      'community': True,
      'created_at': 1587058756,
      'custom_preview': None,
      'deleted': False,
      'embed_content': "<blockquote class='rg_standalone_container' data-src='//genius.com/annotations/19582099/standalone_embed'><a href='https://genius.com/19582099/Ultramega-ok/Https-imagesgeniuscom-745416d896c2bb3356cf7b00111f244d490x490x1png'>https://images.genius.com/745416d896c2bb3356cf7b00111f244d.490x490x1.png</a><br><a href='https://genius.com/album_cover_arts/468029'>&#8213; Ultramega OK</a></blockquote><script async crossorigin src='//genius.com/annotations/load_standalone_embeds.js'></script>",
      'has_voters': False,
      'id': 19582099,
      'needs_exegesis': True,
      'pinned': False,
      'proposed_edit_count': 0,
      'pyongs_count': None,
      'referent_id': 19582099,
      'share_url': 'https://genius.com/19582099',
      'source': None,
      'state': 'needs_exegesis',
      'twitter_share_message': '“?” —@Genius',
      'url': 'https://genius.com/19582099/Ultramega-ok/Https-imagesgeniuscom-745416d896c2bb3356cf7b00111f244d490x490x1png',
      'verified': False,
      'votes_total': 0,
      'current_user_metadata': {'permissions': [],
       'excluded_permissions': ['vote',
        'edit',
        'cosign',
        'uncosign',
        'destroy',
        'accept',
        'reject',
        'see_unreviewed',
        'clear_votes',
        'propose_edit_to',
        'pin_to_profile',
        'unpin_from_profile',
        'update_source',
        'edit_custom_preview',
        'report_as_abusive',
        'create_comment'],
       'interactions': {'cosign': False, 'pyong': False, 'vote': None},
       'iq_by_action': {}},
      'accepted_by': None,
      'authors': [{'_type': 'user_attribution',
        'attribution': 1.0,
        'pinned_role': None,
        'user': {'_type': 'user',
         'about_me_summary': 'https://www.instagram.com/kingdom_of_cruelty/\nDO NOT MESSAGE ME I WONT RESPOND MOST OF THE TIME (Unless if I fucked up at something)\nhttps://letterboxd.com/Metalhead_Corgi/\nhttps://www.last.fm/user/TRAIN_FOOD\nhttps://rateyourmusic.com/~ProcessofSuffocation666\nhttps://www.metal-archives.com/users/MrManMetal\n\nRest In Peace Tony Sly.\nAnti-Metal Elitist/Trans Female.\nFormerly known as Train_Food_dies, Pork_Soda_aka_thefrizzlefry, and MrMan Music.\n196 on Rock Genius All Time\n\nHit 1,000 – 2019\nHit 10,000 – 2019\nHit 20,000 – 8/23/19\nHit 30,000 – 1/25/20\nHit 40,000 – 5/7/20\nHit 50,000 – 6/6/20\n\nHit 60,000 – 7/5/20  \n\nSome of my favorite albums below:\n\n\n\n\n\nI Love the snow',
         'api_path': '/users/8491130',
         'avatar': {'tiny': {'url': 'https://images.genius.com/avatars/tiny/380cd5782db25c1cccbe269dde422303',
           'bounding_box': {'width': 16, 'height': 16}},
          'thumb': {'url': 'https://images.genius.com/avatars/thumb/380cd5782db25c1cccbe269dde422303',
           'bounding_box': {'width': 32, 'height': 32}},
          'small': {'url': 'https://images.genius.com/avatars/small/380cd5782db25c1cccbe269dde422303',
           'bounding_box': {'width': 100, 'height': 100}},
          'medium': {'url': 'https://images.genius.com/avatars/medium/380cd5782db25c1cccbe269dde422303',
           'bounding_box': {'width': 300, 'height': 400}}},
         'header_image_url': 'https://filepicker-images.genius.com/kr57c0b0b9b',
         'human_readable_role_for_display': 'Contributor',
         'id': 8491130,
         'iq': 68481,
         'is_meme_verified': False,
         'is_verified': False,
         'login': 'Metalhead_Corgi',
         'name': 'Metalhead_Corgi',
         'role_for_display': 'contributor',
         'url': 'https://genius.com/Metalhead_Corgi',
         'current_user_metadata': {'permissions': [],
          'excluded_permissions': ['follow'],
          'interactions': {'following': False}}}}],
      'cosigned_by': [],
      'created_by': {'_type': 'user',
       'about_me_summary': 'https://www.instagram.com/kingdom_of_cruelty/\nDO NOT MESSAGE ME I WONT RESPOND MOST OF THE TIME (Unless if I fucked up at something)\nhttps://letterboxd.com/Metalhead_Corgi/\nhttps://www.last.fm/user/TRAIN_FOOD\nhttps://rateyourmusic.com/~ProcessofSuffocation666\nhttps://www.metal-archives.com/users/MrManMetal\n\nRest In Peace Tony Sly.\nAnti-Metal Elitist/Trans Female.\nFormerly known as Train_Food_dies, Pork_Soda_aka_thefrizzlefry, and MrMan Music.\n196 on Rock Genius All Time\n\nHit 1,000 – 2019\nHit 10,000 – 2019\nHit 20,000 – 8/23/19\nHit 30,000 – 1/25/20\nHit 40,000 – 5/7/20\nHit 50,000 – 6/6/20\n\nHit 60,000 – 7/5/20  \n\nSome of my favorite albums below:\n\n\n\n\n\nI Love the snow',
       'api_path': '/users/8491130',
       'avatar': {'tiny': {'url': 'https://images.genius.com/avatars/tiny/380cd5782db25c1cccbe269dde422303',
         'bounding_box': {'width': 16, 'height': 16}},
        'thumb': {'url': 'https://images.genius.com/avatars/thumb/380cd5782db25c1cccbe269dde422303',
         'bounding_box': {'width': 32, 'height': 32}},
        'small': {'url': 'https://images.genius.com/avatars/small/380cd5782db25c1cccbe269dde422303',
         'bounding_box': {'width': 100, 'height': 100}},
        'medium': {'url': 'https://images.genius.com/avatars/medium/380cd5782db25c1cccbe269dde422303',
         'bounding_box': {'width': 300, 'height': 400}}},
       'header_image_url': 'https://filepicker-images.genius.com/kr57c0b0b9b',
       'human_readable_role_for_display': 'Contributor',
       'id': 8491130,
       'iq': 68481,
       'is_meme_verified': False,
       'is_verified': False,
       'login': 'Metalhead_Corgi',
       'name': 'Metalhead_Corgi',
       'role_for_display': 'contributor',
       'url': 'https://genius.com/Metalhead_Corgi',
       'current_user_metadata': {'permissions': [],
        'excluded_permissions': ['follow'],
        'interactions': {'following': False}}},
      'rejection_comment': None,
      'top_comment': None,
      'verified_by': None}]}},
  {'_type': 'cover_art',
   'annotated': False,
   'api_path': '/albums/105320',
   'id': 22250,
   'image_url': 'https://images.genius.com/a982c02aae1763c387ebd8161126c54c.300x300x1.jpg',
   'thumbnail_image_url': 'https://images.genius.com/a982c02aae1763c387ebd8161126c54c.300x300x1.jpg',
   'url': 'https://genius.com/album_cover_arts/22250',
   'current_user_metadata': {'permissions': [],
    'excluded_permissions': ['destroy']},
   'description_annotation': {'_type': 'referent',
    'annotator_id': 2937273,
    'annotator_login': 'geniusbot',
    'api_path': '/referents/12002465',
    'classification': 'needs_exegesis',
    'fragment': 'https://images.genius.com/a982c02aae1763c387ebd8161126c54c.300x300x1.jpg',
    'id': 12002465,
    'ios_app_url': 'genius://referents/12002465',
    'is_description': True,
    'is_image': True,
    'path': '/12002465/Ultramega-ok/Https-imagesgeniuscom-a982c02aae1763c387ebd8161126c54c300x300x1jpg',
    'range': {'content': 'https://images.genius.com/a982c02aae1763c387ebd8161126c54c.300x300x1.jpg'},
    'song_id': None,
    'url': 'https://genius.com/12002465/Ultramega-ok/Https-imagesgeniuscom-a982c02aae1763c387ebd8161126c54c300x300x1jpg',
    'verified_annotator_ids': [],
    'current_user_metadata': {'permissions': [],
     'excluded_permissions': ['add_pinned_annotation_to',
      'add_community_annotation_to'],
     'relationships': {}},
    'tracking_paths': {'aggregate': '/12002465/Ultramega-ok/Https-imagesgeniuscom-a982c02aae1763c387ebd8161126c54c300x300x1jpg',
     'concurrent': '/albums/Soundgarden/Ultramega-ok'},
    'twitter_share_message': '“?” —@Genius',
    'annotatable': {'_type': 'cover_art',
     'api_path': '/albums/105320',
     'context': 'Soundgarden',
     'id': 22250,
     'image_url': 'https://images.genius.com/a982c02aae1763c387ebd8161126c54c.300x300x1.jpg',
     'link_title': 'Ultramega OK',
     'title': 'Ultramega OK',
     'type': 'CoverArt',
     'url': 'https://genius.com/album_cover_arts/22250'},
    'annotations': [{'_type': 'annotation',
      'api_path': '/annotations/12002465',
      'being_created': False,
      'body': {'plain': ''},
      'comment_count': 0,
      'community': True,
      'created_at': 1496876221,
      'custom_preview': None,
      'deleted': False,
      'embed_content': "<blockquote class='rg_standalone_container' data-src='//genius.com/annotations/12002465/standalone_embed'><a href='https://genius.com/12002465/Ultramega-ok/Https-imagesgeniuscom-a982c02aae1763c387ebd8161126c54c300x300x1jpg'>https://images.genius.com/a982c02aae1763c387ebd8161126c54c.300x300x1.jpg</a><br><a href='https://genius.com/album_cover_arts/22250'>&#8213; Ultramega OK</a></blockquote><script async crossorigin src='//genius.com/annotations/load_standalone_embeds.js'></script>",
      'has_voters': False,
      'id': 12002465,
      'needs_exegesis': True,
      'pinned': False,
      'proposed_edit_count': 0,
      'pyongs_count': None,
      'referent_id': 12002465,
      'share_url': 'https://genius.com/12002465',
      'source': None,
      'state': 'needs_exegesis',
      'twitter_share_message': '“?” —@Genius',
      'url': 'https://genius.com/12002465/Ultramega-ok/Https-imagesgeniuscom-a982c02aae1763c387ebd8161126c54c300x300x1jpg',
      'verified': False,
      'votes_total': 0,
      'current_user_metadata': {'permissions': [],
       'excluded_permissions': ['vote',
        'edit',
        'cosign',
        'uncosign',
        'destroy',
        'accept',
        'reject',
        'see_unreviewed',
        'clear_votes',
        'propose_edit_to',
        'pin_to_profile',
        'unpin_from_profile',
        'update_source',
        'edit_custom_preview',
        'report_as_abusive',
        'create_comment'],
       'interactions': {'cosign': False, 'pyong': False, 'vote': None},
       'iq_by_action': {}},
      'accepted_by': None,
      'authors': [{'_type': 'user_attribution',
        'attribution': 1.0,
        'pinned_role': None,
        'user': {'_type': 'user',
         'about_me_summary': 'Hi! I’m the Genius Bot, a robotic user who performs automated tasks on the site. My behavior was programmed by the tech team, and my job is to help keep the site’s data crisp and clean.\n\nIf I’ve rejected or deleted your annotation, check out this thread to learn more.\n\nIf you notice me doing anything else that seems wrong, please hit up the bugs forum!',
         'api_path': '/users/2937273',
         'avatar': {'tiny': {'url': 'https://images.genius.com/avatars/tiny/d8178e34dd5f45daf6e9cb62f8e3b996',
           'bounding_box': {'width': 16, 'height': 16}},
          'thumb': {'url': 'https://images.genius.com/avatars/thumb/d8178e34dd5f45daf6e9cb62f8e3b996',
           'bounding_box': {'width': 32, 'height': 32}},
          'small': {'url': 'https://images.genius.com/avatars/small/d8178e34dd5f45daf6e9cb62f8e3b996',
           'bounding_box': {'width': 100, 'height': 100}},
          'medium': {'url': 'https://images.genius.com/avatars/medium/d8178e34dd5f45daf6e9cb62f8e3b996',
           'bounding_box': {'width': 300, 'height': 400}}},
         'header_image_url': 'https://assets.genius.com/images/default_banner.png?1783019845',
         'human_readable_role_for_display': 'Staff',
         'id': 2937273,
         'iq': 0,
         'is_meme_verified': False,
         'is_verified': False,
         'login': 'geniusbot',
         'name': 'geniusbot',
         'role_for_display': 'staff',
         'url': 'https://genius.com/geniusbot',
         'current_user_metadata': {'permissions': [],
          'excluded_permissions': ['follow'],
          'interactions': {'following': False}}}}],
      'cosigned_by': [],
      'created_by': {'_type': 'user',
       'about_me_summary': 'Hi! I’m the Genius Bot, a robotic user who performs automated tasks on the site. My behavior was programmed by the tech team, and my job is to help keep the site’s data crisp and clean.\n\nIf I’ve rejected or deleted your annotation, check out this thread to learn more.\n\nIf you notice me doing anything else that seems wrong, please hit up the bugs forum!',
       'api_path': '/users/2937273',
       'avatar': {'tiny': {'url': 'https://images.genius.com/avatars/tiny/d8178e34dd5f45daf6e9cb62f8e3b996',
         'bounding_box': {'width': 16, 'height': 16}},
        'thumb': {'url': 'https://images.genius.com/avatars/thumb/d8178e34dd5f45daf6e9cb62f8e3b996',
         'bounding_box': {'width': 32, 'height': 32}},
        'small': {'url': 'https://images.genius.com/avatars/small/d8178e34dd5f45daf6e9cb62f8e3b996',
         'bounding_box': {'width': 100, 'height': 100}},
        'medium': {'url': 'https://images.genius.com/avatars/medium/d8178e34dd5f45daf6e9cb62f8e3b996',
         'bounding_box': {'width': 300, 'height': 400}}},
       'header_image_url': 'https://assets.genius.com/images/default_banner.png?1783019845',
       'human_readable_role_for_display': 'Staff',
       'id': 2937273,
       'iq': 0,
       'is_meme_verified': False,
       'is_verified': False,
       'login': 'geniusbot',
       'name': 'geniusbot',
       'role_for_display': 'staff',
       'url': 'https://genius.com/geniusbot',
       'current_user_metadata': {'permissions': [],
        'excluded_permissions': ['follow'],
        'interactions': {'following': False}}},
      'rejection_comment': None,
      'top_comment': None,
      'verified_by': None}]}}],
 'description_annotation': {'_type': 'referent',
  'annotator_id': 10081309,
  'annotator_login': 'XxxF00FighterxxX',
  'api_path': '/referents/7577763',
  'classification': 'unreviewed',
  'fragment': 'Ultramega OK',
  'id': 7577763,
  'ios_app_url': 'genius://referents/7577763',
  'is_description': True,
  'is_image': False,
  'path': '/7577763/Ultramega-ok/Ultramega-ok',
  'range': {'content': 'Ultramega OK'},
  'song_id': None,
  'url': 'https://genius.com/7577763/Ultramega-ok/Ultramega-ok',
  'verified_annotator_ids': [],
  'current_user_metadata': {'permissions': [],
   'excluded_permissions': ['add_pinned_annotation_to',
    'add_community_annotation_to'],
   'relationships': {}},
  'tracking_paths': {'aggregate': '/7577763/Ultramega-ok/Ultramega-ok',
   'concurrent': '/albums/Soundgarden/Ultramega-ok'},
  'twitter_share_message': '“Soundgarden’s debut album” —@Genius',
  'annotatable': {'_type': 'album',
   'api_path': '/albums/105320',
   'context': 'Soundgarden',
   'id': 105320,
   'image_url': 'https://images.genius.com/745416d896c2bb3356cf7b00111f244d.300x300x1.png',
   'link_title': 'Ultramega OK',
   'title': 'Ultramega OK',
   'type': 'Album',
   'url': 'https://genius.com/albums/Soundgarden/Ultramega-ok'},
  'annotations': [{'_type': 'annotation',
    'api_path': '/annotations/7577763',
    'being_created': False,
    'body': {'plain': 'Soundgarden’s debut album'},
    'comment_count': 1,

In [205]:
#Pandas dataframe columns

ultramegaok_soundgarden_df = pd.DataFrame(columns=['track_title', 'track_lyrics', 'album_name', 'project_name', 'release_year', 'label'])

In [206]:
track_title = []

for track in ultramegaok["tracks"]:
    track_title.append(track['song']['title'])

In [207]:
ultramegaok_soundgarden_df['track_title'] = track_title

In [208]:
ultramegaok_soundgarden_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Flower,NaN,NaN,NaN,NaN,NaN
1,All Your Lies,NaN,NaN,NaN,NaN,NaN
2,665,NaN,NaN,NaN,NaN,NaN
3,Beyond the Wheel,NaN,NaN,NaN,NaN,NaN
4,667,NaN,NaN,NaN,NaN,NaN
5,Mood for Trouble,NaN,NaN,NaN,NaN,NaN
6,Circle of Power,NaN,NaN,NaN,NaN,NaN
7,He Didn’t,NaN,NaN,NaN,NaN,NaN
8,Smokestack Lightning,NaN,NaN,NaN,NaN,NaN
9,Nazi Driver,NaN,NaN,NaN,NaN,NaN
10,Head Injury,NaN,NaN,NaN,NaN,NaN
11,Incessant Mace,NaN,NaN,NaN,NaN,NaN
12,One Minute of Silence,NaN,NaN,NaN,NaN,NaN

In [209]:
track_lyrics = []

for lyric in ultramegaok["tracks"]:
    track_lyrics.append(lyric['song']['lyrics'])

In [210]:
ultramegaok_soundgarden_df['track_lyrics'] = track_lyrics

In [211]:
ultramegaok_soundgarden_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Flower,[Intro]\nAlong her vain parade\nAlong her vein...,NaN,NaN,NaN,NaN
1,All Your Lies,[Intro]\nAll your fears are lies\nAll your fea...,NaN,NaN,NaN,NaN
2,665,[Verse (forward)]\nIt's creeping in so slow\nT...,NaN,NaN,NaN,NaN
3,Beyond the Wheel,[Verse 1]\nFar beyond the road\nBetween your h...,NaN,NaN,NaN,NaN
4,667,[Interlude]\nKill them all\nSteal their gold\n...,NaN,NaN,NaN,NaN
5,Mood for Trouble,[Verse 1]\nMy mood was in full swing\nMy mood ...,NaN,NaN,NaN,NaN
6,Circle of Power,[Verse 1]\nThe day will finally come and\nThe ...,NaN,NaN,NaN,NaN
7,He Didn’t,[Verse 1]\nHe did nothing perfectly\nHe did no...,NaN,NaN,NaN,NaN
8,Smokestack Lightning,"[Intro]\nHey-yeah\n\n[Verse 1]\nHey, smokestac...",NaN,NaN,NaN,NaN
9,Nazi Driver,[Verse 1]\nI don't care if it takes some time\...,NaN,NaN,NaN,NaN
10,Head Injury,[Chorus]\nWow!\nHead injury\nHead injury\nHead...,NaN,NaN,NaN,NaN
11,Incessant Mace,"[Intro]\nYeah-hoo-ooh, ooh-ooh-ooh-oh\nMmm\n\n...",NaN,NaN,NaN,NaN
12,One Minute of Silence,,NaN,NaN,NaN,NaN

In [212]:
ultramegaok_soundgarden_df['album_name']= ultramegaok['name']

In [213]:
ultramegaok_soundgarden_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Flower,[Intro]\nAlong her vain parade\nAlong her vein...,Ultramega OK,NaN,NaN,NaN
1,All Your Lies,[Intro]\nAll your fears are lies\nAll your fea...,Ultramega OK,NaN,NaN,NaN
2,665,[Verse (forward)]\nIt's creeping in so slow\nT...,Ultramega OK,NaN,NaN,NaN
3,Beyond the Wheel,[Verse 1]\nFar beyond the road\nBetween your h...,Ultramega OK,NaN,NaN,NaN
4,667,[Interlude]\nKill them all\nSteal their gold\n...,Ultramega OK,NaN,NaN,NaN
5,Mood for Trouble,[Verse 1]\nMy mood was in full swing\nMy mood ...,Ultramega OK,NaN,NaN,NaN
6,Circle of Power,[Verse 1]\nThe day will finally come and\nThe ...,Ultramega OK,NaN,NaN,NaN
7,He Didn’t,[Verse 1]\nHe did nothing perfectly\nHe did no...,Ultramega OK,NaN,NaN,NaN
8,Smokestack Lightning,"[Intro]\nHey-yeah\n\n[Verse 1]\nHey, smokestac...",Ultramega OK,NaN,NaN,NaN
9,Nazi Driver,[Verse 1]\nI don't care if it takes some time\...,Ultramega OK,NaN,NaN,NaN
10,Head Injury,[Chorus]\nWow!\nHead injury\nHead injury\nHead...,Ultramega OK,NaN,NaN,NaN
11,Incessant Mace,"[Intro]\nYeah-hoo-ooh, ooh-ooh-ooh-oh\nMmm\n\n...",Ultramega OK,NaN,NaN,NaN
12,One Minute of Silence,,Ultramega OK,NaN,NaN,NaN

In [214]:
ultramegaok_soundgarden_df['release_year']= ultramegaok['release_date_components']['year']

In [215]:
ultramegaok_soundgarden_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Flower,[Intro]\nAlong her vain parade\nAlong her vein...,Ultramega OK,NaN,1988,NaN
1,All Your Lies,[Intro]\nAll your fears are lies\nAll your fea...,Ultramega OK,NaN,1988,NaN
2,665,[Verse (forward)]\nIt's creeping in so slow\nT...,Ultramega OK,NaN,1988,NaN
3,Beyond the Wheel,[Verse 1]\nFar beyond the road\nBetween your h...,Ultramega OK,NaN,1988,NaN
4,667,[Interlude]\nKill them all\nSteal their gold\n...,Ultramega OK,NaN,1988,NaN
5,Mood for Trouble,[Verse 1]\nMy mood was in full swing\nMy mood ...,Ultramega OK,NaN,1988,NaN
6,Circle of Power,[Verse 1]\nThe day will finally come and\nThe ...,Ultramega OK,NaN,1988,NaN
7,He Didn’t,[Verse 1]\nHe did nothing perfectly\nHe did no...,Ultramega OK,NaN,1988,NaN
8,Smokestack Lightning,"[Intro]\nHey-yeah\n\n[Verse 1]\nHey, smokestac...",Ultramega OK,NaN,1988,NaN
9,Nazi Driver,[Verse 1]\nI don't care if it takes some time\...,Ultramega OK,NaN,1988,NaN
10,Head Injury,[Chorus]\nWow!\nHead injury\nHead injury\nHead...,Ultramega OK,NaN,1988,NaN
11,Incessant Mace,"[Intro]\nYeah-hoo-ooh, ooh-ooh-ooh-oh\nMmm\n\n...",Ultramega OK,NaN,1988,NaN
12,One Minute of Silence,,Ultramega OK,NaN,1988,NaN

In [216]:
ultramegaok_soundgarden_df['label']=ultramegaok['song_performances'][9]['artists'][0]['name']

In [217]:
ultramegaok_soundgarden_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Flower,[Intro]\nAlong her vain parade\nAlong her vein...,Ultramega OK,NaN,1988,SST Records
1,All Your Lies,[Intro]\nAll your fears are lies\nAll your fea...,Ultramega OK,NaN,1988,SST Records
2,665,[Verse (forward)]\nIt's creeping in so slow\nT...,Ultramega OK,NaN,1988,SST Records
3,Beyond the Wheel,[Verse 1]\nFar beyond the road\nBetween your h...,Ultramega OK,NaN,1988,SST Records
4,667,[Interlude]\nKill them all\nSteal their gold\n...,Ultramega OK,NaN,1988,SST Records
5,Mood for Trouble,[Verse 1]\nMy mood was in full swing\nMy mood ...,Ultramega OK,NaN,1988,SST Records
6,Circle of Power,[Verse 1]\nThe day will finally come and\nThe ...,Ultramega OK,NaN,1988,SST Records
7,He Didn’t,[Verse 1]\nHe did nothing perfectly\nHe did no...,Ultramega OK,NaN,1988,SST Records
8,Smokestack Lightning,"[Intro]\nHey-yeah\n\n[Verse 1]\nHey, smokestac...",Ultramega OK,NaN,1988,SST Records
9,Nazi Driver,[Verse 1]\nI don't care if it takes some time\...,Ultramega OK,NaN,1988,SST Records
10,Head Injury,[Chorus]\nWow!\nHead injury\nHead injury\nHead...,Ultramega OK,NaN,1988,SST Records
11,Incessant Mace,"[Intro]\nYeah-hoo-ooh, ooh-ooh-ooh-oh\nMmm\n\n...",Ultramega OK,NaN,1988,SST Records
12,One Minute of Silence,,Ultramega OK,NaN,1988,SST Records

In [218]:
ultramegaok_soundgarden_df['project_name']=ultramegaok['primary_artist_names']

In [219]:
ultramegaok_soundgarden_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Flower,[Intro]\nAlong her vain parade\nAlong her vein...,Ultramega OK,Soundgarden,1988,SST Records
1,All Your Lies,[Intro]\nAll your fears are lies\nAll your fea...,Ultramega OK,Soundgarden,1988,SST Records
2,665,[Verse (forward)]\nIt's creeping in so slow\nT...,Ultramega OK,Soundgarden,1988,SST Records
3,Beyond the Wheel,[Verse 1]\nFar beyond the road\nBetween your h...,Ultramega OK,Soundgarden,1988,SST Records
4,667,[Interlude]\nKill them all\nSteal their gold\n...,Ultramega OK,Soundgarden,1988,SST Records
5,Mood for Trouble,[Verse 1]\nMy mood was in full swing\nMy mood ...,Ultramega OK,Soundgarden,1988,SST Records
6,Circle of Power,[Verse 1]\nThe day will finally come and\nThe ...,Ultramega OK,Soundgarden,1988,SST Records
7,He Didn’t,[Verse 1]\nHe did nothing perfectly\nHe did no...,Ultramega OK,Soundgarden,1988,SST Records
8,Smokestack Lightning,"[Intro]\nHey-yeah\n\n[Verse 1]\nHey, smokestac...",Ultramega OK,Soundgarden,1988,SST Records
9,Nazi Driver,[Verse 1]\nI don't care if it takes some time\...,Ultramega OK,Soundgarden,1988,SST Records
10,Head Injury,[Chorus]\nWow!\nHead injury\nHead injury\nHead...,Ultramega OK,Soundgarden,1988,SST Records
11,Incessant Mace,"[Intro]\nYeah-hoo-ooh, ooh-ooh-ooh-oh\nMmm\n\n...",Ultramega OK,Soundgarden,1988,SST Records
12,One Minute of Silence,,Ultramega OK,Soundgarden,1988,SST Records

In [141]:
album = genius.search_album("King Animal", "Soundgarden")

INFO lyricsgenius.genius: Searching for "King Animal" by Soundgarden...
DEBUG urllib3.connectionpool: Starting new HTTPS connection (3): genius.com:443
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/search/multi?q=King+Animal+Soundgarden HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/albums/26866?text_format=plain HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/albums/26866/tracks?per_page=50&page=1&text_format=plain HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-been-away-too-long-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-non-state-actor-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-by-crooked-steps-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-a-thousand-days-before-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-blood-on-the-valley-floor-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-bones-of-birds-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-taree-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-attrition-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-black-saturday-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-halfway-there-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-worse-dreams-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-eyelids-mouth-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Soundgarden-rowing-lyrics HTTP/2.0" 200 None

In [142]:
album.save_lyrics()

DEBUG lyricsgenius.types.base: Wrote saved_album_lyrics_soundgarden_king_animal.json.

In [220]:
with open('saved_album_lyrics_soundgarden_king_animal.json') as kinganimal:
    kinganimal = json.load(kinganimal)
kinganimal

{'_type': 'album',
 'api_path': '/albums/26866',
 'cover_art_thumbnail_url': 'https://images.genius.com/25a508117ccc035eca5822a8a080a740.300x300x1.png',
 'cover_art_url': 'https://images.genius.com/25a508117ccc035eca5822a8a080a740.1000x1000x1.png',
 'full_title': 'King Animal by Soundgarden',
 'id': 26866,
 'name': 'King Animal',
 'name_with_artist': 'King Animal (artist: Soundgarden)',
 'primary_artist_names': 'Soundgarden',
 'pusher_channel': 'album-26866',
 'release_date_components': {'year': 2012, 'month': 11, 'day': 13},
 'release_date_for_display': 'November 13, 2012',
 'updated_at': 1758085795,
 'url': 'https://genius.com/albums/Soundgarden/King-animal',
 'current_user_metadata': {'permissions': ['create_comment'],
  'excluded_permissions': ['set_album_color_gradient',
   'edit',
   'destroy',
   'pyong',
   'lock',
   'super_lock',
   'unlock',
   'sort_songs',
   'hide',
   'unhide',
   'see_short_id',
   'create_additional_role',
   'create_question'],
  'interactions': {'pyong': False, 'following': False},
  'iq_by_action': {}},
 'artist': 'Soundgarden',
 'primary_artists': [{'_type': 'artist',
   'api_path': '/artists/19976',
   'header_image_url': 'https://images.genius.com/6bbfe726dc5523b85c557274a3a67d51.1000x696x1.jpg',
   'id': 19976,
   'image_url': 'https://images.genius.com/f96fac2a51d57a7c0c80611c201f10c1.570x570x1.jpg',
   'index_character': 's',
   'is_meme_verified': False,
   'is_verified': False,
   'links_config': None,
   'name': 'Soundgarden',
   'slug': 'Soundgarden',
   'url': 'https://genius.com/artists/Soundgarden'}],
 'album_type': 'album',
 'comment_count': 1,
 'custom_header_image_url': None,
 'description_preview': 'Soundgarden’s sixth studio album and its first of original material since the band’s 2010 reformation.\n\nWhile it was the first new SG album in 16 years, it also marked the band’s first album on a label other than A&M since 1988’s Ultramega OK.',
 'header_image_url': 'https://images.genius.com/25a508117ccc035eca5822a8a080a740.1000x1000x1.png',
 'hidden': False,
 'language': None,
 'lock_state': 'editable',
 'pyongs_count': 0,
 'release_date': '2012-11-13',
 'tracking_paths': {'aggregate': '/albums/Soundgarden/King-animal',
  'concurrent': '/albums/Soundgarden/King-animal'},
 'viewable_by_roles': [],
 'album_art_primary_color': '#d4bc84',
 'album_art_secondary_color': '#f9efd3',
 'album_art_text_color': '#000',
 'song_pageviews': 73668,
 'album_relationships': [{'_type': 'album_relationship',
   'relationship_type': 'deluxe_edition_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_deluxe_edition',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'alternate_version_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_alternate_version',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'reissue_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_reissue',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'remix_version_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_remix_version',
   'albums': []}],
 'cover_arts': [{'_type': 'cover_art',
   'annotated': True,
   'api_path': '/albums/26866',
   'id': 9105,
   'image_url': 'https://images.genius.com/25a508117ccc035eca5822a8a080a740.1000x1000x1.png',
   'thumbnail_image_url': 'https://images.genius.com/25a508117ccc035eca5822a8a080a740.300x300x1.png',
   'url': 'https://genius.com/album_cover_arts/9105',
   'current_user_metadata': {'permissions': [],
    'excluded_permissions': ['destroy']},
   'description_annotation': {'_type': 'referent',
    'annotator_id': 269182,
    'annotator_login': 'igordebraga',
    'api_path': '/referents/11989129',
    'classification': 'accepted',
    'fragment': 'https://images.genius.com/25a508117ccc035eca5822a8a080a740.1000x1000x1.png',
    'id': 11989129,
    'ios_app_url': 'genius://referents/11989129',
    'is_description': True,
    'is_image': True,
    'path': '/11989129/King-animal/Https-imagesgeniuscom-25a508117ccc035eca5822a8a080a7401000x1000x1png',
    'range': {'content': 'https://images.genius.com/25a508117ccc035eca5822a8a080a740.1000x1000x1.png'},
    'song_id': None,
    'url': 'https://genius.com/11989129/King-animal/Https-imagesgeniuscom-25a508117ccc035eca5822a8a080a7401000x1000x1png',
    'verified_annotator_ids': [],
    'current_user_metadata': {'permissions': [],
     'excluded_permissions': ['add_pinned_annotation_to',
      'add_community_annotation_to'],
     'relationships': {}},
    'tracking_paths': {'aggregate': '/11989129/King-animal/Https-imagesgeniuscom-25a508117ccc035eca5822a8a080a7401000x1000x1png',
     'concurrent': '/albums/Soundgarden/King-animal'},
    'twitter_share_message': '“Kim Thayil saw A Storm Of Light in concert as they opened for the band he was playing with, Shri…” —@Genius',
    'annotatable': {'_type': 'cover_art',
     'api_path': '/albums/26866',
     'context': 'Soundgarden',
     'id': 9105,
     'image_url': 'https://images.genius.com/25a508117ccc035eca5822a8a080a740.300x300x1.png',
     'link_title': 'King Animal',
     'title': 'King Animal',
     'type': 'CoverArt',
     'url': 'https://genius.com/album_cover_arts/9105'},
    'annotations': [{'_type': 'annotation',
      'api_path': '/annotations/11989129',
      'being_created': False,
      'body': {'plain': 'Kim Thayil saw A Storm Of Light in concert as they opened for the band he was playing with, Shrinebuilder, and purchased their albums, featuring artwork by  frontman Josh Graham. One year later , Graham got a call saying Thayil’s Soundgarden was reuniting, and they wanted him to become their creative director.\n\nFor their reunion studio album, the only thing Graham was requested was a lighter color palette, given all of Soundgarden’s previous covers had a darker chromatic approach.\nThe final result, a sculpture titled “The Last Equinox”, features a pile of skulls and flowers in the middle of a snowy forest (built in Graham’s attic simultaneously to the cover for a Neurosis album).  Graham’s constants of his works,  light, dark, shadow space and natural forms, are employed, depicting “the fleeting nature of the illusion of permanence":\n\nIt’s synonymous with birth and with death. And everything between there is such a massive part of the human condition.\n\nThayil said that “We used skulls to convey [distance] not some weird, metal, mystical power”, and Chris Cornell added that while it showed  Graham’s interpretation, it also  somehow fit the band’s frequent moody lyrics with an outdoor theme'},
      'comment_count': 0,
      'community': True,
      'created_at': 1500605274,
      'custom_preview': None,
      'deleted': False,
      'embed_content': "<blockquote class='rg_standalone_container' data-src='//genius.com/annotations/11989129/standalone_embed'><a href='https://genius.com/11989129/King-animal/Https-imagesgeniuscom-25a508117ccc035eca5822a8a080a7401000x1000x1png'>https://images.genius.com/25a508117ccc035eca5822a8a080a740.1000x1000x1.png</a><br><a href='https://genius.com/album_cover_arts/9105'>&#8213; King Animal</a></blockquote><script async crossorigin src='//genius.com/annotations/load_standalone_embeds.js'></script>",
      'has_voters': True,
      'id': 11989129,
      'needs_exegesis': False,
      'pinned': False,
      'proposed_edit_count': 0,
      'pyongs_count': None,
      'referent_id': 11989129,
      'share_url': 'https://genius.com/11989129',
      'source': None,
      'state': 'accepted',
      'twitter_share_message': '“Kim Thayil saw A Storm Of Light in concert as they opened for the band he was playing with, Shrinebuilde…” —@Genius',
      'url': 'https://genius.com/11989129/King-animal/Https-imagesgeniuscom-25a508117ccc035eca5822a8a080a7401000x1000x1png',
      'verified': False,
      'votes_total': 1,
      'current_user_metadata': {'permissions': [],
       'excluded_permissions': ['vote',
        'edit',
        'cosign',
        'uncosign',
        'destroy',
        'accept',
        'reject',
        'see_unreviewed',
        'clear_votes',
        'propose_edit_to',
        'pin_to_profile',
        'unpin_from_profile',
        'update_source',
        'edit_custom_preview',
        'report_as_abusive',
        'create_comment'],
       'interactions': {'cosign': False, 'pyong': False, 'vote': None},
       'iq_by_action': {}},
      'accepted_by': {'_type': 'user',
       'about_me_summary': 'I like Alternative Rock from the 90s\n\n\n\nGoals reached:\n\n\nFeb 2014: Joined\n\n21 Sep 2014: Editored by Vesuvius\n\n16 Dec 2014: 10,000 IQ\n\n23 Dec 2015: 25,000 IQ\n\n27 Nov 2016: 50,000 IQ\n\n17 Dec 2017: 100,000 IQ\n\n6 Aug 2025: 250,000 IQ',
       'api_path': '/users/554585',
       'avatar': {'tiny': {'url': 'https://images.genius.com/avatars/tiny/df01a27aedee449e11963ea1b1cb0cab',
         'bounding_box': {'width': 16, 'height': 16}},
        'thumb': {'url': 'https://images.genius.com/avatars/thumb/df01a27aedee449e11963ea1b1cb0cab',
         'bounding_box': {'width': 32, 'height': 32}},
        'small': {'url': 'https://images.genius.com/avatars/small/df01a27aedee449e11963ea1b1cb0cab',
         'bounding_box': {'width': 100, 'height': 100}},
        'medium': {'url': 'https://images.genius.com/avatars/medium/df01a27aedee449e11963ea1b1cb0cab',
         'bounding_box': {'width': 300, 'height': 400}}},
       'header_image_url': 'https://images.genius.com/9ff1f1de42863e6500317d72e88f48d1.500x270x22.gif',
       'human_readable_role_for_display': 'Editor',
       'id': 554585,
       'iq': 265232,
       'is_meme_verified': False,
       'is_verified': False,
       'login': 'IThinkImAndrea',
       'name': 'IThinkImAndrea',
       'role_for_display': 'editor',
       'url': 'https://genius.com/IThinkImAndrea',
       'current_user_metadata': {'permissions': [],
        'excluded_permissions': ['follow'],
        'interactions': {'following': False}}},
      'authors': [{'_type': 'user_attribution',
        'attribution': 1.0,
        'pinned_role': None,
        'user': {'_type': 'user',
         'about_me_summary': 'Half afraid, half amazed, all insane.',
         'api_path': '/users/269182',
         'avatar': {'tiny': {'url': 'https://images.genius.com/avatars/tiny/5f579d275735b22510e0bc9a06171bde',
           'bounding_box': {'width': 16, 'height': 16}},
          'thumb': {'url': 'https://images.genius.com/avatars/thumb/5f579d275735b22510e0bc9a06171bde',
           'bounding_box': {'width': 32, 'height': 32}},
          'small': {'url': 'https://images.genius.com/avatars/small/5f579d275735b22510e0bc9a06171bde',
           'bounding_box': {'width': 100, 'height': 100}},
          'medium': {'url': 'https://images.genius.com/avatars/medium/5f579d275735b22510e0bc9a06171bde',
           'bounding_box': {'width': 300, 'height': 400}}},
         'header_image_url': 'https://filepicker-images.genius.com/3GmrMEUaTVW5V3WEham0_Foto0079.jpg',
         'human_readable_role_for_display': 'Contributor',
         'id': 269182,
         'iq': 454050,
         'is_meme_verified': False,
         'is_verified': False,
         'login': 'igordebraga',
         'name': 'igordebraga',
         'role_for_display': 'contributor',
         'url': 'https://genius.com/igordebraga',
         'current_user_metadata': {'permissions': [],
          'excluded_permissions': ['follow'],
          'interactions': {'following': False}}}}],
      'cosigned_by': [],
      'created_by': {'_type': 'user',
       'about_me_summary': 'Half afraid, half amazed, all insane.',
       'api_path': '/users/269182',
       'avatar': {'tiny': {'url': 'https://images.genius.com/avatars/tiny/5f579d275735b22510e0bc9a06171bde',
         'bounding_box': {'width': 16, 'height': 16}},
        'thumb': {'url': 'https://images.genius.com/avatars/thumb/5f579d275735b22510e0bc9a06171bde',
         'bounding_box': {'width': 32, 'height': 32}},
        'small': {'url': 'https://images.genius.com/avatars/small/5f579d275735b22510e0bc9a06171bde',
         'bounding_box': {'width': 100, 'height': 100}},
        'medium': {'url': 'https://images.genius.com/avatars/medium/5f579d275735b22510e0bc9a06171bde',
         'bounding_box': {'width': 300, 'height': 400}}},
       'header_image_url': 'https://filepicker-images.genius.com/3GmrMEUaTVW5V3WEham0_Foto0079.jpg',
       'human_readable_role_for_display': 'Contributor',
       'id': 269182,
       'iq': 454050,
       'is_meme_verified': False,
       'is_verified': False,
       'login': 'igordebraga',
       'name': 'igordebraga',
       'role_for_display': 'contributor',
       'url': 'https://genius.com/igordebraga',
       'current_user_metadata': {'permissions': [],
        'excluded_permissions': ['follow'],
        'interactions': {'following': False}}},
      'rejection_comment': None,
      'top_comment': None,
      'verified_by': None}]}},
  {'_type': 'cover_art',
   'annotated': False,
   'api_path': '/albums/26866',
   'id': 242201,
   'image_url': 'https://images.genius.com/9697a23a5906b146f1890b1314668ea1.594x594x1.jpg',
   'thumbnail_image_url': 'https://images.genius.com/9697a23a5906b146f1890b1314668ea1.300x300x1.jpg',
   'url': 'https://genius.com/album_cover_arts/242201',
   'current_user_metadata': {'permissions': [],
    'excluded_permissions': ['destroy']},
   'description_annotation': {'_type': 'referent',
    'annotator_id': 6246835,
    'annotator_login': 'gone_3pw37_867d',
    'api_path': '/referents/14824722',
    'classification': 'needs_exegesis',
    'fragment': 'https://images.genius.com/9697a23a5906b146f1890b1314668ea1.594x594x1.jpg',
    'id': 14824722,
    'ios_app_url': 'genius://referents/14824722',
    'is_description': True,
    'is_image': True,
    'path': '/14824722/King-animal/Https-imagesgeniuscom-9697a23a5906b146f1890b1314668ea1594x594x1jpg',
    'range': {'content': 'https://images.genius.com/9697a23a5906b146f1890b1314668ea1.594x594x1.jpg'},
    'song_id': None,
    'url': 'https://genius.com/14824722/King-animal/Https-imagesgeniuscom-9697a23a5906b146f1890b1314668ea1594x594x1jpg',
    'verified_annotator_ids': [],
    'current_user_metadata': {'permissions': [],
     'excluded_permissions': ['add_pinned_annotation_to',
      'add_community_annotation_to'],
     'relationships': {}},
    'tracking_paths': {'aggregate': '/14824722/King-animal/Https-imagesgeniuscom-9697a23a5906b146f1890b1314668ea1594x594x1jpg',
     'concurrent': '/albums/Soundgarden/King-animal'},
    'twitter_share_message': '“?” —@Genius',
    'annotatable': {'_type': 'cover_art',
     'api_path': '/albums/26866',
     'context': 'Soundgarden',
     'id': 242201,
     'image_url': 'https://images.genius.com/9697a23a5906b146f1890b1314668ea1.300x300x1.jpg',
     'link_title': 'King Animal',
     'title': 'King Animal',
     'type': 'CoverArt',
     'url': 'https://genius.com/album_cover_arts/242201'},
    'annotations': [{'_type': 'annotation',
      'api_path': '/annotations/14824722',
      'being_created': False,
      'body': {'plain': ''},
      'comment_count': 0,
      'community': True,
      'created_at': 1529544830,
      'custom_preview': None,
      'deleted': False,
      'embed_content': "<blockquote class='rg_standalone_container' data-src='//genius.com/annotations/14824722/standalone_embed'><a href='https://genius.com/14824722/King-animal/Https-imagesgeniuscom-9697a23a5906b146f1890b1314668ea1594x594x1jpg'>https://images.genius.com/9697a23a5906b146f1890b1314668ea1.594x594x1.jpg</a><br><a href='https://genius.com/album_cover_arts/242201'>&#8213; King Animal</a></blockquote><script async crossorigin src='//genius.com/annotations/load_standalone_embeds.js'></script>",
      'has_voters': False,
      'id': 14824722,
      'needs_exegesis': True,
      'pinned': False,
      'proposed_edit_count': 0,
      'pyongs_count': None,
      'referent_id': 14824722,
      'share_url': 'https://genius.com/14824722',
      'source': None,
      'state': 'needs_exegesis',
      'twitter_share_message': '“?” —@Genius',
      'url': 'https://genius.com/14824722/King-animal/Https-imagesgeniuscom-9697a23a5906b146f1890b1314668ea1594x594x1jpg',
      'verified': False,
      'votes_total': 0,
      'current_user_metadata': {'permissions': [],
       'excluded_permissions': ['vote',
        'edit',
        'cosign',
        'uncosign',
        'destroy',
        'accept',
        'reject',
        'see_unreviewed',
        'clear_votes',
        'propose_edit_to',
        'pin_to_profile',
        'unpin_from_profile',
        'update_source',
        'edit_custom_preview',
        'report_as_abusive',
        'create_comment'],
       'interactions': {'cosign': False, 'pyong': False, 'vote': None},
       'iq_by_action': {}},
      'accepted_by': None,
      'authors': [{'_type': 'user_attribution',
        'attribution': 1.0,
        'pinned_role': None,
        'user': {'_type': 'user',
         'about_me_summary': '',
         'api_path': '/users/6246835',
         'avatar': {'tiny': {'url': 'https://assets.genius.com/images/default_cover_image.png?1783019845',
           'bounding_box': {'width': 16, 'height': 16}},
          'thumb': {'url': 'https://assets.genius.com/images/default_cover_image.png?1783019845',
           'bounding_box': {'width': 32, 'height': 32}},
          'small': {'url': 'https://assets.genius.com/images/default_cover_image.png?1783019845',
           'bounding_box': {'width': 100, 'height': 100}},
          'medium': {'url': 'https://assets.genius.com/images/default_cover_image.png?1783019845',
           'bounding_box': {'width': 300, 'height': 400}}},
         'header_image_url': 'https://assets.genius.com/images/default_banner.png?1783019845',
         'human_readable_role_for_display': 'Contributor',
         'id': 6246835,
         'iq': 57390,
         'is_meme_verified': False,
         'is_verified': False,
         'login': 'gone_3pw37_867d',
         'name': 'gone_3pw37_867d',
         'role_for_display': 'contributor',
         'url': 'https://genius.com/gone_3pw37_867d',
         'current_user_metadata': {'permissions': [],
          'excluded_permissions': ['follow'],
          'interactions': {'following': False}}}}],
      'cosigned_by': [],
      'created_by': {'_type': 'user',
       'about_me_summary': '',
       'api_path': '/users/6246835',
       'avatar': {'tiny': {'url': 'https://assets.genius.com/images/default_cover_image.png?1783019845',
         'bounding_box': {'width': 16, 'height': 16}},
        'thumb': {'url': 'https://assets.genius.com/images/default_cover_image.png?1783019845',
         'bounding_box': {'width': 32, 'height': 32}},
        'small': {'url': 'https://assets.genius.com/images/default_cover_image.png?1783019845',
         'bounding_box': {'width': 100, 'height': 100}},
        'medium': {'url': 'https://assets.genius.com/images/default_cover_image.png?1783019845',
         'bounding_box': {'width': 300, 'height': 400}}},
       'header_image_url': 'https://assets.genius.com/images/default_banner.png?1783019845',
       'human_readable_role_for_display': 'Contributor',
       'id': 6246835,
       'iq': 57390,
       'is_meme_verified': False,
       'is_verified': False,
       'login': 'gone_3pw37_867d',
       'name': 'gone_3pw37_867d',
       'role_for_display': 'contributor',
       'url': 'https://genius.com/gone_3pw37_867d',
       'current_user_metadata': {'permissions': [],
        'excluded_permissions': ['follow'],
        'interactions': {'following': False}}},
      'rejection_comment': None,
      'top_comment': None,
      'verified_by': None}]}},
  {'_type': 'cover_art',
   'annotated': False,
   'api_path': '/albums/26866',
   'id': 242202,
   'image_url': 'https://images.genius.com/625a88f8d0d890ed7d18f127dcf9dfc9.600x290x1.jpg',

In [221]:
#Pandas dataframe columns

kinganimal_soundgarden_df = pd.DataFrame(columns=['track_title', 'track_lyrics', 'album_name', 'project_name', 'release_year', 'label'])

In [222]:
track_title = []

for track in kinganimal["tracks"]:
    track_title.append(track['song']['title'])

In [223]:
kinganimal_soundgarden_df['track_title'] = track_title

In [224]:
kinganimal_soundgarden_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Been Away Too Long,NaN,NaN,NaN,NaN,NaN
1,Non-State Actor,NaN,NaN,NaN,NaN,NaN
2,By Crooked Steps,NaN,NaN,NaN,NaN,NaN
3,A Thousand Days Before,NaN,NaN,NaN,NaN,NaN
4,Blood on the Valley Floor,NaN,NaN,NaN,NaN,NaN
5,Bones of Birds,NaN,NaN,NaN,NaN,NaN
6,Taree,NaN,NaN,NaN,NaN,NaN
7,Attrition,NaN,NaN,NaN,NaN,NaN
8,Black Saturday,NaN,NaN,NaN,NaN,NaN
9,Halfway There,NaN,NaN,NaN,NaN,NaN
10,Worse Dreams,NaN,NaN,NaN,NaN,NaN
11,Eyelid’s Mouth,NaN,NaN,NaN,NaN,NaN
12,Rowing,NaN,NaN,NaN,NaN,NaN

In [225]:
track_lyrics = []

for lyric in kinganimal["tracks"]:
    track_lyrics.append(lyric['song']['lyrics'])

In [226]:
kinganimal_soundgarden_df['track_lyrics'] = track_lyrics

In [227]:
kinganimal_soundgarden_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Been Away Too Long,"[Verse 1]\nYou can't go home, no, I swear you ...",NaN,NaN,NaN,NaN
1,Non-State Actor,"[Intro]\n1,2,3,4\n\nHeeey!\n\n[Verse 1]\nCoin ...",NaN,NaN,NaN,NaN
2,By Crooked Steps,I'm addicted to feeling\nStealing love isn't s...,NaN,NaN,NaN,NaN
3,A Thousand Days Before,"[Intro]\n\n[Verse 1]\nLife, a thousand days ag...",NaN,NaN,NaN,NaN
4,Blood on the Valley Floor,Yeah!\n[Chorus 1]\nMountains all around\nAltog...,NaN,NaN,NaN,NaN
5,Bones of Birds,"[Verse 1]\nTime is my friend\nTill it ain't, a...",NaN,NaN,NaN,NaN
6,Taree,"[Verse]\nThough I can't put my hands on you, I...",NaN,NaN,NaN,NaN
7,Attrition,[Verse]\nLay here under bombast and gloom\nPar...,NaN,NaN,NaN,NaN
8,Black Saturday,[Verse 1]\nPromise something\nKill me right aw...,NaN,NaN,NaN,NaN
9,Halfway There,[Verse 1]\nI woke up with my feet nailed down\...,NaN,NaN,NaN,NaN
10,Worse Dreams,[Verse 1]\nLet it swirl around you now and let...,NaN,NaN,NaN,NaN
11,Eyelid’s Mouth,[Verse 1]\nIn the eyelid's mouth\nOn the iris ...,NaN,NaN,NaN,NaN
12,Rowing,"[Chorus]\nDon't know where I'm going, I just k...",NaN,NaN,NaN,NaN

In [228]:
kinganimal_soundgarden_df['album_name']= kinganimal['name']

In [229]:
kinganimal_soundgarden_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Been Away Too Long,"[Verse 1]\nYou can't go home, no, I swear you ...",King Animal,NaN,NaN,NaN
1,Non-State Actor,"[Intro]\n1,2,3,4\n\nHeeey!\n\n[Verse 1]\nCoin ...",King Animal,NaN,NaN,NaN
2,By Crooked Steps,I'm addicted to feeling\nStealing love isn't s...,King Animal,NaN,NaN,NaN
3,A Thousand Days Before,"[Intro]\n\n[Verse 1]\nLife, a thousand days ag...",King Animal,NaN,NaN,NaN
4,Blood on the Valley Floor,Yeah!\n[Chorus 1]\nMountains all around\nAltog...,King Animal,NaN,NaN,NaN
5,Bones of Birds,"[Verse 1]\nTime is my friend\nTill it ain't, a...",King Animal,NaN,NaN,NaN
6,Taree,"[Verse]\nThough I can't put my hands on you, I...",King Animal,NaN,NaN,NaN
7,Attrition,[Verse]\nLay here under bombast and gloom\nPar...,King Animal,NaN,NaN,NaN
8,Black Saturday,[Verse 1]\nPromise something\nKill me right aw...,King Animal,NaN,NaN,NaN
9,Halfway There,[Verse 1]\nI woke up with my feet nailed down\...,King Animal,NaN,NaN,NaN
10,Worse Dreams,[Verse 1]\nLet it swirl around you now and let...,King Animal,NaN,NaN,NaN
11,Eyelid’s Mouth,[Verse 1]\nIn the eyelid's mouth\nOn the iris ...,King Animal,NaN,NaN,NaN
12,Rowing,"[Chorus]\nDon't know where I'm going, I just k...",King Animal,NaN,NaN,NaN

In [230]:
kinganimal_soundgarden_df['release_year']= kinganimal['release_date_components']['year']

In [231]:
kinganimal_soundgarden_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Been Away Too Long,"[Verse 1]\nYou can't go home, no, I swear you ...",King Animal,NaN,2012,NaN
1,Non-State Actor,"[Intro]\n1,2,3,4\n\nHeeey!\n\n[Verse 1]\nCoin ...",King Animal,NaN,2012,NaN
2,By Crooked Steps,I'm addicted to feeling\nStealing love isn't s...,King Animal,NaN,2012,NaN
3,A Thousand Days Before,"[Intro]\n\n[Verse 1]\nLife, a thousand days ag...",King Animal,NaN,2012,NaN
4,Blood on the Valley Floor,Yeah!\n[Chorus 1]\nMountains all around\nAltog...,King Animal,NaN,2012,NaN
5,Bones of Birds,"[Verse 1]\nTime is my friend\nTill it ain't, a...",King Animal,NaN,2012,NaN
6,Taree,"[Verse]\nThough I can't put my hands on you, I...",King Animal,NaN,2012,NaN
7,Attrition,[Verse]\nLay here under bombast and gloom\nPar...,King Animal,NaN,2012,NaN
8,Black Saturday,[Verse 1]\nPromise something\nKill me right aw...,King Animal,NaN,2012,NaN
9,Halfway There,[Verse 1]\nI woke up with my feet nailed down\...,King Animal,NaN,2012,NaN
10,Worse Dreams,[Verse 1]\nLet it swirl around you now and let...,King Animal,NaN,2012,NaN
11,Eyelid’s Mouth,[Verse 1]\nIn the eyelid's mouth\nOn the iris ...,King Animal,NaN,2012,NaN
12,Rowing,"[Chorus]\nDon't know where I'm going, I just k...",King Animal,NaN,2012,NaN

In [232]:
kinganimal_soundgarden_df['label']=kinganimal['song_performances'][14]['artists'][0]['name']

In [233]:
kinganimal_soundgarden_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Been Away Too Long,"[Verse 1]\nYou can't go home, no, I swear you ...",King Animal,NaN,2012,Loma Vista Recordings
1,Non-State Actor,"[Intro]\n1,2,3,4\n\nHeeey!\n\n[Verse 1]\nCoin ...",King Animal,NaN,2012,Loma Vista Recordings
2,By Crooked Steps,I'm addicted to feeling\nStealing love isn't s...,King Animal,NaN,2012,Loma Vista Recordings
3,A Thousand Days Before,"[Intro]\n\n[Verse 1]\nLife, a thousand days ag...",King Animal,NaN,2012,Loma Vista Recordings
4,Blood on the Valley Floor,Yeah!\n[Chorus 1]\nMountains all around\nAltog...,King Animal,NaN,2012,Loma Vista Recordings
5,Bones of Birds,"[Verse 1]\nTime is my friend\nTill it ain't, a...",King Animal,NaN,2012,Loma Vista Recordings
6,Taree,"[Verse]\nThough I can't put my hands on you, I...",King Animal,NaN,2012,Loma Vista Recordings
7,Attrition,[Verse]\nLay here under bombast and gloom\nPar...,King Animal,NaN,2012,Loma Vista Recordings
8,Black Saturday,[Verse 1]\nPromise something\nKill me right aw...,King Animal,NaN,2012,Loma Vista Recordings
9,Halfway There,[Verse 1]\nI woke up with my feet nailed down\...,King Animal,NaN,2012,Loma Vista Recordings
10,Worse Dreams,[Verse 1]\nLet it swirl around you now and let...,King Animal,NaN,2012,Loma Vista Recordings
11,Eyelid’s Mouth,[Verse 1]\nIn the eyelid's mouth\nOn the iris ...,King Animal,NaN,2012,Loma Vista Recordings
12,Rowing,"[Chorus]\nDon't know where I'm going, I just k...",King Animal,NaN,2012,Loma Vista Recordings

In [234]:
kinganimal_soundgarden_df['project_name']=kinganimal['primary_artist_names']

In [235]:
kinganimal_soundgarden_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Been Away Too Long,"[Verse 1]\nYou can't go home, no, I swear you ...",King Animal,Soundgarden,2012,Loma Vista Recordings
1,Non-State Actor,"[Intro]\n1,2,3,4\n\nHeeey!\n\n[Verse 1]\nCoin ...",King Animal,Soundgarden,2012,Loma Vista Recordings
2,By Crooked Steps,I'm addicted to feeling\nStealing love isn't s...,King Animal,Soundgarden,2012,Loma Vista Recordings
3,A Thousand Days Before,"[Intro]\n\n[Verse 1]\nLife, a thousand days ag...",King Animal,Soundgarden,2012,Loma Vista Recordings
4,Blood on the Valley Floor,Yeah!\n[Chorus 1]\nMountains all around\nAltog...,King Animal,Soundgarden,2012,Loma Vista Recordings
5,Bones of Birds,"[Verse 1]\nTime is my friend\nTill it ain't, a...",King Animal,Soundgarden,2012,Loma Vista Recordings
6,Taree,"[Verse]\nThough I can't put my hands on you, I...",King Animal,Soundgarden,2012,Loma Vista Recordings
7,Attrition,[Verse]\nLay here under bombast and gloom\nPar...,King Animal,Soundgarden,2012,Loma Vista Recordings
8,Black Saturday,[Verse 1]\nPromise something\nKill me right aw...,King Animal,Soundgarden,2012,Loma Vista Recordings
9,Halfway There,[Verse 1]\nI woke up with my feet nailed down\...,King Animal,Soundgarden,2012,Loma Vista Recordings
10,Worse Dreams,[Verse 1]\nLet it swirl around you now and let...,King Animal,Soundgarden,2012,Loma Vista Recordings
11,Eyelid’s Mouth,[Verse 1]\nIn the eyelid's mouth\nOn the iris ...,King Animal,Soundgarden,2012,Loma Vista Recordings
12,Rowing,"[Chorus]\nDon't know where I'm going, I just k...",King Animal,Soundgarden,2012,Loma Vista Recordings

In [236]:
kinganimal_soundgarden_df['project_name']=kinganimal['primary_artist_names']

In [237]:
album = genius.search_album("Audioslave", "Audioslave")

INFO lyricsgenius.genius: Searching for "Audioslave" by Audioslave...
DEBUG urllib3.connectionpool: Starting new HTTPS connection (5): genius.com:443
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/search/multi?q=Audioslave+Audioslave HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/albums/29022?text_format=plain HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/albums/29022/tracks?per_page=50&page=1&text_format=plain HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-cochise-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-show-me-how-to-live-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-gasoline-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-what-you-are-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-like-a-stone-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-set-it-off-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-shadow-on-the-sun-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-i-am-the-highway-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-exploder-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-hypnotize-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-bring-em-back-alive-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-light-my-way-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-getaway-car-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-the-last-remaining-light-lyrics HTTP/2.0" 200 None

In [238]:
album.save_lyrics()

DEBUG lyricsgenius.types.base: Wrote saved_album_lyrics_audioslave_audioslave.json.

In [248]:
with open('saved_album_lyrics_audioslave_audioslave.json') as audioslave:
    audioslave = json.load(audioslave)
audioslave

{'_type': 'album',
 'api_path': '/albums/29022',
 'cover_art_thumbnail_url': 'https://images.genius.com/4d5da2779962dbab926dfdf606897021.300x300x1.png',
 'cover_art_url': 'https://images.genius.com/4d5da2779962dbab926dfdf606897021.600x600x1.png',
 'full_title': 'Audioslave by Audioslave',
 'id': 29022,
 'name': 'Audioslave',
 'name_with_artist': 'Audioslave (artist: Audioslave)',
 'primary_artist_names': 'Audioslave',
 'pusher_channel': 'album-29022',
 'release_date_components': {'year': 2002, 'month': 11, 'day': 19},
 'release_date_for_display': 'November 19, 2002',
 'updated_at': 1775424897,
 'url': 'https://genius.com/albums/Audioslave/Audioslave',
 'current_user_metadata': {'permissions': ['create_comment'],
  'excluded_permissions': ['set_album_color_gradient',
   'edit',
   'destroy',
   'pyong',
   'lock',
   'super_lock',
   'unlock',
   'sort_songs',
   'hide',
   'unhide',
   'see_short_id',
   'create_additional_role',
   'create_question'],
  'interactions': {'pyong': False, 'following': False},
  'iq_by_action': {}},
 'artist': 'Audioslave',
 'primary_artists': [{'_type': 'artist',
   'api_path': '/artists/39547',
   'header_image_url': 'https://images.genius.com/2be4b9fd7771e0076adf9ebdb736c4a5.1000x661x1.jpg',
   'id': 39547,
   'image_url': 'https://images.genius.com/d4a74910ea377b65809166785e497735.1000x1000x1.jpg',
   'index_character': 'a',
   'is_meme_verified': False,
   'is_verified': False,
   'links_config': None,
   'name': 'Audioslave',
   'slug': 'Audioslave',
   'url': 'https://genius.com/artists/Audioslave'}],
 'album_type': 'album',
 'comment_count': 1,
 'custom_header_image_url': 'https://images.genius.com/3d9ac93e1508edce3bc33e40936e1fbe.804x460x1.png',
 'description_preview': 'Certified 3x Platinum by the RIAA, Audioslave is the debut studio album of the namesake band. Featuring the singles “Cochise,” “Like a Stone,” “Show Me How To Live,” “I am the Highway,” “What You Are,” and “Gasoline.” The album was even nominated for the Best Hard Rock Performance 2004 Grammy Award.\n\nMuch to the dismay of guitarist Tom Morello, the album was leaked to some file-sharing networks on May 16, 2002, months before the release of the album. Tom said that the songs were not in their finished form and that in some cases “they weren’t even the same lyrics, guitar solos, performances of any kind.” For an album which sold 162,000 copies in its first week, this truly was a disappointment.',
 'header_image_url': 'https://images.genius.com/3d9ac93e1508edce3bc33e40936e1fbe.804x460x1.png',
 'hidden': False,
 'language': None,
 'lock_state': 'editable',
 'pyongs_count': 3,
 'release_date': '2002-11-19',
 'tracking_paths': {'aggregate': '/albums/Audioslave/Audioslave',
  'concurrent': '/albums/Audioslave/Audioslave'},
 'viewable_by_roles': [],
 'album_art_primary_color': '#94aecf',
 'album_art_secondary_color': '#a4bcdc',
 'album_art_text_color': '#000',
 'song_pageviews': 2725543,
 'album_relationships': [{'_type': 'album_relationship',
   'relationship_type': 'deluxe_edition_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_deluxe_edition',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'alternate_version_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_alternate_version',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'reissue_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_reissue',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'remix_version_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_remix_version',
   'albums': []}],
 'cover_arts': [{'_type': 'cover_art',
   'annotated': False,
   'api_path': '/albums/29022',
   'id': 9864,
   'image_url': 'https://images.genius.com/4d5da2779962dbab926dfdf606897021.600x600x1.png',
   'thumbnail_image_url': 'https://images.genius.com/4d5da2779962dbab926dfdf606897021.300x300x1.png',
   'url': 'https://genius.com/album_cover_arts/9864',
   'current_user_metadata': {'permissions': [],
    'excluded_permissions': ['destroy']},
   'description_annotation': {'_type': 'referent',
    'annotator_id': 3461006,
    'annotator_login': 'Ataraxiac',
    'api_path': '/referents/15473835',
    'classification': 'needs_exegesis',
    'fragment': 'https://images.genius.com/4d5da2779962dbab926dfdf606897021.600x600x1.png',
    'id': 15473835,
    'ios_app_url': 'genius://referents/15473835',
    'is_description': True,
    'is_image': True,
    'path': '/15473835/Audioslave/Https-imagesgeniuscom-4d5da2779962dbab926dfdf606897021600x600x1png',
    'range': {'content': 'https://images.genius.com/4d5da2779962dbab926dfdf606897021.600x600x1.png'},
    'song_id': None,
    'url': 'https://genius.com/15473835/Audioslave/Https-imagesgeniuscom-4d5da2779962dbab926dfdf606897021600x600x1png',
    'verified_annotator_ids': [],
    'current_user_metadata': {'permissions': [],
     'excluded_permissions': ['add_pinned_annotation_to',
      'add_community_annotation_to'],
     'relationships': {}},
    'tracking_paths': {'aggregate': '/15473835/Audioslave/Https-imagesgeniuscom-4d5da2779962dbab926dfdf606897021600x600x1png',
     'concurrent': '/albums/Audioslave/Audioslave'},
    'twitter_share_message': '“?” —@Genius',
    'annotatable': {'_type': 'cover_art',
     'api_path': '/albums/29022',
     'context': 'Audioslave',
     'id': 9864,
     'image_url': 'https://images.genius.com/4d5da2779962dbab926dfdf606897021.300x300x1.png',
     'link_title': 'Audioslave',
     'title': 'Audioslave',
     'type': 'CoverArt',
     'url': 'https://genius.com/album_cover_arts/9864'},
    'annotations': [{'_type': 'annotation',
      'api_path': '/annotations/15473835',
      'being_created': False,
      'body': {'plain': ''},
      'comment_count': 0,
      'community': True,
      'created_at': 1538166745,
      'custom_preview': None,
      'deleted': False,
      'embed_content': "<blockquote class='rg_standalone_container' data-src='//genius.com/annotations/15473835/standalone_embed'><a href='https://genius.com/15473835/Audioslave/Https-imagesgeniuscom-4d5da2779962dbab926dfdf606897021600x600x1png'>https://images.genius.com/4d5da2779962dbab926dfdf606897021.600x600x1.png</a><br><a href='https://genius.com/album_cover_arts/9864'>&#8213; Audioslave</a></blockquote><script async crossorigin src='//genius.com/annotations/load_standalone_embeds.js'></script>",
      'has_voters': False,
      'id': 15473835,
      'needs_exegesis': True,
      'pinned': False,
      'proposed_edit_count': 0,
      'pyongs_count': None,
      'referent_id': 15473835,
      'share_url': 'https://genius.com/15473835',
      'source': None,
      'state': 'needs_exegesis',
      'twitter_share_message': '“?” —@Genius',
      'url': 'https://genius.com/15473835/Audioslave/Https-imagesgeniuscom-4d5da2779962dbab926dfdf606897021600x600x1png',
      'verified': False,
      'votes_total': 0,
      'current_user_metadata': {'permissions': [],
       'excluded_permissions': ['vote',
        'edit',
        'cosign',
        'uncosign',
        'destroy',
        'accept',
        'reject',
        'see_unreviewed',
        'clear_votes',
        'propose_edit_to',
        'pin_to_profile',
        'unpin_from_profile',
        'update_source',
        'edit_custom_preview',
        'report_as_abusive',
        'create_comment'],
       'interactions': {'cosign': False, 'pyong': False, 'vote': None},
       'iq_by_action': {}},
      'accepted_by': None,
      'authors': [{'_type': 'user_attribution',
        'attribution': 1.0,
        'pinned_role': None,
        'user': {'_type': 'user',
         'about_me_summary': 'Hi.',
         'api_path': '/users/3461006',
         'avatar': {'tiny': {'url': 'https://images.genius.com/avatars/tiny/deb31ee6c0ae9cd038249f8e2ff9a184',
           'bounding_box': {'width': 16, 'height': 16}},
          'thumb': {'url': 'https://images.genius.com/avatars/thumb/deb31ee6c0ae9cd038249f8e2ff9a184',
           'bounding_box': {'width': 32, 'height': 32}},
          'small': {'url': 'https://images.genius.com/avatars/small/deb31ee6c0ae9cd038249f8e2ff9a184',
           'bounding_box': {'width': 100, 'height': 100}},
          'medium': {'url': 'https://images.genius.com/avatars/medium/deb31ee6c0ae9cd038249f8e2ff9a184',
           'bounding_box': {'width': 300, 'height': 400}}},
         'header_image_url': 'https://filepicker-images.genius.com/ne0vf8f88n',
         'human_readable_role_for_display': 'Editor',
         'id': 3461006,
         'iq': 251743,
         'is_meme_verified': False,
         'is_verified': False,
         'login': 'Ataraxiac',
         'name': 'Ataraxiac',
         'role_for_display': 'editor',
         'url': 'https://genius.com/Ataraxiac',
         'current_user_metadata': {'permissions': [],
          'excluded_permissions': ['follow'],
          'interactions': {'following': False}}}}],
      'cosigned_by': [],
      'created_by': {'_type': 'user',
       'about_me_summary': 'Hi.',
       'api_path': '/users/3461006',
       'avatar': {'tiny': {'url': 'https://images.genius.com/avatars/tiny/deb31ee6c0ae9cd038249f8e2ff9a184',
         'bounding_box': {'width': 16, 'height': 16}},
        'thumb': {'url': 'https://images.genius.com/avatars/thumb/deb31ee6c0ae9cd038249f8e2ff9a184',
         'bounding_box': {'width': 32, 'height': 32}},
        'small': {'url': 'https://images.genius.com/avatars/small/deb31ee6c0ae9cd038249f8e2ff9a184',
         'bounding_box': {'width': 100, 'height': 100}},
        'medium': {'url': 'https://images.genius.com/avatars/medium/deb31ee6c0ae9cd038249f8e2ff9a184',
         'bounding_box': {'width': 300, 'height': 400}}},
       'header_image_url': 'https://filepicker-images.genius.com/ne0vf8f88n',
       'human_readable_role_for_display': 'Editor',
       'id': 3461006,
       'iq': 251743,
       'is_meme_verified': False,
       'is_verified': False,
       'login': 'Ataraxiac',
       'name': 'Ataraxiac',
       'role_for_display': 'editor',
       'url': 'https://genius.com/Ataraxiac',
       'current_user_metadata': {'permissions': [],
        'excluded_permissions': ['follow'],
        'interactions': {'following': False}}},
      'rejection_comment': None,
      'top_comment': None,
      'verified_by': None}]}},
  {'_type': 'cover_art',
   'annotated': False,
   'api_path': '/albums/29022',
   'id': 270955,
   'image_url': 'https://images.genius.com/5b271f2db52e8125150593a8eb82902d.591x591x1.jpg',
   'thumbnail_image_url': 'https://images.genius.com/5b271f2db52e8125150593a8eb82902d.300x300x1.jpg',
   'url': 'https://genius.com/album_cover_arts/270955',
   'current_user_metadata': {'permissions': [],
    'excluded_permissions': ['destroy']},
   'description_annotation': {'_type': 'referent',
    'annotator_id': 3461006,
    'annotator_login': 'Ataraxiac',
    'api_path': '/referents/15473840',
    'classification': 'needs_exegesis',
    'fragment': 'https://images.genius.com/5b271f2db52e8125150593a8eb82902d.591x591x1.jpg',
    'id': 15473840,
    'ios_app_url': 'genius://referents/15473840',
    'is_description': True,
    'is_image': True,
    'path': '/15473840/Audioslave/Https-imagesgeniuscom-5b271f2db52e8125150593a8eb82902d591x591x1jpg',
    'range': {'content': 'https://images.genius.com/5b271f2db52e8125150593a8eb82902d.591x591x1.jpg'},
    'song_id': None,
    'url': 'https://genius.com/15473840/Audioslave/Https-imagesgeniuscom-5b271f2db52e8125150593a8eb82902d591x591x1jpg',
    'verified_annotator_ids': [],
    'current_user_metadata': {'permissions': [],
     'excluded_permissions': ['add_pinned_annotation_to',
      'add_community_annotation_to'],
     'relationships': {}},
    'tracking_paths': {'aggregate': '/15473840/Audioslave/Https-imagesgeniuscom-5b271f2db52e8125150593a8eb82902d591x591x1jpg',
     'concurrent': '/albums/Audioslave/Audioslave'},
    'twitter_share_message': '“?” —@Genius',
    'annotatable': {'_type': 'cover_art',
     'api_path': '/albums/29022',
     'context': 'Audioslave',
     'id': 270955,
     'image_url': 'https://images.genius.com/5b271f2db52e8125150593a8eb82902d.300x300x1.jpg',
     'link_title': 'Audioslave',
     'title': 'Audioslave',
     'type': 'CoverArt',
     'url': 'https://genius.com/album_cover_arts/270955'},
    'annotations': [{'_type': 'annotation',
      'api_path': '/annotations/15473840',
      'being_created': False,
      'body': {'plain': ''},
      'comment_count': 0,
      'community': True,
      'created_at': 1538166777,
      'custom_preview': None,
      'deleted': False,
      'embed_content': "<blockquote class='rg_standalone_container' data-src='//genius.com/annotations/15473840/standalone_embed'><a href='https://genius.com/15473840/Audioslave/Https-imagesgeniuscom-5b271f2db52e8125150593a8eb82902d591x591x1jpg'>https://images.genius.com/5b271f2db52e8125150593a8eb82902d.591x591x1.jpg</a><br><a href='https://genius.com/album_cover_arts/270955'>&#8213; Audioslave</a></blockquote><script async crossorigin src='//genius.com/annotations/load_standalone_embeds.js'></script>",
      'has_voters': False,
      'id': 15473840,
      'needs_exegesis': True,
      'pinned': False,
      'proposed_edit_count': 0,
      'pyongs_count': None,
      'referent_id': 15473840,
      'share_url': 'https://genius.com/15473840',
      'source': None,
      'state': 'needs_exegesis',
      'twitter_share_message': '“?” —@Genius',
      'url': 'https://genius.com/15473840/Audioslave/Https-imagesgeniuscom-5b271f2db52e8125150593a8eb82902d591x591x1jpg',
      'verified': False,
      'votes_total': 0,
      'current_user_metadata': {'permissions': [],
       'excluded_permissions': ['vote',
        'edit',
        'cosign',
        'uncosign',
        'destroy',
        'accept',
        'reject',
        'see_unreviewed',
        'clear_votes',
        'propose_edit_to',
        'pin_to_profile',
        'unpin_from_profile',
        'update_source',
        'edit_custom_preview',
        'report_as_abusive',
        'create_comment'],
       'interactions': {'cosign': False, 'pyong': False, 'vote': None},
       'iq_by_action': {}},
      'accepted_by': None,
      'authors': [{'_type': 'user_attribution',
        'attribution': 1.0,
        'pinned_role': None,
        'user': {'_type': 'user',
         'about_me_summary': 'Hi.',
         'api_path': '/users/3461006',
         'avatar': {'tiny': {'url': 'https://images.genius.com/avatars/tiny/deb31ee6c0ae9cd038249f8e2ff9a184',
           'bounding_box': {'width': 16, 'height': 16}},
          'thumb': {'url': 'https://images.genius.com/avatars/thumb/deb31ee6c0ae9cd038249f8e2ff9a184',
           'bounding_box': {'width': 32, 'height': 32}},
          'small': {'url': 'https://images.genius.com/avatars/small/deb31ee6c0ae9cd038249f8e2ff9a184',
           'bounding_box': {'width': 100, 'height': 100}},
          'medium': {'url': 'https://images.genius.com/avatars/medium/deb31ee6c0ae9cd038249f8e2ff9a184',
           'bounding_box': {'width': 300, 'height': 400}}},
         'header_image_url': 'https://filepicker-images.genius.com/ne0vf8f88n',
         'human_readable_role_for_display': 'Editor',
         'id': 3461006,
         'iq': 251743,
         'is_meme_verified': False,
         'is_verified': False,
         'login': 'Ataraxiac',
         'name': 'Ataraxiac',
         'role_for_display': 'editor',
         'url': 'https://genius.com/Ataraxiac',
         'current_user_metadata': {'permissions': [],
          'excluded_permissions': ['follow'],
          'interactions': {'following': False}}}}],
      'cosigned_by': [],
      'created_by': {'_type': 'user',
       'about_me_summary': 'Hi.',
       'api_path': '/users/3461006',
       'avatar': {'tiny': {'url': 'https://images.genius.com/avatars/tiny/deb31ee6c0ae9cd038249f8e2ff9a184',
         'bounding_box': {'width': 16, 'height': 16}},
        'thumb': {'url': 'https://images.genius.com/avatars/thumb/deb31ee6c0ae9cd038249f8e2ff9a184',
         'bounding_box': {'width': 32, 'height': 32}},
        'small': {'url': 'https://images.genius.com/avatars/small/deb31ee6c0ae9cd038249f8e2ff9a184',
         'bounding_box': {'width': 100, 'height': 100}},
        'medium': {'url': 'https://images.genius.com/avatars/medium/deb31ee6c0ae9cd038249f8e2ff9a184',
         'bounding_box': {'width': 300, 'height': 400}}},
       'header_image_url': 'https://filepicker-images.genius.com/ne0vf8f88n',
       'human_readable_role_for_display': 'Editor',
       'id': 3461006,
       'iq': 251743,
       'is_meme_verified': False,
       'is_verified': False,
       'login': 'Ataraxiac',
       'name': 'Ataraxiac',
       'role_for_display': 'editor',
       'url': 'https://genius.com/Ataraxiac',
       'current_user_metadata': {'permissions': [],
        'excluded_permissions': ['follow'],
        'interactions': {'following': False}}},
      'rejection_comment': None,
      'top_comment': None,
      'verified_by': None}]}},
  {'_type': 'cover_art',
   'annotated': False,
   'api_path': '/albums/29022',
   'id': 855985,
   'image_url': 'https://images.genius.com/c5731375493b0db561141e817a8bd148.594x594x1.jpg',
   'thumbnail_image_url': 'https://images.genius.com/c5731375493b0db561141e817a8bd148.300x300x1.jpg',
   'url': 'https://genius.com/album_cover_arts/855985',
   'current_user_metadata': {'permissions': [],
    'excluded_permissions': ['destroy']},
   'description_annotation': {'_type': 'referent',
    'annotator_id': 5218691,
    'annotator_login': 'cheddarblaster',
    'api_path': '/referents/26522472',
    'classification': 'needs_exegesis',
    'fragment': 'https://images.genius.com/c5731375493b0db561141e817a8bd148.594x594x1.jpg',
    'id': 26522472,
    'ios_app_url': 'genius://referents/26522472',
    'is_description': True,
    'is_image': True,
    'path': '/26522472/Audioslave/Https-imagesgeniuscom-c5731375493b0db561141e817a8bd148594x594x1jpg',
    'range': {'content': 'https://images.genius.com/c5731375493b0db561141e817a8bd148.594x594x1.jpg'},
    'song_id': None,
    'url': 'https://genius.com/26522472/Audioslave/Https-imagesgeniuscom-c5731375493b0db561141e817a8bd148594x594x1jpg',
    'verified_annotator_ids': [],
    'current_user_metadata': {'permissions': [],
     'excluded_permissions': ['add_pinned_annotation_to',
      'add_community_annotation_to'],
     'relationships': {}},
    'tracking_paths': {'aggregate': '/26522472/Audioslave/Https-imagesgeniuscom-c5731375493b0db561141e817a8bd148594x594x1jpg',
     'concurrent': '/albums/Audioslave/Audioslave'},
    'twitter_share_message': '“?” —@Genius',
    'annotatable': {'_type': 'cover_art',
     'api_path': '/albums/29022',
     'context': 'Audioslave',
     'id': 855985,
     'image_url': 'https://images.genius.com/c5731375493b0db561141e817a8bd148.300x300x1.jpg',
     'link_title': 'Audioslave',
     'title': 'Audioslave',
     'type': 'CoverArt',
     'url': 'https://genius.com/album_cover_arts/855985'},
    'annotations': [{'_type': 'annotation',
      'api_path': '/annotations/26522472',
      'being_created': False,
      'body': {'plain': ''},
      'comment_count': 0,
      'community': True,
      'created_at': 1660835063,
      'custom_preview': None,
      'deleted': False,
      'embed_content': "<blockquote class='rg_standalone_container' data-src='//genius.com/annotations/26522472/standalone_embed'><a href='https://genius.com/26522472/Audioslave/Https-imagesgeniuscom-c5731375493b0db561141e817a8bd148594x594x1jpg'>https://images.genius.com/c5731375493b0db561141e817a8bd148.594x594x1.jpg</a><br><a href='https://genius.com/album_cover_arts/855985'>&#8213; Audioslave</a></blockquote><script async crossorigin src='//genius.com/annotations/load_standalone_embeds.js'></script>",
      'has_voters': False,
      'id': 26522472,
      'needs_exegesis': True,
      'pinned': False,
      'proposed_edit_count': 0,

In [249]:
#Pandas dataframe columns

audioslave_audioslave_df = pd.DataFrame(columns=['track_title', 'track_lyrics', 'album_name', 'project_name', 'release_year', 'label'])

In [255]:
track_title = []

for track in audioslave["tracks"]:
    track_title.append(track['song']['title'])

In [256]:
audioslave_audioslave_df['track_title'] = track_title

In [257]:
audioslave_audioslave_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Cochise,NaN,NaN,NaN,NaN,NaN
1,Show Me How to Live,NaN,NaN,NaN,NaN,NaN
2,Gasoline,NaN,NaN,NaN,NaN,NaN
3,What You Are,NaN,NaN,NaN,NaN,NaN
4,Like a Stone,NaN,NaN,NaN,NaN,NaN
5,Set It Off,NaN,NaN,NaN,NaN,NaN
6,Shadow on the Sun,NaN,NaN,NaN,NaN,NaN
7,I Am the Highway,NaN,NaN,NaN,NaN,NaN
8,Exploder,NaN,NaN,NaN,NaN,NaN
9,Hypnotize,NaN,NaN,NaN,NaN,NaN
10,Bring ’Em Back Alive,NaN,NaN,NaN,NaN,NaN
11,Light My Way,NaN,NaN,NaN,NaN,NaN
12,Getaway Car,NaN,NaN,NaN,NaN,NaN
13,The Last Remaining Light,NaN,NaN,NaN,NaN,NaN

In [258]:
track_lyrics = []

for lyric in audioslave["tracks"]:
    track_lyrics.append(lyric['song']['lyrics'])

In [259]:
audioslave_audioslave_df['track_lyrics'] = track_lyrics

In [260]:
audioslave_audioslave_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Cochise,"[Verse 1]\nWell, I've been watching while you'...",NaN,NaN,NaN,NaN
1,Show Me How to Live,[Verse 1]\nAnd with the early dawn moving righ...,NaN,NaN,NaN,NaN
2,Gasoline,[Verse 1]\nHouse is haunted\nI just want to go...,NaN,NaN,NaN,NaN
3,What You Are,"[Verse 1]\nAnd when you wanted me, I came to y...",NaN,NaN,NaN,NaN
4,Like a Stone,[Verse 1]\nOn a cobweb afternoon in a room ful...,NaN,NaN,NaN,NaN
5,Set It Off,"[Verse 1]\nHe was standing at the rock, gather...",NaN,NaN,NaN,NaN
6,Shadow on the Sun,[Verse 1]\nOnce upon a time\nI was of the mind...,NaN,NaN,NaN,NaN
7,I Am the Highway,[Verse 1]\nPearls and swine\nBereft of me\nLon...,NaN,NaN,NaN,NaN
8,Exploder,[Verse 1]\nI met a man locked away for things ...,NaN,NaN,NaN,NaN
9,Hypnotize,"[Verse 1]\nWell, if you set your mind upon it,...",NaN,NaN,NaN,NaN
10,Bring ’Em Back Alive,[Intro]\nOh-ooh\nOh-ooh\nOh-ooh\nOh-ah\n\n[Ver...,NaN,NaN,NaN,NaN
11,Light My Way,[Verse 1]\nIn my hour of need\nOn a sea of gra...,NaN,NaN,NaN,NaN
12,Getaway Car,[Verse 1]\nThe first time I saw you\nYou were ...,NaN,NaN,NaN,NaN
13,The Last Remaining Light,[Verse 1]\nRoll me on your frozen fields\nBrea...,NaN,NaN,NaN,NaN

In [261]:
audioslave_audioslave_df['album_name']= audioslave['name']

In [262]:
audioslave_audioslave_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Cochise,"[Verse 1]\nWell, I've been watching while you'...",Audioslave,NaN,NaN,NaN
1,Show Me How to Live,[Verse 1]\nAnd with the early dawn moving righ...,Audioslave,NaN,NaN,NaN
2,Gasoline,[Verse 1]\nHouse is haunted\nI just want to go...,Audioslave,NaN,NaN,NaN
3,What You Are,"[Verse 1]\nAnd when you wanted me, I came to y...",Audioslave,NaN,NaN,NaN
4,Like a Stone,[Verse 1]\nOn a cobweb afternoon in a room ful...,Audioslave,NaN,NaN,NaN
5,Set It Off,"[Verse 1]\nHe was standing at the rock, gather...",Audioslave,NaN,NaN,NaN
6,Shadow on the Sun,[Verse 1]\nOnce upon a time\nI was of the mind...,Audioslave,NaN,NaN,NaN
7,I Am the Highway,[Verse 1]\nPearls and swine\nBereft of me\nLon...,Audioslave,NaN,NaN,NaN
8,Exploder,[Verse 1]\nI met a man locked away for things ...,Audioslave,NaN,NaN,NaN
9,Hypnotize,"[Verse 1]\nWell, if you set your mind upon it,...",Audioslave,NaN,NaN,NaN
10,Bring ’Em Back Alive,[Intro]\nOh-ooh\nOh-ooh\nOh-ooh\nOh-ah\n\n[Ver...,Audioslave,NaN,NaN,NaN
11,Light My Way,[Verse 1]\nIn my hour of need\nOn a sea of gra...,Audioslave,NaN,NaN,NaN
12,Getaway Car,[Verse 1]\nThe first time I saw you\nYou were ...,Audioslave,NaN,NaN,NaN
13,The Last Remaining Light,[Verse 1]\nRoll me on your frozen fields\nBrea...,Audioslave,NaN,NaN,NaN

In [263]:
audioslave_audioslave_df['release_year']= audioslave['release_date_components']['year']

In [264]:
audioslave_audioslave_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Cochise,"[Verse 1]\nWell, I've been watching while you'...",Audioslave,NaN,2002,NaN
1,Show Me How to Live,[Verse 1]\nAnd with the early dawn moving righ...,Audioslave,NaN,2002,NaN
2,Gasoline,[Verse 1]\nHouse is haunted\nI just want to go...,Audioslave,NaN,2002,NaN
3,What You Are,"[Verse 1]\nAnd when you wanted me, I came to y...",Audioslave,NaN,2002,NaN
4,Like a Stone,[Verse 1]\nOn a cobweb afternoon in a room ful...,Audioslave,NaN,2002,NaN
5,Set It Off,"[Verse 1]\nHe was standing at the rock, gather...",Audioslave,NaN,2002,NaN
6,Shadow on the Sun,[Verse 1]\nOnce upon a time\nI was of the mind...,Audioslave,NaN,2002,NaN
7,I Am the Highway,[Verse 1]\nPearls and swine\nBereft of me\nLon...,Audioslave,NaN,2002,NaN
8,Exploder,[Verse 1]\nI met a man locked away for things ...,Audioslave,NaN,2002,NaN
9,Hypnotize,"[Verse 1]\nWell, if you set your mind upon it,...",Audioslave,NaN,2002,NaN
10,Bring ’Em Back Alive,[Intro]\nOh-ooh\nOh-ooh\nOh-ooh\nOh-ah\n\n[Ver...,Audioslave,NaN,2002,NaN
11,Light My Way,[Verse 1]\nIn my hour of need\nOn a sea of gra...,Audioslave,NaN,2002,NaN
12,Getaway Car,[Verse 1]\nThe first time I saw you\nYou were ...,Audioslave,NaN,2002,NaN
13,The Last Remaining Light,[Verse 1]\nRoll me on your frozen fields\nBrea...,Audioslave,NaN,2002,NaN

In [280]:
label_one = audioslave['song_performances'][13]['artists'][0]['name']
label_two = audioslave['song_performances'][13]['artists'][1]['name']
labels = [label_one, label_two]

In [282]:
audioslave_audioslave_df['label']=[labels] * len(audioslave_audioslave_df)

In [284]:
audioslave_audioslave_df['project_name']=audioslave['primary_artist_names']

In [286]:
album = genius.search_album("Revelations", "Audioslave")

INFO lyricsgenius.genius: Searching for "Revelations" by Audioslave...
DEBUG urllib3.connectionpool: Starting new HTTPS connection (6): genius.com:443
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/search/multi?q=Revelations+Audioslave HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/albums/106650?text_format=plain HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/albums/106650/tracks?per_page=50&page=1&text_format=plain HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-revelations-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-one-and-the-same-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-sound-of-a-gun-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-until-we-fall-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-original-fire-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-broken-city-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-somedays-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-shape-of-things-to-come-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-jewel-of-the-summertime-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-wide-awake-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-nothing-left-to-say-but-goodbye-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Audioslave-moth-lyrics HTTP/2.0" 200 None

In [287]:
album.save_lyrics()

DEBUG lyricsgenius.types.base: Wrote saved_album_lyrics_audioslave_revelations.json.

In [288]:
with open('saved_album_lyrics_audioslave_revelations.json') as revelations:
    revelations = json.load(revelations)
revelations

{'_type': 'album',
 'api_path': '/albums/106650',
 'cover_art_thumbnail_url': 'https://images.genius.com/1caff1eb4072266856eda80d64004ff8.300x300x1.png',
 'cover_art_url': 'https://images.genius.com/1caff1eb4072266856eda80d64004ff8.1000x1000x1.png',
 'full_title': 'Revelations by Audioslave',
 'id': 106650,
 'name': 'Revelations',
 'name_with_artist': 'Revelations (artist: Audioslave)',
 'primary_artist_names': 'Audioslave',
 'pusher_channel': 'album-106650',
 'release_date_components': {'year': 2006, 'month': 9, 'day': 4},
 'release_date_for_display': 'September 4, 2006',
 'updated_at': 1758068944,
 'url': 'https://genius.com/albums/Audioslave/Revelations',
 'current_user_metadata': {'permissions': ['create_comment'],
  'excluded_permissions': ['set_album_color_gradient',
   'edit',
   'destroy',
   'pyong',
   'lock',
   'super_lock',
   'unlock',
   'sort_songs',
   'hide',
   'unhide',
   'see_short_id',
   'create_additional_role',
   'create_question'],
  'interactions': {'pyong': False, 'following': False},
  'iq_by_action': {}},
 'artist': 'Audioslave',
 'primary_artists': [{'_type': 'artist',
   'api_path': '/artists/39547',
   'header_image_url': 'https://images.genius.com/2be4b9fd7771e0076adf9ebdb736c4a5.1000x661x1.jpg',
   'id': 39547,
   'image_url': 'https://images.genius.com/d4a74910ea377b65809166785e497735.1000x1000x1.jpg',
   'index_character': 'a',
   'is_meme_verified': False,
   'is_verified': False,
   'links_config': None,
   'name': 'Audioslave',
   'slug': 'Audioslave',
   'url': 'https://genius.com/artists/Audioslave'}],
 'album_type': 'album',
 'comment_count': 0,
 'custom_header_image_url': 'https://images.genius.com/2f691f1dbdc04596ee42454d0533feb5.890x890x1.jpg',
 'description_preview': '',
 'header_image_url': 'https://images.genius.com/2f691f1dbdc04596ee42454d0533feb5.890x890x1.jpg',
 'hidden': False,
 'language': None,
 'lock_state': 'editable',
 'pyongs_count': 1,
 'release_date': '2006-09-04',
 'tracking_paths': {'aggregate': '/albums/Audioslave/Revelations',
  'concurrent': '/albums/Audioslave/Revelations'},
 'viewable_by_roles': [],
 'album_art_primary_color': '#93c3cc',
 'album_art_secondary_color': '#e4f4ed',
 'album_art_text_color': '#000',
 'song_pageviews': 127527,
 'album_relationships': [{'_type': 'album_relationship',
   'relationship_type': 'deluxe_edition_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_deluxe_edition',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'alternate_version_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_alternate_version',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'reissue_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_reissue',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'remix_version_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_remix_version',
   'albums': []}],
 'cover_arts': [{'_type': 'cover_art',
   'annotated': False,
   'api_path': '/albums/106650',
   'id': 1446611,
   'image_url': 'https://images.genius.com/1caff1eb4072266856eda80d64004ff8.1000x1000x1.png',
   'thumbnail_image_url': 'https://images.genius.com/1caff1eb4072266856eda80d64004ff8.300x300x1.png',
   'url': 'https://genius.com/album_cover_arts/1446611',
   'current_user_metadata': {'permissions': [],
    'excluded_permissions': ['destroy']},
   'description_annotation': {'_type': 'referent',
    'annotator_id': 21983215,
    'annotator_login': 'ventex9254',
    'api_path': '/referents/36943519',
    'classification': 'needs_exegesis',
    'fragment': 'https://images.genius.com/1caff1eb4072266856eda80d64004ff8.1000x1000x1.png',
    'id': 36943519,
    'ios_app_url': 'genius://referents/36943519',
    'is_description': True,
    'is_image': True,
    'path': '/36943519/Revelations/Https-imagesgeniuscom-1caff1eb4072266856eda80d64004ff81000x1000x1png',
    'range': {'content': 'https://images.genius.com/1caff1eb4072266856eda80d64004ff8.1000x1000x1.png'},
    'song_id': None,
    'url': 'https://genius.com/36943519/Revelations/Https-imagesgeniuscom-1caff1eb4072266856eda80d64004ff81000x1000x1png',
    'verified_annotator_ids': [],
    'current_user_metadata': {'permissions': [],
     'excluded_permissions': ['add_pinned_annotation_to',
      'add_community_annotation_to'],
     'relationships': {}},
    'tracking_paths': {'aggregate': '/36943519/Revelations/Https-imagesgeniuscom-1caff1eb4072266856eda80d64004ff81000x1000x1png',
     'concurrent': '/albums/Audioslave/Revelations'},
    'twitter_share_message': '“?” —@Genius',
    'annotatable': {'_type': 'cover_art',
     'api_path': '/albums/106650',
     'context': 'Audioslave',
     'id': 1446611,
     'image_url': 'https://images.genius.com/1caff1eb4072266856eda80d64004ff8.300x300x1.png',
     'link_title': 'Revelations',
     'title': 'Revelations',
     'type': 'CoverArt',
     'url': 'https://genius.com/album_cover_arts/1446611'},
    'annotations': [{'_type': 'annotation',
      'api_path': '/annotations/36943519',
      'being_created': False,
      'body': {'plain': ''},
      'comment_count': 0,
      'community': True,
      'created_at': 1758068922,
      'custom_preview': None,
      'deleted': False,
      'embed_content': "<blockquote class='rg_standalone_container' data-src='//genius.com/annotations/36943519/standalone_embed'><a href='https://genius.com/36943519/Revelations/Https-imagesgeniuscom-1caff1eb4072266856eda80d64004ff81000x1000x1png'>https://images.genius.com/1caff1eb4072266856eda80d64004ff8.1000x1000x1.png</a><br><a href='https://genius.com/album_cover_arts/1446611'>&#8213; Revelations</a></blockquote><script async crossorigin src='//genius.com/annotations/load_standalone_embeds.js'></script>",
      'has_voters': False,
      'id': 36943519,
      'needs_exegesis': True,
      'pinned': False,
      'proposed_edit_count': 0,
      'pyongs_count': None,
      'referent_id': 36943519,
      'share_url': 'https://genius.com/36943519',
      'source': None,
      'state': 'needs_exegesis',
      'twitter_share_message': '“?” —@Genius',
      'url': 'https://genius.com/36943519/Revelations/Https-imagesgeniuscom-1caff1eb4072266856eda80d64004ff81000x1000x1png',
      'verified': False,
      'votes_total': 0,
      'current_user_metadata': {'permissions': [],
       'excluded_permissions': ['vote',
        'edit',
        'cosign',
        'uncosign',
        'destroy',
        'accept',
        'reject',
        'see_unreviewed',
        'clear_votes',
        'propose_edit_to',
        'pin_to_profile',
        'unpin_from_profile',
        'update_source',
        'edit_custom_preview',
        'report_as_abusive',
        'create_comment'],
       'interactions': {'cosign': False, 'pyong': False, 'vote': None},
       'iq_by_action': {}},
      'accepted_by': None,
      'authors': [{'_type': 'user_attribution',
        'attribution': 1.0,
        'pinned_role': None,
        'user': {'_type': 'user',
         'about_me_summary': 'sup guys. you guys will mostly find me in the rap and rock part of genius.\n\n5k iq – 6/12/24\n10k iq – 6/30/24\n20k iq – 12/18/24\n30k iq – 8/7/25',
         'api_path': '/users/21983215',
         'avatar': {'tiny': {'url': 'https://filepicker-images.genius.com/1meizecpoa',
           'bounding_box': {'width': 16, 'height': 16}},
          'thumb': {'url': 'https://filepicker-images.genius.com/1meizecpoa',
           'bounding_box': {'width': 32, 'height': 32}},
          'small': {'url': 'https://filepicker-images.genius.com/1meizecpoa',
           'bounding_box': {'width': 100, 'height': 100}},
          'medium': {'url': 'https://filepicker-images.genius.com/1meizecpoa',
           'bounding_box': {'width': 300, 'height': 400}}},
         'header_image_url': 'https://filepicker-images.genius.com/7f187c566e0df2f5fe5c18518f51edb647ae55b1921f202ebae1ba38ed4400be%2Fnbrqi2nfa6',
         'human_readable_role_for_display': 'Contributor',
         'id': 21983215,
         'iq': 31177,
         'is_meme_verified': False,
         'is_verified': False,
         'login': 'ventex9254',
         'name': 'ventex9254',
         'role_for_display': 'contributor',
         'url': 'https://genius.com/ventex9254',
         'current_user_metadata': {'permissions': [],
          'excluded_permissions': ['follow'],
          'interactions': {'following': False}}}}],
      'cosigned_by': [],
      'created_by': {'_type': 'user',
       'about_me_summary': 'sup guys. you guys will mostly find me in the rap and rock part of genius.\n\n5k iq – 6/12/24\n10k iq – 6/30/24\n20k iq – 12/18/24\n30k iq – 8/7/25',
       'api_path': '/users/21983215',
       'avatar': {'tiny': {'url': 'https://filepicker-images.genius.com/1meizecpoa',
         'bounding_box': {'width': 16, 'height': 16}},
        'thumb': {'url': 'https://filepicker-images.genius.com/1meizecpoa',
         'bounding_box': {'width': 32, 'height': 32}},
        'small': {'url': 'https://filepicker-images.genius.com/1meizecpoa',
         'bounding_box': {'width': 100, 'height': 100}},
        'medium': {'url': 'https://filepicker-images.genius.com/1meizecpoa',
         'bounding_box': {'width': 300, 'height': 400}}},
       'header_image_url': 'https://filepicker-images.genius.com/7f187c566e0df2f5fe5c18518f51edb647ae55b1921f202ebae1ba38ed4400be%2Fnbrqi2nfa6',
       'human_readable_role_for_display': 'Contributor',
       'id': 21983215,
       'iq': 31177,
       'is_meme_verified': False,
       'is_verified': False,
       'login': 'ventex9254',
       'name': 'ventex9254',
       'role_for_display': 'contributor',
       'url': 'https://genius.com/ventex9254',
       'current_user_metadata': {'permissions': [],
        'excluded_permissions': ['follow'],
        'interactions': {'following': False}}},
      'rejection_comment': None,
      'top_comment': None,
      'verified_by': None}]}},
  {'_type': 'cover_art',
   'annotated': False,
   'api_path': '/albums/106650',
   'id': 271876,
   'image_url': 'https://images.genius.com/4947ed13797a22b1930754be25361ae1.600x600x1.jpg',
   'thumbnail_image_url': 'https://images.genius.com/4947ed13797a22b1930754be25361ae1.300x300x1.jpg',
   'url': 'https://genius.com/album_cover_arts/271876',
   'current_user_metadata': {'permissions': [],
    'excluded_permissions': ['destroy']},
   'description_annotation': {'_type': 'referent',
    'annotator_id': 3461006,
    'annotator_login': 'Ataraxiac',
    'api_path': '/referents/15492138',
    'classification': 'needs_exegesis',
    'fragment': 'https://images.genius.com/4947ed13797a22b1930754be25361ae1.600x600x1.jpg',
    'id': 15492138,
    'ios_app_url': 'genius://referents/15492138',
    'is_description': True,
    'is_image': True,
    'path': '/15492138/Revelations/Https-imagesgeniuscom-4947ed13797a22b1930754be25361ae1600x600x1jpg',
    'range': {'content': 'https://images.genius.com/4947ed13797a22b1930754be25361ae1.600x600x1.jpg'},
    'song_id': None,
    'url': 'https://genius.com/15492138/Revelations/Https-imagesgeniuscom-4947ed13797a22b1930754be25361ae1600x600x1jpg',
    'verified_annotator_ids': [],
    'current_user_metadata': {'permissions': [],
     'excluded_permissions': ['add_pinned_annotation_to',
      'add_community_annotation_to'],
     'relationships': {}},
    'tracking_paths': {'aggregate': '/15492138/Revelations/Https-imagesgeniuscom-4947ed13797a22b1930754be25361ae1600x600x1jpg',
     'concurrent': '/albums/Audioslave/Revelations'},
    'twitter_share_message': '“?” —@Genius',
    'annotatable': {'_type': 'cover_art',
     'api_path': '/albums/106650',
     'context': 'Audioslave',
     'id': 271876,
     'image_url': 'https://images.genius.com/4947ed13797a22b1930754be25361ae1.300x300x1.jpg',
     'link_title': 'Revelations',
     'title': 'Revelations',
     'type': 'CoverArt',
     'url': 'https://genius.com/album_cover_arts/271876'},
    'annotations': [{'_type': 'annotation',
      'api_path': '/annotations/15492138',
      'being_created': False,
      'body': {'plain': ''},
      'comment_count': 0,
      'community': True,
      'created_at': 1538414223,
      'custom_preview': None,
      'deleted': False,
      'embed_content': "<blockquote class='rg_standalone_container' data-src='//genius.com/annotations/15492138/standalone_embed'><a href='https://genius.com/15492138/Revelations/Https-imagesgeniuscom-4947ed13797a22b1930754be25361ae1600x600x1jpg'>https://images.genius.com/4947ed13797a22b1930754be25361ae1.600x600x1.jpg</a><br><a href='https://genius.com/album_cover_arts/271876'>&#8213; Revelations</a></blockquote><script async crossorigin src='//genius.com/annotations/load_standalone_embeds.js'></script>",
      'has_voters': False,
      'id': 15492138,
      'needs_exegesis': True,
      'pinned': False,
      'proposed_edit_count': 0,
      'pyongs_count': None,
      'referent_id': 15492138,
      'share_url': 'https://genius.com/15492138',
      'source': None,
      'state': 'needs_exegesis',
      'twitter_share_message': '“?” —@Genius',
      'url': 'https://genius.com/15492138/Revelations/Https-imagesgeniuscom-4947ed13797a22b1930754be25361ae1600x600x1jpg',
      'verified': False,
      'votes_total': 0,
      'current_user_metadata': {'permissions': [],
       'excluded_permissions': ['vote',
        'edit',
        'cosign',
        'uncosign',
        'destroy',
        'accept',
        'reject',
        'see_unreviewed',
        'clear_votes',
        'propose_edit_to',
        'pin_to_profile',
        'unpin_from_profile',
        'update_source',
        'edit_custom_preview',
        'report_as_abusive',
        'create_comment'],
       'interactions': {'cosign': False, 'pyong': False, 'vote': None},
       'iq_by_action': {}},
      'accepted_by': None,
      'authors': [{'_type': 'user_attribution',
        'attribution': 1.0,
        'pinned_role': None,
        'user': {'_type': 'user',
         'about_me_summary': 'Hi.',
         'api_path': '/users/3461006',
         'avatar': {'tiny': {'url': 'https://images.genius.com/avatars/tiny/deb31ee6c0ae9cd038249f8e2ff9a184',
           'bounding_box': {'width': 16, 'height': 16}},
          'thumb': {'url': 'https://images.genius.com/avatars/thumb/deb31ee6c0ae9cd038249f8e2ff9a184',
           'bounding_box': {'width': 32, 'height': 32}},
          'small': {'url': 'https://images.genius.com/avatars/small/deb31ee6c0ae9cd038249f8e2ff9a184',
           'bounding_box': {'width': 100, 'height': 100}},
          'medium': {'url': 'https://images.genius.com/avatars/medium/deb31ee6c0ae9cd038249f8e2ff9a184',
           'bounding_box': {'width': 300, 'height': 400}}},
         'header_image_url': 'https://filepicker-images.genius.com/ne0vf8f88n',
         'human_readable_role_for_display': 'Editor',
         'id': 3461006,
         'iq': 251743,
         'is_meme_verified': False,
         'is_verified': False,
         'login': 'Ataraxiac',
         'name': 'Ataraxiac',
         'role_for_display': 'editor',
         'url': 'https://genius.com/Ataraxiac',
         'current_user_metadata': {'permissions': [],
          'excluded_permissions': ['follow'],
          'interactions': {'following': False}}}}],
      'cosigned_by': [],
      'created_by': {'_type': 'user',
       'about_me_summary': 'Hi.',
       'api_path': '/users/3461006',
       'avatar': {'tiny': {'url': 'https://images.genius.com/avatars/tiny/deb31ee6c0ae9cd038249f8e2ff9a184',
         'bounding_box': {'width': 16, 'height': 16}},
        'thumb': {'url': 'https://images.genius.com/avatars/thumb/deb31ee6c0ae9cd038249f8e2ff9a184',
         'bounding_box': {'width': 32, 'height': 32}},
        'small': {'url': 'https://images.genius.com/avatars/small/deb31ee6c0ae9cd038249f8e2ff9a184',
         'bounding_box': {'width': 100, 'height': 100}},
        'medium': {'url': 'https://images.genius.com/avatars/medium/deb31ee6c0ae9cd038249f8e2ff9a184',
         'bounding_box': {'width': 300, 'height': 400}}},
       'header_image_url': 'https://filepicker-images.genius.com/ne0vf8f88n',
       'human_readable_role_for_display': 'Editor',
       'id': 3461006,
       'iq': 251743,
       'is_meme_verified': False,
       'is_verified': False,
       'login': 'Ataraxiac',
       'name': 'Ataraxiac',
       'role_for_display': 'editor',
       'url': 'https://genius.com/Ataraxiac',
       'current_user_metadata': {'permissions': [],
        'excluded_permissions': ['follow'],
        'interactions': {'following': False}}},
      'rejection_comment': None,
      'top_comment': None,
      'verified_by': None}]}},
  {'_type': 'cover_art',
   'annotated': False,
   'api_path': '/albums/106650',
   'id': 271877,
   'image_url': 'https://images.genius.com/e03dda1960878a0b57947a1c6051c985.599x599x1.jpg',
   'thumbnail_image_url': 'https://images.genius.com/e03dda1960878a0b57947a1c6051c985.300x300x1.jpg',
   'url': 'https://genius.com/album_cover_arts/271877',
   'current_user_metadata': {'permissions': [],
    'excluded_permissions': ['destroy']},
   'description_annotation': {'_type': 'referent',
    'annotator_id': 3461006,
    'annotator_login': 'Ataraxiac',
    'api_path': '/referents/15492141',
    'classification': 'needs_exegesis',
    'fragment': 'https://images.genius.com/e03dda1960878a0b57947a1c6051c985.599x599x1.jpg',
    'id': 15492141,
    'ios_app_url': 'genius://referents/15492141',
    'is_description': True,
    'is_image': True,
    'path': '/15492141/Revelations/Https-imagesgeniuscom-e03dda1960878a0b57947a1c6051c985599x599x1jpg',
    'range': {'content': 'https://images.genius.com/e03dda1960878a0b57947a1c6051c985.599x599x1.jpg'},
    'song_id': None,
    'url': 'https://genius.com/15492141/Revelations/Https-imagesgeniuscom-e03dda1960878a0b57947a1c6051c985599x599x1jpg',
    'verified_annotator_ids': [],
    'current_user_metadata': {'permissions': [],
     'excluded_permissions': ['add_pinned_annotation_to',
      'add_community_annotation_to'],
     'relationships': {}},
    'tracking_paths': {'aggregate': '/15492141/Revelations/Https-imagesgeniuscom-e03dda1960878a0b57947a1c6051c985599x599x1jpg',
     'concurrent': '/albums/Audioslave/Revelations'},
    'twitter_share_message': '“?” —@Genius',
    'annotatable': {'_type': 'cover_art',
     'api_path': '/albums/106650',
     'context': 'Audioslave',
     'id': 271877,
     'image_url': 'https://images.genius.com/e03dda1960878a0b57947a1c6051c985.300x300x1.jpg',
     'link_title': 'Revelations',
     'title': 'Revelations',
     'type': 'CoverArt',
     'url': 'https://genius.com/album_cover_arts/271877'},
    'annotations': [{'_type': 'annotation',
      'api_path': '/annotations/15492141',
      'being_created': False,
      'body': {'plain': ''},
      'comment_count': 0,
      'community': True,
      'created_at': 1538414238,
      'custom_preview': None,
      'deleted': False,
      'embed_content': "<blockquote class='rg_standalone_container' data-src='//genius.com/annotations/15492141/standalone_embed'><a href='https://genius.com/15492141/Revelations/Https-imagesgeniuscom-e03dda1960878a0b57947a1c6051c985599x599x1jpg'>https://images.genius.com/e03dda1960878a0b57947a1c6051c985.599x599x1.jpg</a><br><a href='https://genius.com/album_cover_arts/271877'>&#8213; Revelations</a></blockquote><script async crossorigin src='//genius.com/annotations/load_standalone_embeds.js'></script>",
      'has_voters': False,
      'id': 15492141,
      'needs_exegesis': True,
      'pinned': False,
      'proposed_edit_count': 0,
      'pyongs_count': None,
      'referent_id': 15492141,
      'share_url': 'https://genius.com/15492141',
      'source': None,
      'state': 'needs_exegesis',
      'twitter_share_message': '“?” —@Genius',
      'url': 'https://genius.com/15492141/Revelations/Https-imagesgeniuscom-e03dda1960878a0b57947a1c6051c985599x599x1jpg',
      'verified': False,
      'votes_total': 0,

In [289]:
#Pandas dataframe columns

revelations_audioslave_df = pd.DataFrame(columns=['track_title', 'track_lyrics', 'album_name', 'project_name', 'release_year', 'label'])

In [290]:
track_title = []

for track in revelations["tracks"]:
    track_title.append(track['song']['title'])

In [291]:
revelations_audioslave_df['track_title'] = track_title

In [292]:
revelations_audioslave_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Revelations,NaN,NaN,NaN,NaN,NaN
1,One and the Same,NaN,NaN,NaN,NaN,NaN
2,Sound of a Gun,NaN,NaN,NaN,NaN,NaN
3,Until We Fall,NaN,NaN,NaN,NaN,NaN
4,Original Fire,NaN,NaN,NaN,NaN,NaN
5,Broken City,NaN,NaN,NaN,NaN,NaN
6,Somedays,NaN,NaN,NaN,NaN,NaN
7,Shape of Things to Come,NaN,NaN,NaN,NaN,NaN
8,Jewel of the Summertime,NaN,NaN,NaN,NaN,NaN
9,Wide Awake,NaN,NaN,NaN,NaN,NaN
10,Nothing Left to Say But Goodbye,NaN,NaN,NaN,NaN,NaN
11,Moth,NaN,NaN,NaN,NaN,NaN

In [293]:
track_lyrics = []

for lyric in revelations["tracks"]:
    track_lyrics.append(lyric['song']['lyrics'])

In [294]:
revelations_audioslave_df['track_lyrics'] = track_lyrics

In [295]:
revelations_audioslave_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Revelations,"[Verse 1]\nYou know what to do, you know what ...",NaN,NaN,NaN,NaN
1,One and the Same,"[Verse 1]\nWell, they don't hate you, you know...",NaN,NaN,NaN,NaN
2,Sound of a Gun,[Verse 1]\nIn the here and now I wait\nDown am...,NaN,NaN,NaN,NaN
3,Until We Fall,[Verse 1]\nI walk the streets without regret\n...,NaN,NaN,NaN,NaN
4,Original Fire,[Chorus]\nThe original fire has died and gone ...,NaN,NaN,NaN,NaN
5,Broken City,[Verse 1]\nMy city sleeps by the side of a fre...,NaN,NaN,NaN,NaN
6,Somedays,"[Intro]\nSomedays, somedays\nSomedays just ain...",NaN,NaN,NaN,NaN
7,Shape of Things to Come,"[Verse 1]\nWell, it's late in the hour\nAnd a ...",NaN,NaN,NaN,NaN
8,Jewel of the Summertime,[Verse 1]\nWhen I was 18\nI didn't know pain w...,NaN,NaN,NaN,NaN
9,Wide Awake,[Verse 1]\nYou can look a hurricane right in t...,NaN,NaN,NaN,NaN
10,Nothing Left to Say But Goodbye,[Verse 1]\nJust like a rescue of a stray dog i...,NaN,NaN,NaN,NaN
11,Moth,"[Verse 1]\nThought I was different, it seems I...",NaN,NaN,NaN,NaN

In [296]:
revelations_audioslave_df['album_name']= revelations['name']

In [297]:
revelations_audioslave_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Revelations,"[Verse 1]\nYou know what to do, you know what ...",Revelations,NaN,NaN,NaN
1,One and the Same,"[Verse 1]\nWell, they don't hate you, you know...",Revelations,NaN,NaN,NaN
2,Sound of a Gun,[Verse 1]\nIn the here and now I wait\nDown am...,Revelations,NaN,NaN,NaN
3,Until We Fall,[Verse 1]\nI walk the streets without regret\n...,Revelations,NaN,NaN,NaN
4,Original Fire,[Chorus]\nThe original fire has died and gone ...,Revelations,NaN,NaN,NaN
5,Broken City,[Verse 1]\nMy city sleeps by the side of a fre...,Revelations,NaN,NaN,NaN
6,Somedays,"[Intro]\nSomedays, somedays\nSomedays just ain...",Revelations,NaN,NaN,NaN
7,Shape of Things to Come,"[Verse 1]\nWell, it's late in the hour\nAnd a ...",Revelations,NaN,NaN,NaN
8,Jewel of the Summertime,[Verse 1]\nWhen I was 18\nI didn't know pain w...,Revelations,NaN,NaN,NaN
9,Wide Awake,[Verse 1]\nYou can look a hurricane right in t...,Revelations,NaN,NaN,NaN
10,Nothing Left to Say But Goodbye,[Verse 1]\nJust like a rescue of a stray dog i...,Revelations,NaN,NaN,NaN
11,Moth,"[Verse 1]\nThought I was different, it seems I...",Revelations,NaN,NaN,NaN

In [298]:
revelations_audioslave_df['release_year']= revelations['release_date_components']['year']

In [299]:
revelations_audioslave_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Revelations,"[Verse 1]\nYou know what to do, you know what ...",Revelations,NaN,2006,NaN
1,One and the Same,"[Verse 1]\nWell, they don't hate you, you know...",Revelations,NaN,2006,NaN
2,Sound of a Gun,[Verse 1]\nIn the here and now I wait\nDown am...,Revelations,NaN,2006,NaN
3,Until We Fall,[Verse 1]\nI walk the streets without regret\n...,Revelations,NaN,2006,NaN
4,Original Fire,[Chorus]\nThe original fire has died and gone ...,Revelations,NaN,2006,NaN
5,Broken City,[Verse 1]\nMy city sleeps by the side of a fre...,Revelations,NaN,2006,NaN
6,Somedays,"[Intro]\nSomedays, somedays\nSomedays just ain...",Revelations,NaN,2006,NaN
7,Shape of Things to Come,"[Verse 1]\nWell, it's late in the hour\nAnd a ...",Revelations,NaN,2006,NaN
8,Jewel of the Summertime,[Verse 1]\nWhen I was 18\nI didn't know pain w...,Revelations,NaN,2006,NaN
9,Wide Awake,[Verse 1]\nYou can look a hurricane right in t...,Revelations,NaN,2006,NaN
10,Nothing Left to Say But Goodbye,[Verse 1]\nJust like a rescue of a stray dog i...,Revelations,NaN,2006,NaN
11,Moth,"[Verse 1]\nThought I was different, it seems I...",Revelations,NaN,2006,NaN

In [310]:
label_one = 'Epic'
label_two = 'Interscope'
labels = [label_one, label_two]

revelations_audioslave_df['label']=[labels] * len(revelations_audioslave_df)

In [311]:
revelations_audioslave_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Revelations,"[Verse 1]\nYou know what to do, you know what ...",Revelations,Audioslave,2006,"[Epic, Interscope]"
1,One and the Same,"[Verse 1]\nWell, they don't hate you, you know...",Revelations,Audioslave,2006,"[Epic, Interscope]"
2,Sound of a Gun,[Verse 1]\nIn the here and now I wait\nDown am...,Revelations,Audioslave,2006,"[Epic, Interscope]"
3,Until We Fall,[Verse 1]\nI walk the streets without regret\n...,Revelations,Audioslave,2006,"[Epic, Interscope]"
4,Original Fire,[Chorus]\nThe original fire has died and gone ...,Revelations,Audioslave,2006,"[Epic, Interscope]"
5,Broken City,[Verse 1]\nMy city sleeps by the side of a fre...,Revelations,Audioslave,2006,"[Epic, Interscope]"
6,Somedays,"[Intro]\nSomedays, somedays\nSomedays just ain...",Revelations,Audioslave,2006,"[Epic, Interscope]"
7,Shape of Things to Come,"[Verse 1]\nWell, it's late in the hour\nAnd a ...",Revelations,Audioslave,2006,"[Epic, Interscope]"
8,Jewel of the Summertime,[Verse 1]\nWhen I was 18\nI didn't know pain w...,Revelations,Audioslave,2006,"[Epic, Interscope]"
9,Wide Awake,[Verse 1]\nYou can look a hurricane right in t...,Revelations,Audioslave,2006,"[Epic, Interscope]"
10,Nothing Left to Say But Goodbye,[Verse 1]\nJust like a rescue of a stray dog i...,Revelations,Audioslave,2006,"[Epic, Interscope]"
11,Moth,"[Verse 1]\nThought I was different, it seems I...",Revelations,Audioslave,2006,"[Epic, Interscope]"

In [312]:
revelations_audioslave_df['project_name']=revelations['primary_artist_names']

In [313]:
revelations_audioslave_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Revelations,"[Verse 1]\nYou know what to do, you know what ...",Revelations,Audioslave,2006,"[Epic, Interscope]"
1,One and the Same,"[Verse 1]\nWell, they don't hate you, you know...",Revelations,Audioslave,2006,"[Epic, Interscope]"
2,Sound of a Gun,[Verse 1]\nIn the here and now I wait\nDown am...,Revelations,Audioslave,2006,"[Epic, Interscope]"
3,Until We Fall,[Verse 1]\nI walk the streets without regret\n...,Revelations,Audioslave,2006,"[Epic, Interscope]"
4,Original Fire,[Chorus]\nThe original fire has died and gone ...,Revelations,Audioslave,2006,"[Epic, Interscope]"
5,Broken City,[Verse 1]\nMy city sleeps by the side of a fre...,Revelations,Audioslave,2006,"[Epic, Interscope]"
6,Somedays,"[Intro]\nSomedays, somedays\nSomedays just ain...",Revelations,Audioslave,2006,"[Epic, Interscope]"
7,Shape of Things to Come,"[Verse 1]\nWell, it's late in the hour\nAnd a ...",Revelations,Audioslave,2006,"[Epic, Interscope]"
8,Jewel of the Summertime,[Verse 1]\nWhen I was 18\nI didn't know pain w...,Revelations,Audioslave,2006,"[Epic, Interscope]"
9,Wide Awake,[Verse 1]\nYou can look a hurricane right in t...,Revelations,Audioslave,2006,"[Epic, Interscope]"
10,Nothing Left to Say But Goodbye,[Verse 1]\nJust like a rescue of a stray dog i...,Revelations,Audioslave,2006,"[Epic, Interscope]"
11,Moth,"[Verse 1]\nThought I was different, it seems I...",Revelations,Audioslave,2006,"[Epic, Interscope]"

In [314]:
album = genius.search_album("Temple of the Dog", "Temple of the Dog")

INFO lyricsgenius.genius: Searching for "Temple of the Dog" by Temple of the Dog...
DEBUG urllib3.connectionpool: Starting new HTTPS connection (7): genius.com:443
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/search/multi?q=Temple+of+the+Dog+Temple+of+the+Dog HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/albums/40578?text_format=plain HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /api/albums/40578/tracks?per_page=50&page=1&text_format=plain HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Temple-of-the-dog-say-hello-2-heaven-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Temple-of-the-dog-reach-down-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Temple-of-the-dog-hunger-strike-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Temple-of-the-dog-pushin-forward-back-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Temple-of-the-dog-call-me-a-dog-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Temple-of-the-dog-times-of-trouble-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Temple-of-the-dog-wooden-jesus-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Temple-of-the-dog-your-saviour-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Temple-of-the-dog-four-walled-world-lyrics HTTP/2.0" 200 None
DEBUG urllib3.connectionpool: https://genius.com:443 "GET /Temple-of-the-dog-all-night-thing-lyrics HTTP/2.0" 200 None

In [315]:
album.save_lyrics()

DEBUG lyricsgenius.types.base: Wrote saved_album_lyrics_temple_of_the_dog_temple_of_the_dog.json.

In [316]:
with open('saved_album_lyrics_temple_of_the_dog_temple_of_the_dog.json') as dog:
    dog = json.load(dog)
dog

{'_type': 'album',
 'api_path': '/albums/40578',
 'cover_art_thumbnail_url': 'https://images.genius.com/4a83194947f418b659d748ae33eb8e91.300x300x1.jpg',
 'cover_art_url': 'https://images.genius.com/4a83194947f418b659d748ae33eb8e91.600x600x1.jpg',
 'full_title': 'Temple of the Dog by Temple of the Dog',
 'id': 40578,
 'name': 'Temple of the Dog',
 'name_with_artist': 'Temple of the Dog (artist: Temple of the Dog)',
 'primary_artist_names': 'Temple of the Dog',
 'pusher_channel': 'album-40578',
 'release_date_components': {'year': 1991, 'month': 4, 'day': 16},
 'release_date_for_display': 'April 16, 1991',
 'updated_at': 1758323356,
 'url': 'https://genius.com/albums/Temple-of-the-dog/Temple-of-the-dog',
 'current_user_metadata': {'permissions': ['create_comment'],
  'excluded_permissions': ['set_album_color_gradient',
   'edit',
   'destroy',
   'pyong',
   'lock',
   'super_lock',
   'unlock',
   'sort_songs',
   'hide',
   'unhide',
   'see_short_id',
   'create_additional_role',
   'create_question'],
  'interactions': {'pyong': False, 'following': False},
  'iq_by_action': {}},
 'artist': 'Temple of the Dog',
 'primary_artists': [{'_type': 'artist',
   'api_path': '/artists/62664',
   'header_image_url': 'https://images.genius.com/25ec393742445b2ee7fc4e45c22e45f7.1000x667x1.jpg',
   'id': 62664,
   'image_url': 'https://images.genius.com/ec49e6f8e2557a21c1ceb9c584813135.765x765x1.jpg',
   'index_character': 't',
   'is_meme_verified': False,
   'is_verified': False,
   'links_config': None,
   'name': 'Temple of the Dog',
   'slug': 'Temple-of-the-dog',
   'url': 'https://genius.com/artists/Temple-of-the-dog'}],
 'album_type': 'album',
 'comment_count': 0,
 'custom_header_image_url': None,
 'description_preview': 'This album is the only studio album by supergroup Temple of the Dog, released on April 16, 1991.  The album is a tribute to Andrew Wood, the former lead singer of Mother Love Bone, who died on March 19, 1990 of a heroin overdose. The songs were written by Soundgarden frontman Chris Cornell, Wood’s former friend and roommate, and count with Soundgarden drummer Matt Cameron, Wood’s band mates Jeff Ament and Stone Gossard, and two guys who together with the last two would form Pearl Jam, Eddie Vedder and  Mike McCready.',
 'header_image_url': 'https://images.genius.com/4a83194947f418b659d748ae33eb8e91.600x600x1.jpg',
 'hidden': False,
 'language': None,
 'lock_state': 'editable',
 'pyongs_count': 0,
 'release_date': '1991-04-16',
 'tracking_paths': {'aggregate': '/albums/Temple-of-the-dog/Temple-of-the-dog',
  'concurrent': '/albums/Temple-of-the-dog/Temple-of-the-dog'},
 'viewable_by_roles': [],
 'album_art_primary_color': '#aea043',
 'album_art_secondary_color': '#f0f2dd',
 'album_art_text_color': '#000',
 'song_pageviews': 467435,
 'album_relationships': [{'_type': 'album_relationship',
   'relationship_type': 'deluxe_edition_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_deluxe_edition',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'alternate_version_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_alternate_version',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'reissue_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_reissue',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'remix_version_of',
   'albums': []},
  {'_type': 'album_relationship',
   'relationship_type': 'has_remix_version',
   'albums': []}],
 'cover_arts': [{'_type': 'cover_art',
   'annotated': False,
   'api_path': '/albums/40578',
   'id': 1446679,
   'image_url': 'https://images.genius.com/4a83194947f418b659d748ae33eb8e91.600x600x1.jpg',
   'thumbnail_image_url': 'https://images.genius.com/4a83194947f418b659d748ae33eb8e91.300x300x1.jpg',
   'url': 'https://genius.com/album_cover_arts/1446679',
   'current_user_metadata': {'permissions': [],
    'excluded_permissions': ['destroy']},
   'description_annotation': {'_type': 'referent',
    'annotator_id': 21983215,
    'annotator_login': 'ventex9254',
    'api_path': '/referents/36944800',
    'classification': 'needs_exegesis',
    'fragment': 'https://images.genius.com/4a83194947f418b659d748ae33eb8e91.600x600x1.jpg',
    'id': 36944800,
    'ios_app_url': 'genius://referents/36944800',
    'is_description': True,
    'is_image': True,
    'path': '/36944800/Temple-of-the-dog/Https-imagesgeniuscom-4a83194947f418b659d748ae33eb8e91600x600x1jpg',
    'range': {'content': 'https://images.genius.com/4a83194947f418b659d748ae33eb8e91.600x600x1.jpg'},
    'song_id': None,
    'url': 'https://genius.com/36944800/Temple-of-the-dog/Https-imagesgeniuscom-4a83194947f418b659d748ae33eb8e91600x600x1jpg',
    'verified_annotator_ids': [],
    'current_user_metadata': {'permissions': [],
     'excluded_permissions': ['add_pinned_annotation_to',
      'add_community_annotation_to'],
     'relationships': {}},
    'tracking_paths': {'aggregate': '/36944800/Temple-of-the-dog/Https-imagesgeniuscom-4a83194947f418b659d748ae33eb8e91600x600x1jpg',
     'concurrent': '/albums/Temple-of-the-dog/Temple-of-the-dog'},
    'twitter_share_message': '“?” —@Genius',
    'annotatable': {'_type': 'cover_art',
     'api_path': '/albums/40578',
     'context': 'Temple of the Dog',
     'id': 1446679,
     'image_url': 'https://images.genius.com/4a83194947f418b659d748ae33eb8e91.300x300x1.jpg',
     'link_title': 'Temple of the Dog',
     'title': 'Temple of the Dog',
     'type': 'CoverArt',
     'url': 'https://genius.com/album_cover_arts/1446679'},
    'annotations': [{'_type': 'annotation',
      'api_path': '/annotations/36944800',
      'being_created': False,
      'body': {'plain': ''},
      'comment_count': 0,
      'community': True,
      'created_at': 1758085464,
      'custom_preview': None,
      'deleted': False,
      'embed_content': "<blockquote class='rg_standalone_container' data-src='//genius.com/annotations/36944800/standalone_embed'><a href='https://genius.com/36944800/Temple-of-the-dog/Https-imagesgeniuscom-4a83194947f418b659d748ae33eb8e91600x600x1jpg'>https://images.genius.com/4a83194947f418b659d748ae33eb8e91.600x600x1.jpg</a><br><a href='https://genius.com/album_cover_arts/1446679'>&#8213; Temple of the Dog</a></blockquote><script async crossorigin src='//genius.com/annotations/load_standalone_embeds.js'></script>",
      'has_voters': False,
      'id': 36944800,
      'needs_exegesis': True,
      'pinned': False,
      'proposed_edit_count': 0,
      'pyongs_count': None,
      'referent_id': 36944800,
      'share_url': 'https://genius.com/36944800',
      'source': None,
      'state': 'needs_exegesis',
      'twitter_share_message': '“?” —@Genius',
      'url': 'https://genius.com/36944800/Temple-of-the-dog/Https-imagesgeniuscom-4a83194947f418b659d748ae33eb8e91600x600x1jpg',
      'verified': False,
      'votes_total': 0,
      'current_user_metadata': {'permissions': [],
       'excluded_permissions': ['vote',
        'edit',
        'cosign',
        'uncosign',
        'destroy',
        'accept',
        'reject',
        'see_unreviewed',
        'clear_votes',
        'propose_edit_to',
        'pin_to_profile',
        'unpin_from_profile',
        'update_source',
        'edit_custom_preview',
        'report_as_abusive',
        'create_comment'],
       'interactions': {'cosign': False, 'pyong': False, 'vote': None},
       'iq_by_action': {}},
      'accepted_by': None,
      'authors': [{'_type': 'user_attribution',
        'attribution': 1.0,
        'pinned_role': None,
        'user': {'_type': 'user',
         'about_me_summary': 'sup guys. you guys will mostly find me in the rap and rock part of genius.\n\n5k iq – 6/12/24\n10k iq – 6/30/24\n20k iq – 12/18/24\n30k iq – 8/7/25',
         'api_path': '/users/21983215',
         'avatar': {'tiny': {'url': 'https://filepicker-images.genius.com/1meizecpoa',
           'bounding_box': {'width': 16, 'height': 16}},
          'thumb': {'url': 'https://filepicker-images.genius.com/1meizecpoa',
           'bounding_box': {'width': 32, 'height': 32}},
          'small': {'url': 'https://filepicker-images.genius.com/1meizecpoa',
           'bounding_box': {'width': 100, 'height': 100}},
          'medium': {'url': 'https://filepicker-images.genius.com/1meizecpoa',
           'bounding_box': {'width': 300, 'height': 400}}},
         'header_image_url': 'https://filepicker-images.genius.com/7f187c566e0df2f5fe5c18518f51edb647ae55b1921f202ebae1ba38ed4400be%2Fnbrqi2nfa6',
         'human_readable_role_for_display': 'Contributor',
         'id': 21983215,
         'iq': 31177,
         'is_meme_verified': False,
         'is_verified': False,
         'login': 'ventex9254',
         'name': 'ventex9254',
         'role_for_display': 'contributor',
         'url': 'https://genius.com/ventex9254',
         'current_user_metadata': {'permissions': [],
          'excluded_permissions': ['follow'],
          'interactions': {'following': False}}}}],
      'cosigned_by': [],
      'created_by': {'_type': 'user',
       'about_me_summary': 'sup guys. you guys will mostly find me in the rap and rock part of genius.\n\n5k iq – 6/12/24\n10k iq – 6/30/24\n20k iq – 12/18/24\n30k iq – 8/7/25',
       'api_path': '/users/21983215',
       'avatar': {'tiny': {'url': 'https://filepicker-images.genius.com/1meizecpoa',
         'bounding_box': {'width': 16, 'height': 16}},
        'thumb': {'url': 'https://filepicker-images.genius.com/1meizecpoa',
         'bounding_box': {'width': 32, 'height': 32}},
        'small': {'url': 'https://filepicker-images.genius.com/1meizecpoa',
         'bounding_box': {'width': 100, 'height': 100}},
        'medium': {'url': 'https://filepicker-images.genius.com/1meizecpoa',
         'bounding_box': {'width': 300, 'height': 400}}},
       'header_image_url': 'https://filepicker-images.genius.com/7f187c566e0df2f5fe5c18518f51edb647ae55b1921f202ebae1ba38ed4400be%2Fnbrqi2nfa6',
       'human_readable_role_for_display': 'Contributor',
       'id': 21983215,
       'iq': 31177,
       'is_meme_verified': False,
       'is_verified': False,
       'login': 'ventex9254',
       'name': 'ventex9254',
       'role_for_display': 'contributor',
       'url': 'https://genius.com/ventex9254',
       'current_user_metadata': {'permissions': [],
        'excluded_permissions': ['follow'],
        'interactions': {'following': False}}},
      'rejection_comment': None,
      'top_comment': None,
      'verified_by': None}]}},
  {'_type': 'cover_art',
   'annotated': False,
   'api_path': '/albums/40578',
   'id': 1133734,
   'image_url': 'https://images.genius.com/f16c740652bdf536f428af51e896b41f.600x467x1.jpg',
   'thumbnail_image_url': 'https://images.genius.com/f16c740652bdf536f428af51e896b41f.300x234x1.jpg',
   'url': 'https://genius.com/album_cover_arts/1133734',
   'current_user_metadata': {'permissions': [],
    'excluded_permissions': ['destroy']},
   'description_annotation': {'_type': 'referent',
    'annotator_id': 19737663,
    'annotator_login': 'su11engir1',
    'api_path': '/referents/31438647',
    'classification': 'needs_exegesis',
    'fragment': 'https://images.genius.com/f16c740652bdf536f428af51e896b41f.600x467x1.jpg',
    'id': 31438647,
    'ios_app_url': 'genius://referents/31438647',
    'is_description': True,
    'is_image': True,
    'path': '/31438647/Temple-of-the-dog/Https-imagesgeniuscom-f16c740652bdf536f428af51e896b41f600x467x1jpg',
    'range': {'content': 'https://images.genius.com/f16c740652bdf536f428af51e896b41f.600x467x1.jpg'},
    'song_id': None,
    'url': 'https://genius.com/31438647/Temple-of-the-dog/Https-imagesgeniuscom-f16c740652bdf536f428af51e896b41f600x467x1jpg',
    'verified_annotator_ids': [],
    'current_user_metadata': {'permissions': [],
     'excluded_permissions': ['add_pinned_annotation_to',
      'add_community_annotation_to'],
     'relationships': {}},
    'tracking_paths': {'aggregate': '/31438647/Temple-of-the-dog/Https-imagesgeniuscom-f16c740652bdf536f428af51e896b41f600x467x1jpg',
     'concurrent': '/albums/Temple-of-the-dog/Temple-of-the-dog'},
    'twitter_share_message': '“?” —@Genius',
    'annotatable': {'_type': 'cover_art',
     'api_path': '/albums/40578',
     'context': 'Temple of the Dog',
     'id': 1133734,
     'image_url': 'https://images.genius.com/f16c740652bdf536f428af51e896b41f.300x234x1.jpg',
     'link_title': 'Temple of the Dog',
     'title': 'Temple of the Dog',
     'type': 'CoverArt',
     'url': 'https://genius.com/album_cover_arts/1133734'},
    'annotations': [{'_type': 'annotation',
      'api_path': '/annotations/31438647',
      'being_created': False,
      'body': {'plain': ''},
      'comment_count': 0,
      'community': True,
      'created_at': 1713115390,
      'custom_preview': None,
      'deleted': False,
      'embed_content': "<blockquote class='rg_standalone_container' data-src='//genius.com/annotations/31438647/standalone_embed'><a href='https://genius.com/31438647/Temple-of-the-dog/Https-imagesgeniuscom-f16c740652bdf536f428af51e896b41f600x467x1jpg'>https://images.genius.com/f16c740652bdf536f428af51e896b41f.600x467x1.jpg</a><br><a href='https://genius.com/album_cover_arts/1133734'>&#8213; Temple of the Dog</a></blockquote><script async crossorigin src='//genius.com/annotations/load_standalone_embeds.js'></script>",
      'has_voters': False,
      'id': 31438647,
      'needs_exegesis': True,
      'pinned': False,
      'proposed_edit_count': 0,
      'pyongs_count': None,
      'referent_id': 31438647,
      'share_url': 'https://genius.com/31438647',
      'source': None,
      'state': 'needs_exegesis',
      'twitter_share_message': '“?” —@Genius',
      'url': 'https://genius.com/31438647/Temple-of-the-dog/Https-imagesgeniuscom-f16c740652bdf536f428af51e896b41f600x467x1jpg',
      'verified': False,
      'votes_total': 0,
      'current_user_metadata': {'permissions': [],
       'excluded_permissions': ['vote',
        'edit',
        'cosign',
        'uncosign',
        'destroy',
        'accept',
        'reject',
        'see_unreviewed',
        'clear_votes',
        'propose_edit_to',
        'pin_to_profile',
        'unpin_from_profile',
        'update_source',
        'edit_custom_preview',
        'report_as_abusive',
        'create_comment'],
       'interactions': {'cosign': False, 'pyong': False, 'vote': None},
       'iq_by_action': {}},
      'accepted_by': None,
      'authors': [{'_type': 'user_attribution',
        'attribution': 1.0,
        'pinned_role': None,
        'user': {'_type': 'user',
         'about_me_summary': 'Jesus died for somebody’s sins but not mine.\n\nLover of all things music, especially grunge, punk, 70s glam rock, folk, new wave, and anything female fronted.\n\nDMs are open if you have any questions or would like to say something to me.',
         'api_path': '/users/19737663',
         'avatar': {'tiny': {'url': 'https://images.genius.com/avatars/tiny/c38818b528fe039e11c8c7ec54ef107d',
           'bounding_box': {'width': 16, 'height': 16}},
          'thumb': {'url': 'https://images.genius.com/avatars/thumb/c38818b528fe039e11c8c7ec54ef107d',
           'bounding_box': {'width': 32, 'height': 32}},
          'small': {'url': 'https://images.genius.com/avatars/small/c38818b528fe039e11c8c7ec54ef107d',
           'bounding_box': {'width': 100, 'height': 100}},
          'medium': {'url': 'https://images.genius.com/avatars/medium/c38818b528fe039e11c8c7ec54ef107d',
           'bounding_box': {'width': 300, 'height': 400}}},
         'header_image_url': 'https://assets.genius.com/images/default_banner.png?1783019845',
         'human_readable_role_for_display': 'Contributor',
         'id': 19737663,
         'iq': 122928,
         'is_meme_verified': False,
         'is_verified': False,
         'login': 'su11engir1',
         'name': 'su11engir1',
         'role_for_display': 'contributor',
         'url': 'https://genius.com/su11engir1',
         'current_user_metadata': {'permissions': [],
          'excluded_permissions': ['follow'],
          'interactions': {'following': False}}}}],
      'cosigned_by': [],
      'created_by': {'_type': 'user',
       'about_me_summary': 'Jesus died for somebody’s sins but not mine.\n\nLover of all things music, especially grunge, punk, 70s glam rock, folk, new wave, and anything female fronted.\n\nDMs are open if you have any questions or would like to say something to me.',
       'api_path': '/users/19737663',
       'avatar': {'tiny': {'url': 'https://images.genius.com/avatars/tiny/c38818b528fe039e11c8c7ec54ef107d',
         'bounding_box': {'width': 16, 'height': 16}},
        'thumb': {'url': 'https://images.genius.com/avatars/thumb/c38818b528fe039e11c8c7ec54ef107d',
         'bounding_box': {'width': 32, 'height': 32}},
        'small': {'url': 'https://images.genius.com/avatars/small/c38818b528fe039e11c8c7ec54ef107d',
         'bounding_box': {'width': 100, 'height': 100}},
        'medium': {'url': 'https://images.genius.com/avatars/medium/c38818b528fe039e11c8c7ec54ef107d',
         'bounding_box': {'width': 300, 'height': 400}}},
       'header_image_url': 'https://assets.genius.com/images/default_banner.png?1783019845',
       'human_readable_role_for_display': 'Contributor',
       'id': 19737663,
       'iq': 122928,
       'is_meme_verified': False,
       'is_verified': False,
       'login': 'su11engir1',
       'name': 'su11engir1',
       'role_for_display': 'contributor',
       'url': 'https://genius.com/su11engir1',
       'current_user_metadata': {'permissions': [],
        'excluded_permissions': ['follow'],
        'interactions': {'following': False}}},
      'rejection_comment': None,
      'top_comment': None,
      'verified_by': None}]}},
  {'_type': 'cover_art',
   'annotated': False,
   'api_path': '/albums/40578',
   'id': 1133735,
   'image_url': 'https://images.genius.com/0833a69b5b1cf7cded7dc9ff78d90c5d.600x596x1.jpg',
   'thumbnail_image_url': 'https://images.genius.com/0833a69b5b1cf7cded7dc9ff78d90c5d.300x298x1.jpg',
   'url': 'https://genius.com/album_cover_arts/1133735',
   'current_user_metadata': {'permissions': [],
    'excluded_permissions': ['destroy']},
   'description_annotation': {'_type': 'referent',
    'annotator_id': 19737663,
    'annotator_login': 'su11engir1',
    'api_path': '/referents/31438649',
    'classification': 'needs_exegesis',
    'fragment': 'https://images.genius.com/0833a69b5b1cf7cded7dc9ff78d90c5d.600x596x1.jpg',
    'id': 31438649,
    'ios_app_url': 'genius://referents/31438649',
    'is_description': True,
    'is_image': True,
    'path': '/31438649/Temple-of-the-dog/Https-imagesgeniuscom-0833a69b5b1cf7cded7dc9ff78d90c5d600x596x1jpg',
    'range': {'content': 'https://images.genius.com/0833a69b5b1cf7cded7dc9ff78d90c5d.600x596x1.jpg'},
    'song_id': None,
    'url': 'https://genius.com/31438649/Temple-of-the-dog/Https-imagesgeniuscom-0833a69b5b1cf7cded7dc9ff78d90c5d600x596x1jpg',
    'verified_annotator_ids': [],
    'current_user_metadata': {'permissions': [],
     'excluded_permissions': ['add_pinned_annotation_to',
      'add_community_annotation_to'],
     'relationships': {}},
    'tracking_paths': {'aggregate': '/31438649/Temple-of-the-dog/Https-imagesgeniuscom-0833a69b5b1cf7cded7dc9ff78d90c5d600x596x1jpg',
     'concurrent': '/albums/Temple-of-the-dog/Temple-of-the-dog'},
    'twitter_share_message': '“?” —@Genius',
    'annotatable': {'_type': 'cover_art',
     'api_path': '/albums/40578',
     'context': 'Temple of the Dog',
     'id': 1133735,
     'image_url': 'https://images.genius.com/0833a69b5b1cf7cded7dc9ff78d90c5d.300x298x1.jpg',
     'link_title': 'Temple of the Dog',
     'title': 'Temple of the Dog',
     'type': 'CoverArt',
     'url': 'https://genius.com/album_cover_arts/1133735'},
    'annotations': [{'_type': 'annotation',

In [317]:
#Pandas dataframe columns

temple_dog_df = pd.DataFrame(columns=['track_title', 'track_lyrics', 'album_name', 'project_name', 'release_year', 'label'])

In [318]:
track_title = []

for track in dog["tracks"]:
    track_title.append(track['song']['title'])

In [319]:
temple_dog_df['track_title'] = track_title

In [320]:
track_lyrics = []

for lyric in dog["tracks"]:
    track_lyrics.append(lyric['song']['lyrics'])

In [321]:
temple_dog_df['track_lyrics'] = track_lyrics

In [322]:
temple_dog_df['album_name']= dog['name']

In [323]:
temple_dog_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Say Hello 2 Heaven,"[Intro]\nYeah, yeah\nOoh, ooh\n\n[Verse 1]\nPl...",Temple of the Dog,NaN,NaN,NaN
1,Reach Down,"[Verse 1]\nWell, I had a dream the other night...",Temple of the Dog,NaN,NaN,NaN
2,Hunger Strike,[Verse: Chris Cornell]\nWell I don't mind stea...,Temple of the Dog,NaN,NaN,NaN
3,Pushin’ Forward Back,"[Verse 1]\nMother, mother found me on her step...",Temple of the Dog,NaN,NaN,NaN
4,Call Me a Dog,"[Verse 1]\nYou call me a dog, well, that's fai...",Temple of the Dog,NaN,NaN,NaN
5,Times of Trouble,[Verse 1]\nWhen the spoon is hot and the needl...,Temple of the Dog,NaN,NaN,NaN
6,Wooden Jesus,"[Verse 1]\nWooden Jesus, where are you from?\n...",Temple of the Dog,NaN,NaN,NaN
7,Your Saviour,"[Verse 1]\nYeah, people like you, I know mysel...",Temple of the Dog,NaN,NaN,NaN
8,Four Walled World,"[Verse 1]\nWell, she cries, and she cries\nAll...",Temple of the Dog,NaN,NaN,NaN
9,All Night Thing,[Verse 1]\nShe motioned to me that she wanted ...,Temple of the Dog,NaN,NaN,NaN

In [324]:
temple_dog_df['release_year']= dog['release_date_components']['year']

In [345]:
temple_dog_df['label']=dog['song_performances'][8]['artists'][0]['name']

In [346]:
temple_dog_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Say Hello 2 Heaven,"[Intro]\nYeah, yeah\nOoh, ooh\n\n[Verse 1]\nPl...",Temple of the Dog,NaN,1991,A&M Records
1,Reach Down,"[Verse 1]\nWell, I had a dream the other night...",Temple of the Dog,NaN,1991,A&M Records
2,Hunger Strike,[Verse: Chris Cornell]\nWell I don't mind stea...,Temple of the Dog,NaN,1991,A&M Records
3,Pushin’ Forward Back,"[Verse 1]\nMother, mother found me on her step...",Temple of the Dog,NaN,1991,A&M Records
4,Call Me a Dog,"[Verse 1]\nYou call me a dog, well, that's fai...",Temple of the Dog,NaN,1991,A&M Records
5,Times of Trouble,[Verse 1]\nWhen the spoon is hot and the needl...,Temple of the Dog,NaN,1991,A&M Records
6,Wooden Jesus,"[Verse 1]\nWooden Jesus, where are you from?\n...",Temple of the Dog,NaN,1991,A&M Records
7,Your Saviour,"[Verse 1]\nYeah, people like you, I know mysel...",Temple of the Dog,NaN,1991,A&M Records
8,Four Walled World,"[Verse 1]\nWell, she cries, and she cries\nAll...",Temple of the Dog,NaN,1991,A&M Records
9,All Night Thing,[Verse 1]\nShe motioned to me that she wanted ...,Temple of the Dog,NaN,1991,A&M Records

In [347]:
temple_dog_df['project_name']=dog['primary_artist_names']

In [348]:
temple_dog_df

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Say Hello 2 Heaven,"[Intro]\nYeah, yeah\nOoh, ooh\n\n[Verse 1]\nPl...",Temple of the Dog,Temple of the Dog,1991,A&M Records
1,Reach Down,"[Verse 1]\nWell, I had a dream the other night...",Temple of the Dog,Temple of the Dog,1991,A&M Records
2,Hunger Strike,[Verse: Chris Cornell]\nWell I don't mind stea...,Temple of the Dog,Temple of the Dog,1991,A&M Records
3,Pushin’ Forward Back,"[Verse 1]\nMother, mother found me on her step...",Temple of the Dog,Temple of the Dog,1991,A&M Records
4,Call Me a Dog,"[Verse 1]\nYou call me a dog, well, that's fai...",Temple of the Dog,Temple of the Dog,1991,A&M Records
5,Times of Trouble,[Verse 1]\nWhen the spoon is hot and the needl...,Temple of the Dog,Temple of the Dog,1991,A&M Records
6,Wooden Jesus,"[Verse 1]\nWooden Jesus, where are you from?\n...",Temple of the Dog,Temple of the Dog,1991,A&M Records
7,Your Saviour,"[Verse 1]\nYeah, people like you, I know mysel...",Temple of the Dog,Temple of the Dog,1991,A&M Records
8,Four Walled World,"[Verse 1]\nWell, she cries, and she cries\nAll...",Temple of the Dog,Temple of the Dog,1991,A&M Records
9,All Night Thing,[Verse 1]\nShe motioned to me that she wanted ...,Temple of the Dog,Temple of the Dog,1991,A&M Records

In [ ]:
# df_normalized = pd.json_normalize(d, sep='_')
# print("DataFrame using pd.json_normalize:")
# df_normalized

In [ ]:
# df_normalized.melt

In [ ]:
# df_normalized.columns